#!/usr/bin/env bash
#
# shell script to know on which hardware we are
#
# Administrator, Jun 1992
# yafra.org, Switzerland
#
# return: hardware type
#         HPUX400
#         HPUX700
#         LINUX
#         SCO
#         DOS
#         DEC
#

SYSTEM=`uname -s`
MACHINETYPE=`uname -m`

# Test for HP Platform
#
if test "$SYSTEM" = "HP-UX"
	then TMP=`echo $MACHINETYPE | cut -c1-6`
	case $TMP in
		"9000/3") HARDWARE=HPUX400;;
		"9000/4") HARDWARE=HPUX400;;
		"9000/7") HARDWARE=HPUX700;;
		"9000/8") HARDWARE=HPUX700;;
	esac
fi

# test for DEC Ultrix
#
if test "$SYSTEM" = "ULTRIX"
	then HARDWARE=ULTRIX
fi

# test for Linux
#
if test "$SYSTEM" = "Linux"
	then HARDWARE=$MACHINETYPE
fi

# Test for cygwin
#
if [[ "$SYSTEM" == *CYGWIN* ]]
	then HARDWARE=$MACHINETYPE
fi

# test if SCO (to hell with uname !!)
#
if test "$SYSTEM" = "james"
	then HARDWARE=SCO
fi

# put the platform string to the stdout
echo $HARDWARE
