#!/usr/bin/env bash
#
# shell script to know on which hardware we are
#
# Administrator, Jun 1992
# yafra.org, Switzerland
#
# return: include path of Motif
#

SYSTEM=`uname -s`

# Test for HP Platform
#
if test "$SYSTEM" = "HP-UX"
	then INCMOTIF=/usr/include/Motif2.1
fi

# Test for cygwin
#
if [[ "$SYSTEM" == *CYGWIN* ]]
	then INCMOTIF=/usr/include
fi

# test for Linux
#
if test "$SYSTEM" = "Linux"
	then INCMOTIF=/usr/include
fi

# put the platform string to the stdout
echo $INCMOTIF
