#!/usr/bin/env bash
#
# shell script to know on which system we are
#
# Administrator, Jun 1992
# yafra.org, Switzerland
#
# return os type:
#         ps_unix
#         ps_win
#         ps_dos
#

SYSTEMNAME=`uname -s`

# Test for HP Platform
#
if test "$SYSTEMNAME" = "HP-UX"
	then GET_OSTYPE=ps_unix
fi

# test for DEC Ultrix
#
if test "$SYSTEMNAME" = "ULTRIX"
	then GET_OSTYPE=ps_unix
fi

# test for Linux
#
if test "$SYSTEMNAME" = "Linux"
	then GET_OSTYPE=ps_unix
fi

# test for Mac OS/X
#
if test "$SYSTEMNAME" = "Darwin"
	then GET_OSTYPE=ps_unix
fi

# Test for cygwin
#
if [[ "$SYSTEMNAME" == *CYGWIN* ]]
	then GET_OSTYPE=ps_unix
fi


# test for SCO 386/486 Unix
#
if test "$SYSTEMNAME" = "SCO"
	then GET_OSTYPE=ps_unix
fi

# put the platform string to the stdout
echo $GET_OSTYPE
