#!/usr/bin/env bash
#-------------------------------------------------------------------------------
#  Copyright 2012 yafra.org
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#-------------------------------------------------------------------------------
#
# Author:       Administrator
#
# Purpose:     checkout release from code repository
#
# git usage    clone first, checkout tag/branch
#-------------------------------------------------------------------------------

#
# make sure the generic profile is loaded and you have enough permissions!!
#
if [ ! -d $SYSADM/defaults ]
then
	echo "Environment not loaded - install first !"
	exit
fi

# get newest source via git pull without pwd
echo "reset source now"
cd $BASENODE
cd ..
rm -rf YafraLocalGit/
git clone git://yafra.git.sourceforge.net/gitroot/yafra/yafra YafraLocalGit


if [ $# == 1 ]
then
	echo "get brance or tag $1"
	cd $BASENODE
	git checkout $1
	#git branch -v
fi


