#!/usr/bin/env bash
#
# shell script to know on which hardware we are
#
# Administrator, Jun 1992
# yafra.org, Switzerland
#
# return: include path of X11
#

SYSTEM=`uname -s`

# Test for HP Platform
#
if test "$SYSTEM" = "HP-UX"
	then INCX11=/usr/include/X11R6
fi

# Test for cygwin
#
if [[ "$SYSTEM" == *CYGWIN* ]]
	then INCX11=/usr/include
fi

# test for Linux
#
if test "$SYSTEM" = "Linux"
	then INCX11=/usr/include
fi

# put the platform string to the stdout
echo $INCX11
