#!/bin/sh
#-------------------------------------------------------------------------------
# yafra.oro
#
# function:	make a general C include file with version information
#           $1: name of program
#           $2: version string
#
#
# author:	Administrator  
#
# date:		19.12.94
#-------------------------------------------------------------------------------
#
# last modified:
#
#-------------------------------------------------------------------------------

# for date format
LANG=german

# version strings
VER_CORENAME=$1
VER_VERSION=$2
VER_NO=$2
VER_COMPILE="$(hostname):$(whoami) $(date +%d.%m.%y)"
VER_OS="$(uname -s) $(uname -r)"
VER_HW="$(uname -m)"

# obsolete
echo "#define MAINVERSION \"$VER_CORENAME $VER_VERSION $VER_COMPILE\""

# version string for pswhat and -v options
echo "#define PSPROJECTVERSION \"$VER_CORENAME $VER_VERSION\""
echo "#define PSVERSION \"$VER_CORENAME $VER_VERSION\""
echo "#define PSVERINFO \"$VER_OS $VER_HW $VER_COMPILE\""
echo "#define PSVERNO \"$VER_NO\""
echo "#define PSIDENT \"$VER_CORENAME $VER_VERSION $VER_OS $VER_HW $VER_COMPILE\""
echo "static char ident[]=\"@(#)$VER_CORENAME $VER_VERSION $VER_OS $VER_HW $VER_COMPILE\";"
