/*D***********************************************************
 * header:    Datenbankspezifische Angaben
 *            Hier wird das Header der spezifischen DB angegeben
 *
 * copyright: yafra.org, Basel, Switzerland
 *************************************************************/
/*R
 RCS Information:
 $Header: /yafra/cvsroot/mapo/source/include/mpdbglob.h,v 1.7 2008-11-02 19:55:32 mwn Exp $
*/

/*************************************************************
 * section: table definition for MARCO POLO database
 *          order must be the same as in MPobj_def.h
 *
 * not null = 1 Einheit
 * null     = 2 Einheiten
 *************************************************************/

static struct {
		char  *name;
		int   sqln;
		int   sqlnrow;
		int   sqlrowlen;
		struct {
			int typ;
			int leng;
		} elements[SQL_MAX_ROW];
} def_table[] = {
	{ "MAXIMA", 8, SQL_MAX_ROW, sizeof(MAXIMA),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4 } },
	{ "SPRACHEN", 8, SQL_MAX_ROW, sizeof(SPRACHEN),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_CHAR,256, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4 } },
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "STATUS_WERTE", 6, SQL_MAX_ROW, sizeof(STATUS_WERTE),
	{ DB_INT,4, DB_CHAR,256, DB_CHAR,1024, DB_INT,4, DB_DOUBLE,8, DB_INT,8 } },
#else
#if defined(ps_linux)
	{ "STATUS_WERTE", 6, SQL_MAX_ROW, sizeof(STATUS_WERTE),
	{ DB_INT,4, DB_CHAR,256, DB_CHAR,1024, DB_INT,4, DB_DOUBLE,8, DB_INT,4 } },
#else
	{ "STATUS_WERTE", 6, SQL_MAX_ROW, sizeof(STATUS_WERTE),
	{ DB_INT,4, DB_CHAR,256, DB_CHAR,1024, DB_INT,8, DB_DOUBLE,8, DB_INT,8 } },
#endif
#endif
	{ "BEZEICHNUNG", 4, SQL_MAX_ROW, sizeof(BEZEICHNUNG),
	{ DB_INT,4, DB_INT,4, DB_CHAR,1024, DB_INT,4 } },
	{ "TEXTE", 5, SQL_MAX_ROW, sizeof(TEXTE),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_CHAR,1024, DB_INT,4 } },
	{ "AKTIONSTEXTE", 5, SQL_MAX_ROW, sizeof(AKTIONSTEXTE),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_CHAR,1024, DB_INT,4 } },
	{ "HELP", 5, SQL_MAX_ROW, sizeof(HELP),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_CHAR,1024 } },
	{ "MSG", 5, SQL_MAX_ROW, sizeof(MP_MSG),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_CHAR,1024 } },
	{ "LABEL", 6, SQL_MAX_ROW, sizeof(LABEL),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_CHAR,1024 } },
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "SAISON", 8, SQL_MAX_ROW, sizeof(SAISON),
	{ DB_INT,4, DB_CHAR,256, DB_NULLIND,4, DB_INT,8, DB_LONG,8, DB_LONG,8, DB_INT,4, DB_NULLIND,4 } },
#else
	{ "SAISON", 8, SQL_MAX_ROW, sizeof(SAISON),
	{ DB_INT,4, DB_CHAR,256, DB_NULLIND,4, DB_INT,4, DB_LONG,8, DB_LONG,8, DB_INT,4, DB_NULLIND,4 } },
#endif

#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "LAND", 16, SQL_MAX_ROW, sizeof(LAND),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_NULLIND,2, DB_CHAR,256,
	  DB_NULLIND,2, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4,
	  DB_NULLIND,8, DB_DOUBLE,8, DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,2 } },
#elif defined(ps_linux)
	{ "LAND", 16, SQL_MAX_ROW, sizeof(LAND),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_NULLIND,2, DB_CHAR,256,
	  DB_NULLIND,2, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4,
	  DB_NULLIND,4, DB_DOUBLE,8, DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,2 } },
#else
	{ "LAND", 16, SQL_MAX_ROW, sizeof(LAND),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_NULLIND,2, DB_CHAR,256,
	  DB_NULLIND,2, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4,
	  DB_NULLIND,8, DB_DOUBLE,8, DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,8 } },
#endif
	{ "ORT", 15, SQL_MAX_ROW, sizeof(ORT),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_NULLIND,2,
	  DB_CHAR,256, DB_NULLIND,2, DB_INT,4, DB_NULLIND,4, DB_INT,4,
	  DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4 } },
	{ "WAEHRUNG", 8, SQL_MAX_ROW, sizeof(WAEHRUNG),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_NULLIND,4, DB_INT,4,
	  DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,2 } },
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "LAND_WHR", 7, SQL_MAX_ROW, sizeof(LAND_WHR),
	{ DB_INT,4, DB_INT,4, DB_INT,8, DB_DOUBLE,8, DB_DOUBLE,8, DB_LONG,8, DB_NULLIND,8 } },
#else
	{ "LAND_WHR", 7, SQL_MAX_ROW, sizeof(LAND_WHR),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_DOUBLE,8, DB_DOUBLE,8, DB_LONG,8, DB_NULLIND,4 } },
#endif
	{ "LAND_SPR", 2, SQL_MAX_ROW, sizeof(LAND_SPR),
	{ DB_INT,4, DB_INT,4 } },


	{ "TRAEGER_TYP", 6, SQL_MAX_ROW, sizeof(TRAEGER_TYP),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_NULLIND,4 } },
	{ "KATEGORIE", 9, SQL_MAX_ROW, sizeof(KATEGORIE),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_INT,4,
	  DB_NULLIND,4, DB_INT,4, DB_NULLIND,4 } },
	{ "DIENST_TRAEGER", 17, SQL_MAX_ROW, sizeof(DIENST_TRAEGER),
	{ DB_INT,4, DB_CHAR,256, DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_INT,4, DB_INT,4, DB_NULLIND,4, DB_INT,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4 } },
	{ "ANGEBOTS_TYP", 4, SQL_MAX_ROW, sizeof(ANGEBOTS_TYP),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_NULLIND,4 } },
	{ "AKTIONS_TYP", 5, SQL_MAX_ROW, sizeof(AKTIONS_TYP),
	{ DB_INT,4, DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_NULLIND,4 } },
	{ "AKTIONSPARA", 11, SQL_MAX_ROW, sizeof(AKTIONSPARA),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_NULLIND,4, DB_CHAR,1024,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4 } },
	{ "AKTIONEN", 15, SQL_MAX_ROW, sizeof(AKTIONEN),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_NULLIND,4, DB_INT,4,
	  DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4 } },
	{ "AKTIONSGRP", 4, SQL_MAX_ROW, sizeof(AKTIONSGRP),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4 } },
	{ "DIENST_ANGEBOT", 16, SQL_MAX_ROW, sizeof(DIENST_ANGEBOT),
	{ DB_INT,4, DB_CHAR,256, DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_CHAR,256, DB_INT,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_INT,4 } },

	{ "KUNDEN_TYP", 6, SQL_MAX_ROW, sizeof(KUNDEN_TYP),
	{ DB_INT,4, DB_CHAR,256, DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_NULLIND,4 } },
	{ "KUNDEN", 23, SQL_MAX_ROW, sizeof(KUNDEN),
	{ DB_INT,4, DB_CHAR,256, DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,2,
      DB_CHAR,256, DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,2,
      DB_CHAR,1024, DB_NULLIND,2, DB_CHAR,1024, DB_NULLIND,2,
      DB_CHAR,256, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_CHAR,1024, DB_NULLIND,2,
	  DB_CHAR,1024, DB_NULLIND,2, DB_INT,4, DB_INT,4 } },

#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "DLG_PART", 22, SQL_MAX_ROW, sizeof(DLG_PART),
	{ DB_INT,4, DB_CHAR,256, DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_NULLIND,8, DB_LONG,8, DB_NULLIND,8, DB_LONG,8, DB_NULLIND,4,
	  DB_INT,4, DB_INT,4, DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,2,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_NULLIND,8 } },
#else
	{ "DLG_PART", 22, SQL_MAX_ROW, sizeof(DLG_PART),
	{ DB_INT,4, DB_CHAR,256, DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_NULLIND,4, DB_LONG,8, DB_NULLIND,4, DB_LONG,8, DB_NULLIND,4,
	  DB_INT,4, DB_INT,4, DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,2,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_NULLIND,4 } },
#endif
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "DIENSTLEISTUNG", 11, SQL_MAX_ROW, sizeof(DIENSTLEISTUNG),
	{ DB_INT,4, DB_CHAR,256, DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_NULLIND,4, DB_INT,4,
	  DB_LONG,8, DB_NULLIND,4, DB_INT,4, DB_NULLIND,8 } },
#else
	{ "DIENSTLEISTUNG", 11, SQL_MAX_ROW, sizeof(DIENSTLEISTUNG),
	{ DB_INT,4, DB_CHAR,256, DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_NULLIND,4, DB_INT,4,
	  DB_LONG,8, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4 } },
#endif
	{ "DLG_DLG", 3, SQL_MAX_ROW, sizeof(DLG_DLG),
	{ DB_INT,4, DB_INT,4, DB_INT,4 } },
	{ "PROGRAMM", 7, SQL_MAX_ROW, sizeof(PROGRAMM),
	{ DB_INT,4, DB_CHAR,256, DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_NULLIND,4, DB_INT,4 } },
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "ARRANGEMENT", 9, SQL_MAX_ROW, sizeof(ARRANGEMENT),
	{ DB_INT,4, DB_CHAR,256, DB_NULLIND,4, DB_INT,8, DB_LONG,8, DB_INT,4, DB_INT,4,
	  DB_NULLIND,4, DB_INT,4 } },
#else
	{ "ARRANGEMENT", 9, SQL_MAX_ROW, sizeof(ARRANGEMENT),
	{ DB_INT,4, DB_CHAR,256, DB_NULLIND,4, DB_INT,4, DB_LONG,8, DB_INT,4, DB_INT,4,
	  DB_NULLIND,4, DB_INT,4 } },
#endif
	{ "ARR_DLG", 4, SQL_MAX_ROW, sizeof(ARR_DLG),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4 } },

	{ "KOLLEKTIV_TYP", 6, SQL_MAX_ROW, sizeof(KOLLEKTIV_TYP),
	{ DB_INT,4, DB_CHAR,256, DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_NULLIND,4 } },
	{ "KOLLEKTIV", 15, SQL_MAX_ROW, sizeof(KOLLEKTIV),
	{ DB_INT,4, DB_CHAR,256, DB_NULLIND,2, DB_CHAR,512, DB_NULLIND,2, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4 } },
	{ "PERSONEN", 8, SQL_MAX_ROW, sizeof(PERSONEN),
	{ DB_INT,4, DB_INT,4, DB_CHAR,512,
	  DB_INT,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4 } },
	{ "REISENDER_TYP", 10, SQL_MAX_ROW, sizeof(REISENDER_TYP),
	{ DB_INT,4, DB_CHAR,256, DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4 } },
	{ "REISENDER", 17, SQL_MAX_ROW, sizeof(REISENDER),
	{ DB_INT,4, DB_CHAR,512, DB_INT,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,2, DB_CHAR,256,
	  DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,2, DB_CHAR,1024, DB_NULLIND,2,
	  DB_CHAR,1024, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4 } },
	{ "PERSADR", 38, SQL_MAX_ROW, sizeof(PERSADR),
	{ DB_INT,4, DB_INT,4, DB_CHAR,256, DB_NULLIND,2, DB_CHAR,1024, DB_NULLIND,2,
	  DB_CHAR,1024, DB_NULLIND,2, DB_CHAR,1024, DB_NULLIND,2, DB_CHAR,256,
	  DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
      DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
      DB_CHAR,256, DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,2,
      DB_CHAR,256, DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,2, DB_CHAR,1024, DB_NULLIND,2,
      DB_CHAR,1024, DB_NULLIND,2 } },

#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
  	{ "HOST-KONTINGENT", 21, SQL_MAX_ROW, sizeof(HOST_KONT),
  	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
  	  DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_LONG,8, DB_NULLIND,8,
  	  DB_LONG,8, DB_NULLIND,4, DB_INT,4, DB_NULLIND,8, DB_LONG,8, DB_NULLIND,4,
  	  DB_INT,4, DB_CHAR,256, DB_NULLIND,4, DB_INT,4, DB_NULLIND,8 } },
#else
	{ "HOST-KONTINGENT", 21, SQL_MAX_ROW, sizeof(HOST_KONT),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_LONG,8, DB_NULLIND,4,
	  DB_LONG,8, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_LONG,8, DB_NULLIND,4,
	  DB_INT,4, DB_CHAR,256, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4 } },
#endif
	{ "KONTINGENT", 11, SQL_MAX_ROW, sizeof(KONTINGENT),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_LONG,8,
	  DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,2, DB_INT,4,
	  DB_INT,4, DB_NULLIND,4 } },
	{ "KONT_DETAIL", 14, SQL_MAX_ROW, sizeof(KONT_DETAIL),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_LONG,8, DB_LONG,8 } },

#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "BUCHUNG", 25, SQL_MAX_ROW, sizeof(BUCHUNG),
	{ DB_INT,4, DB_INT,4, DB_CHAR,256, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_INT,4, DB_LONG,8, DB_NULLIND,8,
	  DB_LONG,8, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,8 } },
#else
	{ "BUCHUNG", 25, SQL_MAX_ROW, sizeof(BUCHUNG),
	{ DB_INT,4, DB_INT,4, DB_CHAR,256, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_INT,4, DB_LONG,8, DB_NULLIND,4,
	  DB_LONG,8, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
      DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4 } },
#endif
	{ "AKT_DETAIL", 15, SQL_MAX_ROW, sizeof(AKT_DETAIL),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_INT,4, DB_INT,8, DB_INT,4, DB_NULLIND,4 } },
	{ "KOSTEN_ART", 4, SQL_MAX_ROW, sizeof(KOSTEN_ART),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_NULLIND,4 } },
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "KOMMISSION", 31, SQL_MAX_ROW, sizeof(KOMMISSION),
	{ DB_INT,4, DB_INT,4, DB_INT,8, DB_DOUBLE,8, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_LONG,8, DB_NULLIND,8,
	  DB_LONG,8, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_NULLIND,4 } },
#else
	{ "KOMMISSION", 31, SQL_MAX_ROW, sizeof(KOMMISSION),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_DOUBLE,8, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_LONG,8, DB_NULLIND,4,
	  DB_LONG,8, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_NULLIND,4 } },
#endif
	{ "KOMM_DETAIL", 7, SQL_MAX_ROW, sizeof(KOMM_DETAIL),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_NULLIND,4 } },
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "RESERVATION", 21, SQL_MAX_ROW, sizeof(RESERVATION),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_INT,8,
	  DB_LONG,8, DB_NULLIND,8, DB_LONG,8, DB_NULLIND,4, DB_INT,4, DB_NULLIND,8 } },
#else
	{ "RESERVATION", 21, SQL_MAX_ROW, sizeof(RESERVATION),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_INT,4,
	  DB_LONG,8, DB_NULLIND,4, DB_LONG,8, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4 } },
#endif
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "PREIS", 48, SQL_MAX_ROW, sizeof(PREIS),
	{ DB_INT,8, DB_DOUBLE,8, DB_DOUBLE,8, DB_DOUBLE,8,
	  DB_LONG,8, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_LONG,8, DB_NULLIND,8, DB_LONG,8, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_LONG,8, DB_NULLIND,8, DB_LONG,8, DB_NULLIND,8 } },
#else
	{ "PREIS", 48, SQL_MAX_ROW, sizeof(PREIS),
	{ DB_INT,4, DB_DOUBLE,8, DB_DOUBLE,8, DB_DOUBLE,8,
	  DB_LONG,8, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_LONG,8, DB_NULLIND,4, DB_LONG,8, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_LONG,8, DB_NULLIND,4, DB_LONG,8, DB_NULLIND,4 } },
#endif

	{ "GRAPHIK", 5, SQL_MAX_ROW, sizeof(GRAPHIK),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_NULLIND,4 } },
	{ "PCX_FILES", 10, SQL_MAX_ROW, sizeof(PCX_FILES),
	{ DB_INT,4, DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_INT,4 } },
	{ "GRAFORM", 3, SQL_MAX_ROW, sizeof (GRAFORM),
	{ DB_INT,4, DB_INT,4, DB_CHAR,256 } },
	{ "REGIONS", 6, SQL_MAX_ROW, sizeof (REGIONS),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_INT,4 } },

// TODO check padding on char/int in64bit mode
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "HISTORY", 6, SQL_MAX_ROW, sizeof(HISTORY),
	{ DB_INT,4, DB_INT,4, DB_INT,8, DB_CHAR,1024, DB_LONG,8, DB_INT,8 } },
#else
	{ "HISTORY", 6, SQL_MAX_ROW, sizeof(HISTORY),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_CHAR,1024, DB_LONG,8, DB_INT,4 } },
#endif

	{ "BCH_DLN", 2, SQL_MAX_ROW, sizeof(BCH_DLN),
	{ DB_INT,4, DB_INT,4 } },
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "KAPA", 13, SQL_MAX_ROW, sizeof(KAPA),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,8, DB_DOUBLE,8, DB_NULLIND,8, DB_LONG,8, DB_LONG,8 } },
#else
	{ "KAPA", 13, SQL_MAX_ROW, sizeof(KAPA),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_DOUBLE,8, DB_NULLIND,4, DB_LONG,8, DB_LONG,8 } },
#endif
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "MP_PROFIL", 16, SQL_MAX_ROW, sizeof(MP_PROFIL),
	{ DB_INT,4, DB_CHAR,128, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_LONG,8, DB_LONG,8, DB_INT,8 } },
#else
	{ "MP_PROFIL", 16, SQL_MAX_ROW, sizeof(MP_PROFIL),
	{ DB_INT,4, DB_CHAR,128, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_LONG,8, DB_LONG,8, DB_INT,4 } },
#endif
	{ "MP_ARRKOM", 3, SQL_MAX_ROW, sizeof(MP_ARRKOM),
	{ DB_INT,4, DB_INT,4, DB_INT,4 } },

	{ NULL }, { NULL }, { NULL },

	{ "DATUM", 1, SQL_MAX_ROW, sizeof(double), { DB_DOUBLE, 8 } },
	{ "SHORT", 1, SQL_MAX_ROW, sizeof(short), { DB_SHORT, 2 } },
	{ "INTEGER", 1, SQL_MAX_ROW, sizeof(int), { DB_INT, 4 } },
	{ "LONG", 1, SQL_MAX_ROW, sizeof(long), { DB_LONG, 8 } },
	{ "DOUBLE", 1, SQL_MAX_ROW, sizeof(double), { DB_DOUBLE, 8 } },

	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },

	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL }, { NULL }, { NULL },
	{ NULL }, { NULL }, { NULL },

	{ "SYS_COLUMN", 13, SQL_MAX_ROW, sizeof(SYS_COLUMN),
	{ DB_INT,4, DB_INT,4, DB_CHAR,32, DB_INT,4, DB_CHAR,32 } },
	{ "SYS_INDEX", 11, SQL_MAX_ROW, sizeof(SYS_INDEX),
	{ DB_INT,4, DB_INT,4, DB_CHAR,32, DB_INT,4, DB_CHAR,32 } },

	{ "SPR_VIEW", 5, SQL_MAX_ROW, sizeof(SPR_VIEW),
	{ DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_INT,4, DB_CHAR,256 } },
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "STA_VIEW", 7, SQL_MAX_ROW, sizeof(STA_VIEW),
	{ DB_INT,4, DB_CHAR,256, DB_CHAR,1024, DB_CHAR,1024, DB_INT,4,
	  DB_DOUBLE,8, DB_INT,8 } },
#else
	{ "STA_VIEW", 7, SQL_MAX_ROW, sizeof(STA_VIEW),
	{ DB_INT,4, DB_CHAR,256, DB_CHAR,1024, DB_CHAR,1024, DB_INT,4,
	  DB_DOUBLE,8, DB_INT,4 } },
#endif
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "SAI_VIEW", 7, SQL_MAX_ROW, sizeof(SAI_VIEW),
	{ DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_LONG,8, DB_LONG,8,
	  DB_INT,4, DB_NULLIND,4 } },
#else
	{ "SAI_VIEW", 7, SQL_MAX_ROW, sizeof(SAI_VIEW),
	{ DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_LONG,8, DB_LONG,8,
	  DB_INT,4, DB_NULLIND,4 } },
#endif

#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "LAND_VIEW", 15, SQL_MAX_ROW, sizeof(LAND_VIEW),
	{ DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_CHAR,256, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,8,
	  DB_DOUBLE,8, DB_NULLIND,8 } },
#else
	{ "LAND_VIEW", 15, SQL_MAX_ROW, sizeof(LAND_VIEW),
	{ DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_CHAR,256, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_DOUBLE,8, DB_NULLIND,4 } },
#endif

	{ "KUN_VIEW", 27, SQL_MAX_ROW, sizeof(KUN_VIEW),
	{ DB_INT,4, DB_CHAR,512, DB_CHAR,256, DB_INT,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,2,
	  DB_CHAR,256, DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,2,
	  DB_INT,4, DB_NULLIND,2, DB_CHAR,1024, DB_NULLIND,2, DB_CHAR,1024, DB_NULLIND,4,
	  DB_INT,4, DB_INT,4, DB_INT,4 } },
	{ "DLN_VIEW", 24, SQL_MAX_ROW, sizeof(DLN_VIEW),
	{ DB_INT,4, DB_CHAR,512, DB_CHAR,512, DB_CHAR,256, DB_INT,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_NULLIND,4, DB_INT,4,
	  DB_NULLIND,4, DB_INT,4, DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,2,
	  DB_CHAR,256, DB_NULLIND,2, DB_CHAR,1024, DB_NULLIND,2, DB_CHAR,1024,
	  DB_NULLIND,4 } },
	{ "RKR_VIEW", 11, SQL_MAX_ROW, sizeof(RKR_VIEW),
	{ DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_INT,4, DB_NULLIND,2,
	  DB_CHAR,256, DB_NULLIND,2, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_NULLIND,4 } },

	{ "TTYP_VIEW", 5, SQL_MAX_ROW, sizeof(TTYP_VIEW),
	{ DB_INT,4, DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_CHAR,1024 } },
	{ "KAT_VIEW", 10, SQL_MAX_ROW, sizeof(KAT_VIEW),
	{ DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_INT,4, DB_NULLIND,4, DB_INT,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4 } },
	{ "TRAEGER_VIEW", 6, SQL_MAX_ROW, sizeof(TRAEGER_VIEW),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_CHAR,1024, DB_INT,4,
	  DB_INT,4 } },
	{ "DLT_VIEW", 11, SQL_MAX_ROW, sizeof(DLT_VIEW),
	{ DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_INT,4,
	  DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_NULLIND,4, DB_INT,4 } },
	{ "AKT_VIEW", 5, SQL_MAX_ROW, sizeof(AKT_VIEW),
	{ DB_INT,4, DB_CHAR,1024, DB_CHAR,1024, DB_INT,4, DB_INT,4 } },
	{ "DLA_VIEW", 15, SQL_MAX_ROW, sizeof(DLA_VIEW),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_CHAR,1024,
	  DB_INT,4, DB_INT,4, DB_CHAR,256, DB_INT,4, DB_INT,4,
	  DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_INT,4 } },
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "DLG_VIEW", 19, SQL_MAX_ROW, sizeof(DLG_VIEW),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_CHAR,1024, DB_INT,4,
	  DB_INT,4, DB_NULLIND,4, DB_LONG,8, DB_NULLIND,8, DB_LONG,8,
	  DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_NULLIND,4, DB_CHAR,256,
	  DB_NULLIND,4, DB_INT,4, DB_NULLIND,4, DB_INT,4 } },
#else
	{ "DLG_VIEW", 19, SQL_MAX_ROW, sizeof(DLG_VIEW),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_CHAR,1024, DB_INT,4,
	  DB_INT,4, DB_NULLIND,4, DB_LONG,8, DB_NULLIND,4, DB_LONG,8,
	  DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_NULLIND,2, DB_CHAR,256,
	  DB_NULLIND,2, DB_INT,4, DB_NULLIND,4, DB_INT,4 } },
#endif
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "DLDLG_VIEW", 12, SQL_MAX_ROW, sizeof(DLDLG_VIEW),
	{ DB_INT,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_CHAR,1024,
	  DB_LONG,8, DB_NULLIND,8, DB_LONG,8, DB_NULLIND,4, DB_INT,4,
	  DB_INT,4, DB_INT,4 } },
#else
	{ "DLDLG_VIEW", 12, SQL_MAX_ROW, sizeof(DLDLG_VIEW),
	{ DB_INT,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_CHAR,1024,
	  DB_LONG,8, DB_NULLIND,4, DB_LONG,8, DB_NULLIND,4, DB_INT,4,
	  DB_INT,4, DB_INT,4 } },
#endif
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "DTG_VIEW", 10, SQL_MAX_ROW, sizeof(DTG_VIEW),
	{ DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,8, DB_INT,8, DB_NULLIND,8, DB_INT,4, DB_NULLIND,4 } },
#else
	{ "DTG_VIEW", 10, SQL_MAX_ROW, sizeof(DTG_VIEW),
	{ DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_INT,4, DB_NULLIND,4,
	  DB_INT,4, DB_INT,8, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4 } },
#endif
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "ARRDL_VIEW", 11, SQL_MAX_ROW, sizeof(ARRDL_VIEW),
	{ DB_INT,8, DB_LONG,8, DB_INT,8, DB_CHAR,1024, DB_LONG,8,
	  DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_NULLIND,4, DB_INT,4 } },
#else
	{ "ARRDL_VIEW", 11, SQL_MAX_ROW, sizeof(ARRDL_VIEW),
	{ DB_INT,4, DB_LONG,8, DB_INT,4, DB_CHAR,1024, DB_LONG,8,
	  DB_NULLIND,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_NULLIND,4, DB_INT,4 } },
#endif
	{ "ARR_VIEW", 8, SQL_MAX_ROW, sizeof(ARR_VIEW),
	{ DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_LONG,8, DB_INT,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4 } },
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "ARR_DETAIL", 14, SQL_MAX_ROW, sizeof(ARR_DETAIL),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_LONG,8, DB_NULLIND,4, DB_INT,4, DB_CHAR,1024,
	  DB_CHAR,1024, DB_INT,8, DB_LONG,8, DB_NULLIND,8 } },
#else
	{ "ARR_DETAIL", 14, SQL_MAX_ROW, sizeof(ARR_DETAIL),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_LONG,8, DB_NULLIND,4, DB_INT,4, DB_CHAR,1024,
	  DB_CHAR,1024, DB_INT,4, DB_LONG,8, DB_NULLIND,4 } },
#endif

#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "KON_VIEW", 12, SQL_MAX_ROW, sizeof(KON_VIEW),
	{ DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_LONG,8, DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,2,
	  DB_INT,4, DB_INT,4, DB_NULLIND,4 } },
#else
	{ "KON_VIEW", 12, SQL_MAX_ROW, sizeof(KON_VIEW),
	{ DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_LONG,8, DB_NULLIND,2, DB_CHAR,256, DB_NULLIND,2,
	  DB_INT,4, DB_INT,4, DB_NULLIND,4 } },
#endif

	{ "AKT_DETAIL_VIEW", 12, SQL_MAX_ROW, sizeof(AKT_DETAIL_VIEW),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_CHAR,1024 } },
	{ "KAR_VIEW", 5, SQL_MAX_ROW, sizeof(KAR_VIEW),
	{ DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_INT,4, DB_NULLIND,4 } },
	{ "GRA_VIEW", 7, SQL_MAX_ROW, sizeof(GRA_VIEW),
	{ DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_CHAR,1024, DB_INT,4,
	  DB_NULLIND,4, DB_INT,4 } },
	{ "KONCHECK_VIEW", 8, SQL_MAX_ROW, sizeof(KONCHECK_VIEW),
	{ DB_INT,4, DB_INT,4, DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4 } },
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "MPV_KAPA", 13, SQL_MAX_ROW, sizeof(MPV_KAPA),
	{ DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_INT,4, DB_CHAR,1024, DB_INT,4,
	  DB_INT,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,8,
	  DB_DOUBLE,8, DB_NULLIND,8 } },
#else
	{ "MPV_KAPA", 13, SQL_MAX_ROW, sizeof(MPV_KAPA),
	{ DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_INT,4, DB_CHAR,1024, DB_INT,4,
	  DB_INT,4, DB_INT,4, DB_NULLIND,4, DB_INT,4, DB_NULLIND,4,
	  DB_DOUBLE,8, DB_NULLIND,4 } },
#endif
	{ "ROUTEN_VIEW", 7, SQL_MAX_ROW, sizeof(ROUTEN_VIEW),
	{ DB_INT,4, DB_CHAR,1024, DB_INT,4, DB_CHAR,256, DB_NULLIND,2,
	  DB_CHAR,256, DB_NULLIND,2 } },
	{ "MPV_DLNADR", 18, SQL_MAX_ROW, sizeof(MPV_DLNADR),
	{ DB_INT,4,     DB_CHAR,256,   DB_NULLIND,4, DB_CHAR,512,   DB_CHAR,512,
	  DB_CHAR,1024,   DB_NULLIND,2, DB_CHAR,1024,   DB_NULLIND,2, DB_CHAR,1024,
	  DB_NULLIND,2, DB_CHAR,256,   DB_NULLIND,2, DB_CHAR,256,
	  DB_INT,4,     DB_NULLIND,4, DB_INT,4,     DB_NULLIND,4  } },
	{ "MPV_KUNADR", 23, SQL_MAX_ROW, sizeof(MPV_KUNADR),
	{ DB_INT,4,     DB_CHAR,256,   DB_NULLIND,2, DB_CHAR,512, DB_CHAR,1024,
	  DB_NULLIND,2, DB_CHAR,1024,   DB_NULLIND,2, DB_CHAR,1024, DB_NULLIND,2,
	  DB_CHAR,256,   DB_NULLIND,2, DB_CHAR,256,   DB_CHAR,256, DB_NULLIND,2,
	  DB_INT,4,     DB_INT,4,     DB_NULLIND,4, DB_INT,4,   DB_CHAR,256,
	  DB_NULLIND,2, DB_CHAR,256,   DB_NULLIND,2 } },
	{ NULL },
	{ NULL },
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "RES_DL_VIEW", 23, SQL_MAX_ROW, sizeof(RES_DL_VIEW),
	{ DB_INT,4,     DB_INT,4,   DB_CHAR,512,   DB_INT,8,     DB_LONG,8,
	  DB_NULLIND,4, DB_INT,4,   DB_LONG,8,     DB_NULLIND,8, DB_LONG,8,
	  DB_NULLIND,8, DB_LONG,8,   DB_NULLIND,8, DB_LONG,8,    DB_NULLIND,4,
	  DB_INT,4,     DB_CHAR,1024, DB_INT,4,     DB_INT,4,    DB_CHAR,1024,
	  DB_INT,4,     DB_INT,4,   DB_INT,8 } },
#else
	{ "RES_DL_VIEW", 23, SQL_MAX_ROW, sizeof(RES_DL_VIEW),
	{ DB_INT,4,     DB_INT,4,   DB_CHAR,512,   DB_INT,4,     DB_LONG,8,
	  DB_NULLIND,4, DB_INT,4,   DB_LONG,8,     DB_NULLIND,4, DB_LONG,8,
	  DB_NULLIND,4, DB_LONG,8,   DB_NULLIND,4, DB_LONG,8,    DB_NULLIND,4,
	  DB_INT,4,     DB_CHAR,1024, DB_INT,4,     DB_INT,4,    DB_CHAR,1024,
	  DB_INT,4,     DB_INT,4,   DB_INT,4 } },
#endif
#if defined(x86_64) || defined(ps_win) || defined(ps_cygwin)
	{ "RESDLN_VIEW", 15, SQL_MAX_ROW, sizeof(RESDLN_VIEW),
	{ DB_INT,4, DB_INT,4, DB_CHAR,512,   DB_INT,4, DB_INT,4,
	  DB_INT,8, DB_LONG,8, DB_NULLIND,8, DB_LONG,8, DB_NULLIND,4,
	  DB_INT,4, DB_INT,4, DB_INT,4,     DB_INT,4, DB_INT,4 } },
#else
	{ "RESDLN_VIEW", 15, SQL_MAX_ROW, sizeof(RESDLN_VIEW),
	{ DB_INT,4, DB_INT,4, DB_CHAR,512,   DB_INT,4, DB_INT,4,
	  DB_INT,4, DB_LONG,8, DB_NULLIND,4, DB_LONG,8, DB_NULLIND,4,
	  DB_INT,4, DB_INT,4, DB_INT,4,     DB_INT,4, DB_INT,4 } },
#endif
	{ "RESDL_VIEW", 16, SQL_MAX_ROW, sizeof(RESDL_VIEW),
	{ DB_INT,4,   DB_INT,4,   DB_INT,4,   DB_INT,4, DB_CHAR,1024,
	  DB_INT,4,   DB_INT,4,   DB_LONG,8,   DB_NULLIND,4, DB_LONG,8,
	  DB_NULLIND,4,   DB_INT,4,   DB_INT,4,   DB_INT,4, DB_INT,4,   DB_INT,4 } },
	{ NULL }
};
