/**************************************************************/
/* Header:    SQL dynam. delete statements                    */
/*                                                            */
/* Copyright: yafra.org, Basel, Switzerland     */
/**************************************************************/
/*
 RCS Information:
 $Header: /yafra/cvsroot/mapo/source/include/mpsqldel.h,v 1.2 2008-11-02 19:55:32 mwn Exp $
*/

/*	Definition aller verwendbaren SQL-Delete Befehlen */
#define _DELETE_MAX  "DELETE FROM TDBADMIN.MAXIMA WHERE TABELLE = %d AND TYP = %d;"
#define _DELETE_SPR	"DELETE FROM TDBADMIN.SPRACHEN WHERE S_ID = %d;"
#define _DELETE_STA	"DELETE FROM TDBADMIN.STATUS_WERTE WHERE STA_ID = %d AND TYP = %d;"
#define _DELETE_BEZ	"DELETE FROM TDBADMIN.BEZEICHNUNG WHERE BEZ_ID = %d AND TYP = %d;"
#define _DELETE_TXT	"DELETE FROM TDBADMIN.TEXTE WHERE TEXTID = %d AND TYP = %d;"
#define _DELETE_SID_TXT	"DELETE FROM TDBADMIN.TEXTE WHERE TEXTID = %d AND TYP = %d AND S_ID = %d;"
#define _DELETE_HIS	"DELETE FROM TDBADMIN.HISTORY WHERE HIS_ID = %d;"
#define _DELETE_MSG  "DELETE FROM TDBADMIN.MSG WHERE MSG_ID = %d;"
#define _DELETE_SAI	"DELETE FROM TDBADMIN.SAISON WHERE SAI_ID = %d;"



#define _DELETE_WHR  "DELETE FROM TDBADMIN.WAEHRUNG WHERE WHR_ID = %d;"
#define _DELETE_LAND "DELETE FROM TDBADMIN.LAND WHERE LAND_ID = %d;"
#define _DELETE_ORT  "DELETE FROM TDBADMIN.ORT WHERE ORT_ID = %d;"
#define _DELETE_LW   "DELETE FROM TDBADMIN.LAND_WHR WHERE LAND_ID = %d AND WHR_ID = %d AND KURS_TYP = %d;"
#define _DELETE_LWALL "DELETE FROM TDBADMIN.LAND_WHR WHERE LAND_ID = %d AND WHR_ID = %d;"
#define _DELETE_LS   "DELETE FROM TDBADMIN.LAND_SPR WHERE LAND_ID = %d AND S_ID = %d;"




#define _DELETE_PERS	"DELETE FROM TDBADMIN.PERSONEN WHERE PERS_ID = %d;"
#define _DELETE_PERSADR	"DELETE FROM TDBADMIN.PERSADR WHERE PERS_ID = %d;"
/* REI und DLN sind synonym, gleiches fuer REIT - DLNT */
#define _DELETE_REI	"DELETE FROM TDBADMIN.REISENDER WHERE PERS_ID = %d;"
#define _DELETE_REIT	"DELETE FROM TDBADMIN.REISENDER_TYP WHERE RKR_ID = %d;"
#define _DELETE_DLN	"DELETE FROM TDBADMIN.REISENDER WHERE PERS_ID = %d;"
#define _DELETE_DLNT	"DELETE FROM TDBADMIN.REISENDER_TYP WHERE RKR_ID = %d;"
#define _DELETE_KUNT	"DELETE FROM TDBADMIN.KUNDEN_TYP WHERE K_TYP_ID = %d;"
#define _DELETE_KUN	"DELETE FROM TDBADMIN.KUNDEN WHERE PERS_ID = %d;"
#define _DELETE_KOLT	"DELETE FROM TDBADMIN.KOLLEKTIV_TYP WHERE K_TYP_ID = %d;"
#define _DELETE_KOL	"DELETE FROM TDBADMIN.KOLLEKTIV WHERE K_ID = %d;"




#define _DELETE_DLTT	"DELETE FROM TDBADMIN.TRAEGER_TYP WHERE TYP_ID = %d;"
#define _DELETE_KAT	"DELETE FROM TDBADMIN.KATEGORIE WHERE KAT_ID = %d;"
#define _DELETE_DLT	"DELETE FROM TDBADMIN.DIENST_TRAEGER WHERE DLT_ID = %d;"
#define _DELETE_DLAT	"DELETE FROM TDBADMIN.ANGEBOTS_TYP WHERE ART_ID = %d;"
#define _DELETE_AKTT	"DELETE FROM TDBADMIN.AKTIONS_TYP WHERE A_TYP_ID = %d;"
#define _DELETE_AKTP	"DELETE FROM TDBADMIN.AKTIONSPARA WHERE A_TYP_ID = %d AND NR = %d;"
#define _DELETE_AKT	"DELETE FROM TDBADMIN.AKTIONEN WHERE AKT_ID = %d;"
#define _DELETE_AKTG "DELETE FROM TDBADMIN.AKTIONSGRP WHERE PARENTAKT = %d \
	AND CHILDAKT = %d AND ORD = %d;"
#define _DELETE_DLA	"DELETE FROM TDBADMIN.DIENST_ANGEBOT WHERE DLA_ID = %d;"
#define _DELETE_DLG	"DELETE FROM TDBADMIN.DLG_PARTS WHERE DL_ID = %d;"
#define _DELETE_DTG	"DELETE FROM TDBADMIN.DIENSTLEISTUNG WHERE DLG_ID = %d;"
#define _DELETE_DD	"DELETE FROM TDBADMIN.DLG_DLG WHERE DLG_ID = %d;"
#define _DELETE_ONE_DD	"DELETE FROM TDBADMIN.DLG_DLG WHERE DLG_ID = %d AND DL_ID = %d AND ORD = %d;"
#define _DELETE_PRG	"DELETE FROM TDBADMIN.PROGRAMM WHERE PRG_ID = %d;"
#define _DELETE_ARR	"DELETE FROM TDBADMIN.ARRANGEMENT WHERE ARR_ID = %d;"
#define _DELETE_AD	"DELETE FROM TDBADMIN.ARR_DLG WHERE ARR_ID = %d;"
#define _DELETE_ONE_AD	"DELETE FROM TDBADMIN.ARR_DLG WHERE ARR_ID = %d AND DLG_ID = %d AND TEIL = %d;"


#define _DELETE_HKON	"DELETE FROM TDBADMIN.HOST_KONT WHERE HOSTKONT_ID = %d;"
#define _DELETE_KON	"DELETE FROM TDBADMIN.KONTINGENT WHERE KONT_ID = %d;"
#define _DELETE_KOND_HKON		"DELETE FROM TDBADMIN.KONT_DETAIL WHERE HOSTKONT_ID = %d;"
#define _DELETE_KOND_HKONKAT	"DELETE FROM TDBADMIN.KONT_DETAIL WHERE HOSTKONT_ID = %d AND KAT_ID = %d;"
#define _DELETE_KOND_HKONDLT	"DELETE FROM TDBADMIN.KONT_DETAIL WHERE HOSTKONT_ID = %d AND DLT_ID = %d;"
#define _DELETE_KOND_KON		"DELETE FROM TDBADMIN.KONT_DETAIL WHERE KONT_ID = %d;"
#define _DELETE_KOND_KONKAT	"DELETE FROM TDBADMIN.KONT_DETAIL WHERE KONT_ID = %d AND KAT_ID = %d;"
#define _DELETE_KOND_KONDLT	"DELETE FROM TDBADMIN.KONT_DETAIL WHERE KONT_ID = %d AND DLT_ID = %d;"




#define _DELETE_BCH	"DELETE FROM TDBADMIN.BUCHUNG WHERE BID = %d;"
#define _DELETE_BD	"DELETE FROM TDBADMIN.BCH_DLN WHERE BID = %d AND DLN_ID = %d;"
#define _DELETE_BDBCH	"DELETE FROM TDBADMIN.BCH_DLN WHERE BID = %d;"
#define _DELETE_BDDLN	"DELETE FROM TDBADMIN.BCH_DLN WHERE DLN_ID = %d;"
#define _DELETE_AKTDET_BCH "DELETE FROM TDBADMIN.AKT_DETAIL WHERE BID=%d;"
#define _DELETE_AKTDET_DLN "DELETE FROM TDBADMIN.AKT_DETAIL \
	WHERE PERS_ID = %d;"
#define _DELETE_AKTDET_BCH_TEIL "DELETE FROM TDBADMIN.AKT_DETAIL \
	WHERE BID = %d AND TEIL = %d;"
#define _DELETE_AKTDET_BCH_DLN "DELETE FROM TDBADMIN.AKT_DETAIL \
	WHERE BID = %d AND PERS_ID = %d;"
#define _DELETE_AKTDET_BCH_DLN_TEIL "DELETE FROM TDBADMIN.AKT_DETAIL \
	WHERE BID = %d AND PERS_ID = %d AND TEIL = %d;"
#define _DELETE_KAR	"DELETE FROM TDBADMIN.KOSTEN_ART WHERE KAR_ID = %d;"
#define _DELETE_KOM	"DELETE FROM TDBADMIN.KOMMISSION WHERE KOMM_ID = %d;"

#define _DELETE_KOMD_KOM_BCH "DELETE FROM TDBADMIN.KOMM_DETAIL WHERE KOMM_ID = %d AND BID = %d;"
#define _DELETE_KOMD_KOM_DLN "DELETE FROM TDBADMIN.KOMM_DETAIL WHERE KOMM_ID = %d AND DLN_ID = %d;"
#define _DELETE_KOMD_KOM_KUN "DELETE FROM TDBADMIN.KOMM_DETAIL WHERE KOMM_ID = %d AND KUN_ID = %d;"
#define _DELETE_KOMD_KOM_KOL "DELETE FROM TDBADMIN.KOMM_DETAIL WHERE KOMM_ID = %d AND KOL_ID = %d;"
#define _DELETE_KOMD_KOM_DLN_BCH "DELETE FROM TDBADMIN.KOMM_DETAIL WHERE KOMM_ID = %d AND DLN_ID = %d AND BID = %d;"

#define _DELETE_KOMD_BCH "DELETE FROM TDBADMIN.KOMM_DETAIL WHERE BID = %d;"
#define _DELETE_KOMD_DLN "DELETE FROM TDBADMIN.KOMM_DETAIL WHERE DLN_ID = %d;"
#define _DELETE_KOMD_KUN "DELETE FROM TDBADMIN.KOMM_DETAIL WHERE KUN_ID = %d;"
#define _DELETE_KOMD_KOL "DELETE FROM TDBADMIN.KOMM_DETAIL WHERE KOL_ID = %d;"
#define _DELETE_KOMD_DLN_BCH "DELETE FROM TDBADMIN.KOMM_DETAIL WHERE DLN_ID = %d AND BID = %d;"

#define _DELETE_KOMD "DELETE FROM TDBADMIN.KOMM_DETAIL WHERE KOMM_ID = %d;"


#define _DELETE_PRE	"DELETE FROM TDBADMIN.PREIS WHERE PRE_ID = %d;"


#define _DELETE_RES_BCH "DELETE FROM TDBADMIN.RESERVATION WHERE BID=%d;"
#define _DELETE_RES_DLN "DELETE FROM TDBADMIN.RESERVATION WHERE PERS_ID=%d;"
#define _DELETE_RES_BCH_DLN "DELETE FROM TDBADMIN.RESERVATION WHERE BID = %d AND PERS_ID = %d;"
#define _DELETE_RES_BCH_TEIL "DELETE FROM TDBADMIN.RESERVATION WHERE BID = %d AND TEIL = %d;"
#define _DELETE_RES_BCH_DLN_TEIL "DELETE FROM TDBADMIN.RESERVATION WHERE BID = %d AND PERS_ID = %d AND TEIL=%d;"


#define _DELETE_KAPA	"DELETE FROM TDBADMIN.KAPA WHERE KAT_ID = %d AND TDL_ID = %d;"
#define _DELETE_KAPA_KAT "DELETE FROM TDBADMIN.KAPA WHERE KAT_ID = %d;"
#define _DELETE_KAPA_TDL "DELETE FROM TDBADMIN.KAPA WHERE TDL_ID = %d;"

#define _DELETE_ARRKOM	"DELETE FROM TDBADMIN.MP_ARRKOM WHERE ARR_ID = %d AND KOMM_ID = %d;"
#define _DELETE_ARRKOM_ARR "DELETE FROM TDBADMIN.MP_ARRKOM WHERE ARR_ID = %d;"
#define _DELETE_ARRKOM_KOM "DELETE FROM TDBADMIN.MP_ARRKOM WHERE KOMM_ID = %d;"


#define _DELETE_GRA	"DELETE FROM TDBADMIN.GRAPHIK WHERE GRA_ID = %d;"
#define _DELETE_GRAFORM	"DELETE FROM TDBADMIN.GRAFORM WHERE GRA_ID = %d;"
#define _DELETE_REG	"DELETE FROM TDBADMIN.REGIONS WHERE HOST_ID = %d;"
#define _DELETE_PCX	"DELETE FROM TDBADMIN.PCX_FILES WHERE PCX_ID = %d;"



/* oh lord, what shall that be ? */
#define _DELETE_FREE	"DELETE FROM TDBADMIN.FREE_ID WHERE FREE_ID = %d AND TABLE = \'%s\';"
