#
#  Copyright 2002 yafra.org
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# MAKEFILE for your_project
#
# external:


# ---- set RELEASE and VERSION ----------------------------
#
xyVER = 2
xyREL = 99
RELEASE = v$(xyVER)r$(xyREL)

MAKE       = gmake

#
# ---- General make tasks ----------------------------------
#

default: info

all: xy_a xy_b xy_c

xy_a:
	$(MAKE) -f makefile.xy_a version xy_a install RELEASE="$(RELEASE)"

xy_lib:
	$(MAKE) -f makefile.xy_lib version lib install.lib RELEASE="$(RELEASE)"

##
## DON'T TOUCH SYSTEM LIBRARIES and GLOBAL LIBRARIES
## GET THEM IN RELEASED FORM !!
##

#
# Call this to clean the objects and binaries
#
clean:
	$(MAKE) -f makefile.xy_a clean
	$(MAKE) -f makefile.xy_b clean

#
# info of make commands
#
info index:
	@echo ===============
	@echo make commands
	@echo ===============
	@echo "xy_a:           make xy_a"
	@echo ""
	@echo "prepare_release:	prepares everything for relase"
	@echo "build_release:   make the release of the current target" 
