#!/usr/bin/bash
echo
echo PISO Date and Time function tests
echo
echo Test current century
echo
$YAFRAEXE/psdatetime -d "28.07.97 11:33" -t 00:11:33
$YAFRAEXE/psdatetime -d "17.02.97 12:13" -t 01:10:15
$YAFRAEXE/psdatetime -d "17.07.97" -t 01:10:15
echo
echo "Test absolut century Y2000"
echo
$YAFRAEXE/psdatetime -d "17.02.2001 12:13" -t 11:10:15
echo
echo "Test 1901 (which should be an error)"
echo
$YAFRAEXE/psdatetime -d "17.02.1901 12:13" -t 11:11:15
