set pagesize 24;
set pause off;
spool aaa
SELECT * FROM TDBADMIN.LAND WHERE ROWNUM < 4 ORDER BY ROWNUM
/
SELECT * FROM TDBADMIN.SPRACHEN ORDER BY ROWNUM
/
SELECT * FROM TDBADMIN.SAISON ORDER BY ROWNUM
/
SELECT * FROM TDBADMIN.PERSONEN WHERE ROWNUM < 4 ORDER BY ROWNUM
/
SELECT * FROM TDBADMIN.STATUS_WERTE WHERE ROWNUM < 4 ORDER BY ROWNUM
/
SELECT * FROM TDBADMIN.REISENDER_TYP WHERE ROWNUM<4 ORDER BY ROWNUM
/
SELECT * FROM TDBADMIN.PERSADR WHERE ROWNUM < 4 ORDER BY ROWNUM
/
SELECT * FROM TDBADMIN.KONTINGENT WHERE ROWNUM < 4 ORDER BY ROWNUM
/
SELECT * FROM TDBADMIN.KOMMISSION WHERE ROWNUM < 4 ORDER BY ROWNUM
/
SELECT * FROM TDBADMIN.PREIS WHERE ROWNUM < 4 ORDER BY ROWNUM
/
SELECT * FROM TDBADMIN.KAPA WHERE ROWNUM < 4 ORDER BY ROWNUM
/
SELECT * FROM TDBADMIN.STA_VIEW WHERE ROWNUM < 4 ORDER BY ROWNUM
/
SELECT * FROM TDBADMIN.LAND_VIEW WHERE ROWNUM < 4 ORDER BY ROWNUM
/
SELECT * FROM TDBADMIN.KUN_VIEW WHERE ROWNUM < 4 ORDER BY ROWNUM
/
SELECT * FROM TDBADMIN.MPV_KAPA WHERE ROWNUM < 4 ORDER BY ROWNUM
/
SELECT * FROM TDBADMIN.MPV_DLNADR WHERE ROWNUM < 4 ORDER BY ROWNUM
/
SELECT * FROM TDBADMIN.MPV_KUNADR WHERE ROWNUM < 4 ORDER BY ROWNUM
/
spool off;
