//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace tdb.DS {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("ActV")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class ActV : global::System.Data.DataSet {
        
        private tdbv_actDataTable tabletdbv_act;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ActV() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected ActV(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["tdbv_act"] != null)) {
                    base.Tables.Add(new tdbv_actDataTable(ds.Tables["tdbv_act"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public tdbv_actDataTable tdbv_act {
            get {
                return this.tabletdbv_act;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            ActV cln = ((ActV)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["tdbv_act"] != null)) {
                    base.Tables.Add(new tdbv_actDataTable(ds.Tables["tdbv_act"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tabletdbv_act = ((tdbv_actDataTable)(base.Tables["tdbv_act"]));
            if ((initTable == true)) {
                if ((this.tabletdbv_act != null)) {
                    this.tabletdbv_act.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "ActV";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/ActV.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabletdbv_act = new tdbv_actDataTable();
            base.Tables.Add(this.tabletdbv_act);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializetdbv_act() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            ActV ds = new ActV();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void tdbv_actRowChangeEventHandler(object sender, tdbv_actRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class tdbv_actDataTable : global::System.Data.TypedTableBase<tdbv_actRow> {
            
            private global::System.Data.DataColumn columnACT_ID;
            
            private global::System.Data.DataColumn columnBEZ_ID;
            
            private global::System.Data.DataColumn columnBEZ;
            
            private global::System.Data.DataColumn columnS_ID;
            
            private global::System.Data.DataColumn columnTEXTID;
            
            private global::System.Data.DataColumn columnAFLAG;
            
            private global::System.Data.DataColumn columnAFLAGID;
            
            private global::System.Data.DataColumn columnBFLAG;
            
            private global::System.Data.DataColumn columnBFLAGID;
            
            private global::System.Data.DataColumn columnB2FLAG;
            
            private global::System.Data.DataColumn columnB2FLAGID;
            
            private global::System.Data.DataColumn columnMFLAG;
            
            private global::System.Data.DataColumn columnMFLAGID;
            
            private global::System.Data.DataColumn columnACTTYPE;
            
            private global::System.Data.DataColumn columnACTTYPEID;
            
            private global::System.Data.DataColumn columnACTTPROC;
            
            private global::System.Data.DataColumn columnFILE_ID;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tdbv_actDataTable() {
                this.TableName = "tdbv_act";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal tdbv_actDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected tdbv_actDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ACT_IDColumn {
                get {
                    return this.columnACT_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BEZ_IDColumn {
                get {
                    return this.columnBEZ_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BEZColumn {
                get {
                    return this.columnBEZ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn S_IDColumn {
                get {
                    return this.columnS_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TEXTIDColumn {
                get {
                    return this.columnTEXTID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn AFLAGColumn {
                get {
                    return this.columnAFLAG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn AFLAGIDColumn {
                get {
                    return this.columnAFLAGID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BFLAGColumn {
                get {
                    return this.columnBFLAG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BFLAGIDColumn {
                get {
                    return this.columnBFLAGID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn B2FLAGColumn {
                get {
                    return this.columnB2FLAG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn B2FLAGIDColumn {
                get {
                    return this.columnB2FLAGID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MFLAGColumn {
                get {
                    return this.columnMFLAG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MFLAGIDColumn {
                get {
                    return this.columnMFLAGID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ACTTYPEColumn {
                get {
                    return this.columnACTTYPE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ACTTYPEIDColumn {
                get {
                    return this.columnACTTYPEID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ACTTPROCColumn {
                get {
                    return this.columnACTTPROC;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FILE_IDColumn {
                get {
                    return this.columnFILE_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tdbv_actRow this[int index] {
                get {
                    return ((tdbv_actRow)(this.Rows[index]));
                }
            }
            
            public event tdbv_actRowChangeEventHandler tdbv_actRowChanging;
            
            public event tdbv_actRowChangeEventHandler tdbv_actRowChanged;
            
            public event tdbv_actRowChangeEventHandler tdbv_actRowDeleting;
            
            public event tdbv_actRowChangeEventHandler tdbv_actRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Addtdbv_actRow(tdbv_actRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tdbv_actRow Addtdbv_actRow(
                        int ACT_ID, 
                        int BEZ_ID, 
                        string BEZ, 
                        int S_ID, 
                        int TEXTID, 
                        string AFLAG, 
                        int AFLAGID, 
                        string BFLAG, 
                        int BFLAGID, 
                        string B2FLAG, 
                        int B2FLAGID, 
                        string MFLAG, 
                        int MFLAGID, 
                        string ACTTYPE, 
                        int ACTTYPEID, 
                        string ACTTPROC, 
                        int FILE_ID) {
                tdbv_actRow rowtdbv_actRow = ((tdbv_actRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        ACT_ID,
                        BEZ_ID,
                        BEZ,
                        S_ID,
                        TEXTID,
                        AFLAG,
                        AFLAGID,
                        BFLAG,
                        BFLAGID,
                        B2FLAG,
                        B2FLAGID,
                        MFLAG,
                        MFLAGID,
                        ACTTYPE,
                        ACTTYPEID,
                        ACTTPROC,
                        FILE_ID};
                rowtdbv_actRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowtdbv_actRow);
                return rowtdbv_actRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                tdbv_actDataTable cln = ((tdbv_actDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new tdbv_actDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnACT_ID = base.Columns["ACT_ID"];
                this.columnBEZ_ID = base.Columns["BEZ_ID"];
                this.columnBEZ = base.Columns["BEZ"];
                this.columnS_ID = base.Columns["S_ID"];
                this.columnTEXTID = base.Columns["TEXTID"];
                this.columnAFLAG = base.Columns["AFLAG"];
                this.columnAFLAGID = base.Columns["AFLAGID"];
                this.columnBFLAG = base.Columns["BFLAG"];
                this.columnBFLAGID = base.Columns["BFLAGID"];
                this.columnB2FLAG = base.Columns["B2FLAG"];
                this.columnB2FLAGID = base.Columns["B2FLAGID"];
                this.columnMFLAG = base.Columns["MFLAG"];
                this.columnMFLAGID = base.Columns["MFLAGID"];
                this.columnACTTYPE = base.Columns["ACTTYPE"];
                this.columnACTTYPEID = base.Columns["ACTTYPEID"];
                this.columnACTTPROC = base.Columns["ACTTPROC"];
                this.columnFILE_ID = base.Columns["FILE_ID"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnACT_ID = new global::System.Data.DataColumn("ACT_ID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnACT_ID);
                this.columnBEZ_ID = new global::System.Data.DataColumn("BEZ_ID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBEZ_ID);
                this.columnBEZ = new global::System.Data.DataColumn("BEZ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBEZ);
                this.columnS_ID = new global::System.Data.DataColumn("S_ID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnS_ID);
                this.columnTEXTID = new global::System.Data.DataColumn("TEXTID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTEXTID);
                this.columnAFLAG = new global::System.Data.DataColumn("AFLAG", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAFLAG);
                this.columnAFLAGID = new global::System.Data.DataColumn("AFLAGID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAFLAGID);
                this.columnBFLAG = new global::System.Data.DataColumn("BFLAG", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBFLAG);
                this.columnBFLAGID = new global::System.Data.DataColumn("BFLAGID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBFLAGID);
                this.columnB2FLAG = new global::System.Data.DataColumn("B2FLAG", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnB2FLAG);
                this.columnB2FLAGID = new global::System.Data.DataColumn("B2FLAGID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnB2FLAGID);
                this.columnMFLAG = new global::System.Data.DataColumn("MFLAG", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMFLAG);
                this.columnMFLAGID = new global::System.Data.DataColumn("MFLAGID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMFLAGID);
                this.columnACTTYPE = new global::System.Data.DataColumn("ACTTYPE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnACTTYPE);
                this.columnACTTYPEID = new global::System.Data.DataColumn("ACTTYPEID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnACTTYPEID);
                this.columnACTTPROC = new global::System.Data.DataColumn("ACTTPROC", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnACTTPROC);
                this.columnFILE_ID = new global::System.Data.DataColumn("FILE_ID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFILE_ID);
                this.columnACT_ID.AllowDBNull = false;
                this.columnBEZ_ID.AllowDBNull = false;
                this.columnBEZ.AllowDBNull = false;
                this.columnS_ID.AllowDBNull = false;
                this.columnAFLAG.AllowDBNull = false;
                this.columnBFLAG.AllowDBNull = false;
                this.columnB2FLAG.AllowDBNull = false;
                this.columnMFLAG.AllowDBNull = false;
                this.columnACTTYPE.AllowDBNull = false;
                this.columnACTTYPEID.AllowDBNull = false;
                this.columnACTTPROC.AllowDBNull = false;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tdbv_actRow Newtdbv_actRow() {
                return ((tdbv_actRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new tdbv_actRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(tdbv_actRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.tdbv_actRowChanged != null)) {
                    this.tdbv_actRowChanged(this, new tdbv_actRowChangeEvent(((tdbv_actRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.tdbv_actRowChanging != null)) {
                    this.tdbv_actRowChanging(this, new tdbv_actRowChangeEvent(((tdbv_actRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.tdbv_actRowDeleted != null)) {
                    this.tdbv_actRowDeleted(this, new tdbv_actRowChangeEvent(((tdbv_actRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.tdbv_actRowDeleting != null)) {
                    this.tdbv_actRowDeleting(this, new tdbv_actRowChangeEvent(((tdbv_actRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Removetdbv_actRow(tdbv_actRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                ActV ds = new ActV();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "tdbv_actDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class tdbv_actRow : global::System.Data.DataRow {
            
            private tdbv_actDataTable tabletdbv_act;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal tdbv_actRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabletdbv_act = ((tdbv_actDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int ACT_ID {
                get {
                    return ((int)(this[this.tabletdbv_act.ACT_IDColumn]));
                }
                set {
                    this[this.tabletdbv_act.ACT_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int BEZ_ID {
                get {
                    return ((int)(this[this.tabletdbv_act.BEZ_IDColumn]));
                }
                set {
                    this[this.tabletdbv_act.BEZ_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string BEZ {
                get {
                    return ((string)(this[this.tabletdbv_act.BEZColumn]));
                }
                set {
                    this[this.tabletdbv_act.BEZColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int S_ID {
                get {
                    return ((int)(this[this.tabletdbv_act.S_IDColumn]));
                }
                set {
                    this[this.tabletdbv_act.S_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int TEXTID {
                get {
                    try {
                        return ((int)(this[this.tabletdbv_act.TEXTIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TEXTID\' in table \'tdbv_act\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletdbv_act.TEXTIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string AFLAG {
                get {
                    return ((string)(this[this.tabletdbv_act.AFLAGColumn]));
                }
                set {
                    this[this.tabletdbv_act.AFLAGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int AFLAGID {
                get {
                    try {
                        return ((int)(this[this.tabletdbv_act.AFLAGIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AFLAGID\' in table \'tdbv_act\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletdbv_act.AFLAGIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string BFLAG {
                get {
                    return ((string)(this[this.tabletdbv_act.BFLAGColumn]));
                }
                set {
                    this[this.tabletdbv_act.BFLAGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int BFLAGID {
                get {
                    try {
                        return ((int)(this[this.tabletdbv_act.BFLAGIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BFLAGID\' in table \'tdbv_act\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletdbv_act.BFLAGIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string B2FLAG {
                get {
                    return ((string)(this[this.tabletdbv_act.B2FLAGColumn]));
                }
                set {
                    this[this.tabletdbv_act.B2FLAGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int B2FLAGID {
                get {
                    try {
                        return ((int)(this[this.tabletdbv_act.B2FLAGIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'B2FLAGID\' in table \'tdbv_act\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletdbv_act.B2FLAGIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string MFLAG {
                get {
                    return ((string)(this[this.tabletdbv_act.MFLAGColumn]));
                }
                set {
                    this[this.tabletdbv_act.MFLAGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int MFLAGID {
                get {
                    try {
                        return ((int)(this[this.tabletdbv_act.MFLAGIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MFLAGID\' in table \'tdbv_act\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletdbv_act.MFLAGIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ACTTYPE {
                get {
                    return ((string)(this[this.tabletdbv_act.ACTTYPEColumn]));
                }
                set {
                    this[this.tabletdbv_act.ACTTYPEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int ACTTYPEID {
                get {
                    return ((int)(this[this.tabletdbv_act.ACTTYPEIDColumn]));
                }
                set {
                    this[this.tabletdbv_act.ACTTYPEIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ACTTPROC {
                get {
                    return ((string)(this[this.tabletdbv_act.ACTTPROCColumn]));
                }
                set {
                    this[this.tabletdbv_act.ACTTPROCColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int FILE_ID {
                get {
                    try {
                        return ((int)(this[this.tabletdbv_act.FILE_IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FILE_ID\' in table \'tdbv_act\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletdbv_act.FILE_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTEXTIDNull() {
                return this.IsNull(this.tabletdbv_act.TEXTIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTEXTIDNull() {
                this[this.tabletdbv_act.TEXTIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsAFLAGIDNull() {
                return this.IsNull(this.tabletdbv_act.AFLAGIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetAFLAGIDNull() {
                this[this.tabletdbv_act.AFLAGIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBFLAGIDNull() {
                return this.IsNull(this.tabletdbv_act.BFLAGIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBFLAGIDNull() {
                this[this.tabletdbv_act.BFLAGIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsB2FLAGIDNull() {
                return this.IsNull(this.tabletdbv_act.B2FLAGIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetB2FLAGIDNull() {
                this[this.tabletdbv_act.B2FLAGIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMFLAGIDNull() {
                return this.IsNull(this.tabletdbv_act.MFLAGIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMFLAGIDNull() {
                this[this.tabletdbv_act.MFLAGIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFILE_IDNull() {
                return this.IsNull(this.tabletdbv_act.FILE_IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFILE_IDNull() {
                this[this.tabletdbv_act.FILE_IDColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class tdbv_actRowChangeEvent : global::System.EventArgs {
            
            private tdbv_actRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tdbv_actRowChangeEvent(tdbv_actRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tdbv_actRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591