/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget *create_tdb_main(void);
GtkWidget *create_tdb_login(void);
GtkWidget *create_tdb_langwin(void);
GtkWidget *create_tdb_about(void);
GtkWidget *create_tdb_exit(void);
GtkWidget *create_tdb_select(void);
GtkWidget *create_tdb_opts(void);
