<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="PersonService" targetNamespace="http://pojo.jee.server.yafra.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://pojo.jee.server.yafra.org/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
<import namespace="http://pojo.jee.server.yafra.org/" schemaLocation="person_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="getPersons">
    <wsdl:part name="parameters" element="tns:getPersons">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getPersonsResponse">
    <wsdl:part name="parameters" element="tns:getPersonsResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="insertPerson">
    <wsdl:part name="parameters" element="tns:insertPerson">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="insertPersonResponse">
    <wsdl:part name="parameters" element="tns:insertPersonResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="PersonSEI">
    <wsdl:operation name="getPersons">
      <wsdl:input name="getPersons" message="tns:getPersons">
    </wsdl:input>
      <wsdl:output name="getPersonsResponse" message="tns:getPersonsResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="insertPerson">
      <wsdl:input name="insertPerson" message="tns:insertPerson">
    </wsdl:input>
      <wsdl:output name="insertPersonResponse" message="tns:insertPersonResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="PersonServiceSoapBinding" type="tns:PersonSEI">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getPersons">
      <soap:operation soapAction="urn:GetPersons" style="document"/>
      <wsdl:input name="getPersons">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getPersonsResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="insertPerson">
      <soap:operation soapAction="urn:InsertPerson" style="document"/>
      <wsdl:input name="insertPerson">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="insertPersonResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PersonService">
    <wsdl:port name="PersonSEI" binding="tns:PersonServiceSoapBinding">
      <soap:address location="http://localhost:8080/org.yafra.server.jee/services/PersonSEI"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
