package org.yafra.orm.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.yafra.orm.Person;

/**
 * Class _PersonLog was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PersonLog extends CayenneDataObject {

    public static final String EVENT_AUDIT_PROPERTY = "eventAudit";
    public static final String EVENT_AUDIT_REVIEWER_PROPERTY = "eventAuditReviewer";
    public static final String EVENT_CREATOR_PROPERTY = "eventCreator";
    public static final String EVENT_DATE_PROPERTY = "eventDate";
    public static final String EVENT_DESCRIPTION_PROPERTY = "eventDescription";
    public static final String TO_PERSON_PROPERTY = "toPerson";

    public static final String PK_PERSON_LOG_PK_COLUMN = "pkPersonLog";

    public void setEventAudit(String eventAudit) {
        writeProperty("eventAudit", eventAudit);
    }
    public String getEventAudit() {
        return (String)readProperty("eventAudit");
    }

    public void setEventAuditReviewer(String eventAuditReviewer) {
        writeProperty("eventAuditReviewer", eventAuditReviewer);
    }
    public String getEventAuditReviewer() {
        return (String)readProperty("eventAuditReviewer");
    }

    public void setEventCreator(String eventCreator) {
        writeProperty("eventCreator", eventCreator);
    }
    public String getEventCreator() {
        return (String)readProperty("eventCreator");
    }

    public void setEventDate(Date eventDate) {
        writeProperty("eventDate", eventDate);
    }
    public Date getEventDate() {
        return (Date)readProperty("eventDate");
    }

    public void setEventDescription(String eventDescription) {
        writeProperty("eventDescription", eventDescription);
    }
    public String getEventDescription() {
        return (String)readProperty("eventDescription");
    }

    public void setToPerson(Person toPerson) {
        setToOneTarget("toPerson", toPerson, true);
    }

    public Person getToPerson() {
        return (Person)readProperty("toPerson");
    }


}
