// ===============================================================================
// Microsoft Data Access Application Block for .NET 3.0
//
// Oldedb.cs
//
// This file contains the implementations of the AdoHelper supporting OleDb.
//
// For more information see the Documentation. 
// ===============================================================================
// Release history
// VERSION	DESCRIPTION
//   2.0	Added support for FillDataset, UpdateDataset and "Param" helper methods
//   3.0	New abstract class supporting the same methods using ADO.NET interfaces
//
// ===============================================================================
// Copyright (C) 2000-2001 Microsoft Corporation
// All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR
// FITNESS FOR A PARTICULAR PURPOSE.
// ==============================================================================

using System;
using System.Collections;
using System.Data;
using System.Data.OleDb;
using System.Text.RegularExpressions;
using System.Xml;
using System.IO;

namespace org.swyn.foundation.db
{
	/// <summary>
	/// The OleDb class is intended to encapsulate high performance, scalable best practices for 
	/// common uses of the OleDb ADO.NET provider.  It is created using the abstract factory in AdoHelper
	/// </summary>
	public class OleDb : AdoHelper
	{
		/// <summary>
		/// Create an OleDb Helper.  Needs to be a default constructor so that the Factory can create it
		/// </summary>
		public OleDb()
		{
		}

		#region Overrides
		/// <summary>
		/// Returns an array of OleDbParameters of the specified size
		/// </summary>
		/// <param name="size">size of the array</param>
		/// <returns>The array of OdbcParameters</returns>
		protected override IDataParameter[] GetDataParameters(int size)
		{
			return new OleDbParameter[size];
		}

		/// <summary>
		/// Returns an OleDbConnection object for the given connection string
		/// </summary>
		/// <param name="connectionString">The connection string to be used to create the connection</param>
		/// <returns>An OleDbConnection object</returns>
		public override IDbConnection GetConnection( string connectionString )
		{
			return new OleDbConnection( connectionString );
		}

		/// <summary>
		/// Returns an OleDbDataAdapter object
		/// </summary>
		/// <returns>The OleDbDataAdapter</returns>
		public override IDbDataAdapter GetDataAdapter()
		{
			return new OleDbDataAdapter(); 
		}

		/// <summary>
		/// Calls the CommandBuilder.DeriveParameters method for the specified provider, doing any setup and cleanup necessary
		/// </summary>
		/// <param name="cmd">The IDbCommand referencing the stored procedure from which the parameter information is to be derived. The derived parameters are added to the Parameters collection of the IDbCommand. </param>
		public override void DeriveParameters( IDbCommand cmd )
		{
			bool mustCloseConnection = false;

			if( !( cmd is OleDbCommand ) )
				throw new ArgumentException( "The command provided is not a OleDbCommand instance.", "cmd" );
	
			if (cmd.Connection.State != ConnectionState.Open) 
			{
				cmd.Connection.Open();
				mustCloseConnection = true;
			}
			
			OleDbCommandBuilder.DeriveParameters( (OleDbCommand)cmd );

			if (mustCloseConnection)
			{
				cmd.Connection.Close();
			}
		}

		/// <summary>
		/// Returns an OleDbParameter object
		/// </summary>
		/// <returns>The OleDbParameter object</returns>
		public override IDataParameter GetParameter()
		{
			return new OleDbParameter(); 
		}

		/// <summary>
		/// This cleans up the parameter syntax for an OleDb call.  This was split out from PrepareCommand so that it could be called independently.
		/// </summary>
		/// <param name="command">An IDbCommand object containing the CommandText to clean.</param>
		public override void CleanParameterSyntax(IDbCommand command)
		{
		}

		/// <summary>
		/// Execute an IDbCommand (that returns a resultset) against the provided IDbConnection. 
		/// </summary>
		/// <example>
		/// <code>
		/// XmlReader r = helper.ExecuteXmlReader(command);
		/// </code></example>
		/// <param name="command">The IDbCommand to execute</param>
		/// <returns>An XmlReader containing the resultset generated by the command</returns>
		public override XmlReader ExecuteXmlReader(IDbCommand command)
		{
			bool mustCloseConnection = false;

			if (command.Connection.State != ConnectionState.Open) 
			{
				command.Connection.Open();
				mustCloseConnection = true;
			}

			CleanParameterSyntax(command);

			OleDbDataAdapter da = new OleDbDataAdapter((OleDbCommand)command);
			DataSet ds = new DataSet();

			da.MissingSchemaAction = MissingSchemaAction.AddWithKey;
			da.Fill(ds);

			StringReader stream = new StringReader(ds.GetXml());
			if (mustCloseConnection)
			{
				command.Connection.Close();
			}

			return new XmlTextReader(stream);
		}

		/// <summary>
		/// Provider specific code to set up the updating/ed event handlers used by UpdateDataset
		/// </summary>
		/// <param name="dataAdapter">DataAdapter to attach the event handlers to</param>
		/// <param name="rowUpdatingHandler">The handler to be called when a row is updating</param>
		/// <param name="rowUpdatedHandler">The handler to be called when a row is updated</param>
		protected override void AddUpdateEventHandlers(IDbDataAdapter dataAdapter, RowUpdatingHandler rowUpdatingHandler, RowUpdatedHandler rowUpdatedHandler)
		{
			if (rowUpdatingHandler != null)
			{
				this.m_rowUpdating = rowUpdatingHandler;
				((OleDbDataAdapter)dataAdapter).RowUpdating += new OleDbRowUpdatingEventHandler(RowUpdating);
			}

			if (rowUpdatedHandler != null)
			{
				this.m_rowUpdated = rowUpdatedHandler;
				((OleDbDataAdapter)dataAdapter).RowUpdated +=  new OleDbRowUpdatedEventHandler(RowUpdated);
			}
		}

		/// <summary>
		/// Handles the RowUpdating event
		/// </summary>
		/// <param name="obj">The object that published the event</param>
		/// <param name="e">The OleDbRowUpdatingEventArgs</param>
		protected void RowUpdating(object obj, OleDbRowUpdatingEventArgs e)
		{
			base.RowUpdating(obj, e);
		}

		/// <summary>
		/// Handles the RowUpdated event
		/// </summary>
		/// <param name="obj">The object that published the event</param>
		/// <param name="e">The OleDbRowUpdatedEventArgs</param>
		protected void RowUpdated(object obj, OleDbRowUpdatedEventArgs e)
		{
			base.RowUpdated(obj, e);
		}
		
		/// <summary>
		/// Handle any provider-specific issues with BLOBs here by "washing" the IDataParameter and returning a new one that is set up appropriately for the provider.
		/// </summary>
		/// <param name="connection">The IDbConnection to use in cleansing the parameter</param>
		/// <param name="p">The parameter before cleansing</param>
		/// <returns>The parameter after it's been cleansed.</returns>
		protected override IDataParameter GetBlobParameter(IDbConnection connection, IDataParameter p)
		{
			// nothing special needed for OleDb...as far as we know now
			return p;
		}
		#endregion
	}
}