insert into label values (180, 0, 0, 0, 25, 'travelDB - graphic                     ');
insert into label values (180, 0, 1, 0, 25, 'Graphic                                  ');
insert into label values (180, 0, 2, 0, 25, 'File:                                    ');
insert into label values (180, 0, 3, 0, 25, 'Dialogwindow                             ');
insert into label values (180, 0, 4, 0, 25, 'End                                      ');
insert into label values (180, 0, 5, 0, 25, 'Bookingwindow                            ');
insert into label values (180, 0, 6, 0, 25, 'Service location                         ');
insert into label values (180, 0, 7, 0, 25, 'Select file                              ');
insert into label values (180, 0, 8, 0, 25, 'Palette                                  ');
insert into label values (180, 0, 9, 0, 25, ' Region:                                 ');
insert into label values (180, 0, 10, 0, 25, 'Graphic booking                          ');
insert into label values (180, 1, 0, 0, 25, 'Font                                     ');
insert into label values (180, 1, 1, 0, 25, 'colour                                   ');
insert into label values (180, 1, 2, 0, 25, 'Breadth                                  ');
insert into label values (180, 1, 3, 0, 25, 'Pattern                                  ');
insert into label values (180, 1, 4, 0, 25, 'Stile                                    ');
insert into label values (180, 1, 5, 0, 25, 'Snap                                     ');
insert into label values (180, 2, 0, 0, 25, 'File                                     ');
insert into label values (180, 2, 1, 0, 25, 'Import ...                               ');
insert into label values (180, 2, 2, 0, 25, 'Export                                   ');
insert into label values (180, 2, 3, 0, 25, 'Export as  ...                           ');
insert into label values (180, 2, 4, 0, 25, 'Graphic delete                           ');
insert into label values (180, 2, 5, 0, 25, 'Cancel                                   ');
insert into label values (180, 2, 6, 0, 25, 'End                                      ');
insert into label values (180, 3, 0, 0, 25, 'Create                                   ');
insert into label values (180, 3, 1, 0, 25, 'Text                                     ');
insert into label values (180, 3, 2, 0, 25, 'Point                                    ');
insert into label values (180, 3, 3, 0, 25, 'Line                                     ');
insert into label values (180, 3, 4, 0, 25, 'Rectangle                                ');
insert into label values (180, 3, 5, 0, 25, 'Circle                                   ');
insert into label values (180, 3, 6, 0, 25, 'Kreisbogen                               ');
insert into label values (180, 3, 7, 0, 25, 'Ellipse                                  ');
insert into label values (180, 3, 8, 0, 25, 'schraffiertes Rechteck                   ');
insert into label values (180, 3, 9, 0, 25, 'schraffierter Kreis                      ');
insert into label values (180, 3, 10, 0, 25, 'schraffierter Kreisbogen                 ');
insert into label values (180, 3, 11, 0, 25, 'schraffierte Ellipse                     ');
insert into label values (180, 4, 0, 0, 25, 'Modify                                   ');
insert into label values (180, 4, 1, 0, 25, 'Element move                             ');
insert into label values (180, 4, 2, 0, 25, 'Element copy                             ');
insert into label values (180, 4, 3, 0, 25, 'Element delete                           ');
insert into label values (180, 5, 0, 0, 25, 'Settings                                 ');
insert into label values (180, 5, 1, 0, 25, 'Grid                                     ');
insert into label values (180, 5, 2, 0, 25, 'Pickbox                                  ');
insert into label values (180, 5, 3, 0, 25, 'Punktradius                              ');
insert into label values (180, 5, 4, 0, 25, 'Desktop                                  ');
insert into label values (180, 6, 0, 0, 25, 'Zoom                                     ');
insert into label values (180, 6, 1, 0, 25, 'Start                                    ');
insert into label values (180, 6, 2, 0, 25, 'new                                      ');
insert into label values (180, 6, 3, 0, 25, 'Last zoom                                ');
insert into label values (180, 6, 4, 0, 25, 'Next zoom                                ');
insert into label values (180, 6, 5, 0, 25, 'resize                                   ');
insert into label values (180, 6, 6, 0, 25, '..... dbg print                          ');
insert into label values (180, 7, 0, 0, 25, 'Help                                     ');
insert into label values (180, 7, 1, 0, 25, 'Help about graphic                       ');
insert into label values (180, 7, 2, 0, 25, 'Help about mainmenu                      ');
insert into label values (180, 7, 3, 0, 25, 'Help about menu  ...                     ');
insert into label values (180, 7, 4, 0, 25, 'Help overview                            ');
insert into label values (180, 8, 0, 0, 25, 'ok                                       ');
insert into label values (180, 8, 1, 0, 25, 'no                                       ');
insert into label values (180, 8, 2, 0, 25, 'Delete entire graphic  ?                 ');
insert into label values (180, 8, 3, 0, 25, 'Exit without save graphic ?              ');
insert into label values (180, 8, 4, 0, 25, 'Send booking                             ');
insert into label values (180, 9, 0, 0, 25, ' 1. Point of the line                    ');
insert into label values (180, 9, 1, 0, 25, ' 2. Point of the line                    ');
insert into label values (180, 9, 2, 0, 25, 'Enter point                              ');
insert into label values (180, 9, 3, 0, 25, 'Upper left corner (rectangle)            ');
insert into label values (180, 9, 4, 0, 25, 'Lower right corner (rectangle)           ');
insert into label values (180, 9, 5, 0, 25, ' 1. periferal point (Circlsegt)          ');
insert into label values (180, 9, 6, 0, 25, ' 2. periferal point (Circlsegt)          ');
insert into label values (180, 9, 7, 0, 25, ' 3. periferal point (Circlsegt)          ');
insert into label values (180, 9, 8, 0, 25, 'Enter circle center                      ');
insert into label values (180, 9, 9, 0, 25, 'Enter periferal point                    ');
insert into label values (180, 9, 10, 0, 25, 'linke obere Ecke (Pickbox)               ');
insert into label values (180, 9, 11, 0, 25, 'rechte untere Ecke (Pickbox)             ');
insert into label values (180, 9, 12, 0, 25, 'Enter text                               ');
insert into label values (180, 9, 13, 0, 25, 'linke untere Ecke (Textanfang)           ');
insert into label values (180, 9, 14, 0, 25, 'Gitterabstand im mm eingeben             ');
insert into label values (180, 9, 15, 0, 25, 'Pickboxgroesse in mm eingeben            ');
insert into label values (180, 9, 16, 0, 25, 'Zeichenblattgroesse (A0-A4)              ');
insert into label values (180, 9, 17, 0, 25, 'Punktradius in mm eingeben               ');
insert into label values (180, 9, 18, 0, 25, 'Element in Pickbox auswaehlen            ');
insert into label values (180, 9, 19, 0, 25, 'Bestimmungsort eingeben                  ');
insert into label values (180, 9, 20, 0, 25, 'Element in Pickbox auswaehlen            ');
insert into label values (180, 9, 21, 0, 25, 'Bestimmungsort der Kopie                 ');
insert into label values (180, 9, 22, 0, 25, 'Element in Pickbox auswaehlen            ');
insert into label values (180, 9, 23, 0, 25, 'linke obere Ecke (Ausschnitt)            ');
insert into label values (180, 9, 24, 0, 25, 'rechte untere Ecke (Ausschnitt)          ');
insert into label values (180, 9, 25, 0, 25, 'Punkt eingeben fuer Textelement          ');
insert into label values (180, 9, 26, 0, 25, 'Punkt eines Elementes auswaehlen         ');
insert into label values (180, 10, 0, 0, 25, 'Ende                                     ');
insert into label values (180, 10, 1, 0, 25, 'Zoom original                            ');
insert into label values (180, 10, 2, 0, 25, 'Zoom neu                                 ');
insert into label values (180, 10, 3, 0, 25, 'Zoom-                                    ');
insert into label values (180, 10, 4, 0, 25, 'Zoom+                                    ');
insert into label values (180, 10, 5, 0, 25, 'Help                                     ');
insert into label values (181, 1, 0, 0, 25, 'Language...                              ');
insert into label values (181, 1, 1, 0, 25, 'Language Label                           ');
insert into label values (181, 1, 2, 0, 25, 'Dialoglanguage?                          ');
insert into label values (181, 1, 3, 0, 25, 'Systemlabel (NLS)                        ');
insert into label values (181, 1, 4, 0, 25, 'Output language ?                         ');
insert into label values (181, 1, 5, 0, 25, 'GUI language ?                            ');
insert into label values (181, 2, 0, 0, 25, 'Statevalues...                           ');
insert into label values (181, 2, 1, 0, 25, 'State Label                              ');
insert into label values (181, 2, 2, 0, 25, 'Shortname                                ');
insert into label values (181, 2, 3, 0, 25, 'State value                              ');
insert into label values (181, 2, 4, 0, 25, 'Conditions                               ');
insert into label values (181, 2, 5, 0, 25, 'Type of state                            ');
insert into label values (181, 3, 0, 0, 25, 'Labels ...                               ');
insert into label values (181, 3, 1, 0, 25, 'Language                                 ');
insert into label values (181, 3, 2, 0, 25, 'Type of Label                            ');
insert into label values (181, 3, 3, 0, 25, 'Label                                    ');
insert into label values (181, 3, 4, 0, 25, 'new Label                                ');
insert into label values (181, 4, 0, 0, 25, 'Text ...                                 ');
insert into label values (181, 4, 1, 0, 25, 'Language                                 ');
insert into label values (181, 4, 2, 0, 25, 'Text                                     ');
insert into label values (181, 4, 3, 0, 25, 'to language                              ');
insert into label values (181, 4, 4, 0, 25, 'to text                                  ');
insert into label values (181, 6, 0, 0, 25, 'Help ...                                 ');
insert into label values (181, 6, 1, 0, 25, 'Type of help                             ');
insert into label values (181, 6, 2, 0, 25, 'Help Number                              ');
insert into label values (181, 6, 3, 0, 25, 'Language                                 ');
insert into label values (181, 6, 4, 0, 25, 'Help text                                ');
insert into label values (181, 7, 0, 0, 25, 'Messages...                              ');
insert into label values (181, 7, 1, 0, 25, 'Messagetype                              ');
insert into label values (181, 7, 2, 0, 25, 'Message number                           ');
insert into label values (181, 7, 3, 0, 25, 'Language                                 ');
insert into label values (181, 7, 4, 0, 25, 'Text                                     ');
insert into label values (181, 8, 0, 0, 25, 'Labels...                                ');
insert into label values (181, 8, 1, 0, 25, 'Label Descriptin                         ');
insert into label values (181, 8, 2, 0, 25, 'Label language                           ');
insert into label values (181, 8, 3, 0, 25, 'Label Programnumber                      ');
insert into label values (181, 8, 4, 0, 25, 'Label type                               ');
insert into label values (181, 8, 5, 0, 25, 'Label level 1                            ');
insert into label values (181, 8, 6, 0, 25, 'Label level 2                            ');
insert into label values (181, 9, 0, 0, 25, 'Season ...                               ');
insert into label values (181, 9, 1, 0, 25, 'Season label                             ');
insert into label values (181, 9, 2, 0, 25, 'Code                                     ');
insert into label values (181, 9, 3, 0, 25, 'From - date [dd.mm.yy]                   ');
insert into label values (181, 9, 4, 0, 25, 'To   - date [dd.mm.jy]                   ');
insert into label values (181, 9, 5, 0, 25, 'Description                              ');
insert into label values (181, 10, 0, 0, 25, 'Countries.                               ');
insert into label values (181, 10, 1, 0, 25, 'Land                                     ');
insert into label values (181, 10, 2, 0, 25, 'Capital                                  ');
insert into label values (181, 10, 3, 0, 25, 'Currency                                 ');
insert into label values (181, 10, 4, 0, 25, 'Nationallanguage                         ');
insert into label values (181, 10, 5, 0, 25, 'Shortname                                ');
insert into label values (181, 10, 6, 0, 25, 'Taxes (in %)                             ');
insert into label values (181, 10, 7, 0, 25, 'Description                              ');
insert into label values (181, 10, 8, 0, 25, 'Dateformat                               ');
insert into label values (181, 11, 0, 0, 25, 'Locations                                ');
insert into label values (181, 11, 1, 0, 25, 'Location                                 ');
insert into label values (181, 11, 2, 0, 25, 'Land                                     ');
insert into label values (181, 11, 3, 0, 25, 'Type                                     ');
insert into label values (181, 11, 4, 0, 25, 'Shortname                                ');
insert into label values (181, 11, 5, 0, 25, 'Timezone                                 ');
insert into label values (181, 11, 6, 0, 25, 'X coordinate                             ');
insert into label values (181, 11, 7, 0, 25, 'Y coordinate                             ');
insert into label values (181, 11, 8, 0, 25, 'Description                              ');
insert into label values (181, 12, 0, 0, 25, 'Currency ...                             ');
insert into label values (181, 12, 1, 0, 25, 'Currency                                 ');
insert into label values (181, 12, 2, 0, 25, 'State of currency                        ');
insert into label values (181, 12, 3, 0, 25, 'Shortname                                ');
insert into label values (181, 12, 4, 0, 25, 'Description                              ');
insert into label values (181, 13, 0, 0, 25, 'Exchange ...                             ');
insert into label values (181, 13, 1, 0, 25, 'Country                                  ');
insert into label values (181, 13, 2, 0, 25, 'Currency                                 ');
insert into label values (181, 13, 3, 0, 25, 'Type of exchange                         ');
insert into label values (181, 13, 4, 0, 25, 'Buy                                      ');
insert into label values (181, 13, 5, 0, 25, 'Sell                                     ');
insert into label values (181, 13, 6, 0, 25, 'Date of exchange rate                    ');
insert into label values (181, 15, 0, 0, 25, 'Type of location                         ');
insert into label values (181, 15, 1, 0, 25, 'Type of location label                   ');
insert into label values (181, 15, 2, 0, 25, 'Types of location                        ');
insert into label values (181, 15, 3, 0, 25, 'Upper type of location                   ');
insert into label values (181, 15, 4, 0, 25, 'Description                              ');
insert into label values (181, 16, 0, 0, 25, 'Categories...                            ');
insert into label values (181, 16, 1, 0, 25, 'Category label                           ');
insert into label values (181, 16, 2, 0, 25, 'Type of location                         ');
insert into label values (181, 16, 3, 0, 25, 'upgrade Categorie                        ');
insert into label values (181, 16, 4, 0, 25, 'Graph. attribut                          ');
insert into label values (181, 16, 5, 0, 25, 'Description                              ');
insert into label values (181, 17, 0, 0, 25, 'Location of the service ...              ');
insert into label values (181, 17, 1, 0, 25, 'Label of the service loaction            ');
insert into label values (181, 17, 2, 0, 25, 'Category                                 ');
insert into label values (181, 17, 3, 0, 25, 'Upper type of location                   ');
insert into label values (181, 17, 4, 0, 25, 'Type of location                         ');
insert into label values (181, 17, 5, 0, 25, 'Description                              ');
insert into label values (181, 17, 6, 0, 25, 'Host location                            ');
insert into label values (181, 17, 7, 0, 25, 'Bestplace attribute                      ');
insert into label values (181, 17, 8, 0, 25, 'Code                                     ');
insert into label values (181, 17, 9, 0, 25, 'Capacity of unit                         ');
insert into label values (181, 18, 0, 0, 25, 'Offer types ...                          ');
insert into label values (181, 18, 1, 0, 25, 'Offer type label                         ');
insert into label values (181, 18, 2, 0, 25, 'Description                              ');
insert into label values (181, 19, 0, 0, 25, 'Aktion types...                          ');
insert into label values (181, 19, 1, 0, 25, 'Action type label                        ');
insert into label values (181, 19, 2, 0, 25, 'Process                                  ');
insert into label values (181, 19, 3, 0, 25, 'Description                              ');
insert into label values (181, 19, 4, 0, 25, 'Parameternumber                          ');
insert into label values (181, 19, 5, 0, 25, 'Parametertype                            ');
insert into label values (181, 19, 6, 0, 25, 'Parameter                                ');
insert into label values (181, 19, 7, 0, 25, 'MUST-Parameter ?                         ');
insert into label values (181, 19, 8, 0, 25, 'FLAG-Parameter ?                         ');
insert into label values (181, 19, 9, 0, 25, 'Parameterdescription                     ');
insert into label values (181, 21, 0, 0, 25, 'Aktions ...                              ');
insert into label values (181, 21, 1, 0, 25, 'Action label                             ');
insert into label values (181, 21, 2, 0, 25, 'Output device                            ');
insert into label values (181, 21, 3, 0, 25, 'Description                              ');
insert into label values (181, 21, 4, 0, 25, 'Running state                            ');
insert into label values (181, 21, 5, 0, 25, 'Reservation state at start               ');
insert into label values (181, 21, 6, 0, 25, 'Type of action                           ');
insert into label values (181, 21, 7, 0, 25, 'Reservation state if success             ');
insert into label values (181, 22, 0, 0, 25, 'Action groups ...                        ');
insert into label values (181, 22, 1, 0, 25, 'Master action                            ');
insert into label values (181, 22, 2, 0, 25, 'Action                                   ');
insert into label values (181, 22, 3, 0, 25, 'Order                                    ');
insert into label values (181, 23, 0, 0, 25, 'Offers (and parts of)...                 ');
insert into label values (181, 23, 1, 0, 25, 'Offer label                              ');
insert into label values (181, 23, 2, 0, 25, 'Master offer                             ');
insert into label values (181, 23, 3, 0, 25, 'Order of the offers                      ');
insert into label values (181, 23, 4, 0, 25, 'Location                                 ');
insert into label values (181, 23, 5, 0, 25, 'Actions                                  ');
insert into label values (181, 23, 6, 0, 25, 'Embarking place                          ');
insert into label values (181, 23, 7, 0, 25, 'Type of offers                           ');
insert into label values (181, 23, 8, 0, 25, 'Period [dd.mm.yy]                        ');
insert into label values (181, 23, 9, 0, 25, 'Description                              ');
insert into label values (181, 23, 10, 0, 25, 'From destination                         ');
insert into label values (181, 23, 11, 0, 25, 'To destination                           ');
insert into label values (181, 23, 12, 0, 25, 'Code                                     ');
insert into label values (181, 24, 0, 0, 25, 'Types of client...                       ');
insert into label values (181, 24, 1, 0, 25, 'Type of client label                     ');
insert into label values (181, 24, 2, 0, 25, 'Description                              ');
insert into label values (181, 24, 3, 0, 25, 'Code                                     ');
insert into label values (181, 25, 0, 0, 25, 'Clients...                               ');
insert into label values (181, 25, 1, 0, 25, 'Client number                            ');
insert into label values (181, 25, 2, 0, 25, 'Name of client                           ');
insert into label values (181, 25, 3, 0, 25, 'Village                                  ');
insert into label values (181, 25, 4, 0, 25, 'Type of client                           ');
insert into label values (181, 25, 5, 0, 25, 'Country                                  ');
insert into label values (181, 25, 6, 0, 25, 'Accounting currency                      ');
insert into label values (181, 25, 7, 0, 25, 'Language                                 ');
insert into label values (181, 25, 8, 0, 25, 'Telephon-number                          ');
insert into label values (181, 25, 9, 0, 25, 'Fax-number                               ');
insert into label values (181, 25, 10, 0, 25, 'Telex-number                             ');
insert into label values (181, 25, 11, 0, 25, 'Account number                           ');
insert into label values (181, 25, 12, 0, 25, 'Name of general manager                  ');
insert into label values (181, 25, 13, 0, 25, 'Region label                             ');
insert into label values (181, 25, 14, 0, 25, 'Individual Attribut 1                    ');
insert into label values (181, 25, 15, 0, 25, 'Individual Attribut 2                    ');
insert into label values (181, 25, 16, 0, 25, 'Description                              ');
insert into label values (181, 26, 0, 0, 25, 'Service parts...                         ');
insert into label values (181, 26, 1, 0, 25, 'Label of servica part                    ');
insert into label values (181, 26, 2, 0, 25, 'Master service part                      ');
insert into label values (181, 26, 3, 0, 25, 'Offers (and prts of)                     ');
insert into label values (181, 26, 4, 0, 25, 'Start time  [dd.mm.yy [ss.mm]]           ');
insert into label values (181, 26, 5, 0, 25, 'End time    [dd.mm.yy [ss.mm]]           ');
insert into label values (181, 26, 6, 0, 25, 'Kind of reservation                      ');
insert into label values (181, 26, 7, 0, 25, 'Distributor/Administrator                ');
insert into label values (181, 26, 8, 0, 25, 'Profit account number                    ');
insert into label values (181, 26, 9, 0, 25, 'Description                              ');
insert into label values (181, 26, 10, 0, 25, 'Season                                   ');
insert into label values (181, 26, 11, 0, 25, 'Accounting office                        ');
insert into label values (181, 26, 12, 0, 25, 'Code                                     ');
insert into label values (181, 27, 0, 0, 25, 'Services...                              ');
insert into label values (181, 27, 1, 0, 25, 'Service part label                       ');
insert into label values (181, 27, 2, 0, 25, 'Service part                             ');
insert into label values (181, 27, 3, 0, 25, 'Description                              ');
insert into label values (181, 27, 4, 0, 25, 'Start date  [dd.mm.yy [ss.mm]]           ');
insert into label values (181, 27, 5, 0, 25, 'Actions                                  ');
insert into label values (181, 27, 6, 0, 25, 'Order                                    ');
insert into label values (181, 27, 7, 0, 25, 'Code                                     ');
insert into label values (181, 29, 0, 0, 25, 'Catalog/Destination...                   ');
insert into label values (181, 29, 1, 0, 25, 'Catalog/Dest. label                      ');
insert into label values (181, 29, 2, 0, 25, 'Code                                     ');
insert into label values (181, 29, 3, 0, 25, 'Description                              ');
insert into label values (181, 29, 4, 0, 25, 'Season                                   ');
insert into label values (181, 30, 0, 0, 25, 'Arrangements...                          ');
insert into label values (181, 30, 1, 0, 25, 'Arrangement label                        ');
insert into label values (181, 30, 2, 0, 25, 'Start Date  [dd.mm.yy]                   ');
insert into label values (181, 30, 3, 0, 25, 'Catalog/Destination                      ');
insert into label values (181, 30, 4, 0, 25, 'Priority                                 ');
insert into label values (181, 30, 5, 0, 25, 'Description                              ');
insert into label values (181, 30, 6, 0, 25, 'Service                                  ');
insert into label values (181, 30, 7, 0, 25, 'Part number                              ');
insert into label values (181, 30, 8, 0, 25, 'Code                                     ');
insert into label values (181, 32, 0, 0, 25, 'Types of collectives...                  ');
insert into label values (181, 32, 1, 0, 25, 'Label for type of collective             ');
insert into label values (181, 32, 2, 0, 25, 'Description                              ');
insert into label values (181, 32, 3, 0, 25, 'Code                                     ');
insert into label values (181, 33, 0, 0, 25, 'Groups/Collectivs...                     ');
insert into label values (181, 33, 1, 0, 25, 'Group label                              ');
insert into label values (181, 33, 2, 0, 25, 'Group leader                             ');
insert into label values (181, 33, 3, 0, 25, 'Type of group/collectivs                 ');
insert into label values (181, 33, 4, 0, 25, 'Description                              ');
insert into label values (181, 33, 5, 0, 25, 'Client Accounting address                ');
insert into label values (181, 33, 6, 0, 25, 'GSA / Booking office                     ');
insert into label values (181, 33, 7, 0, 25, 'Group reference                          ');
insert into label values (181, 35, 0, 0, 25, 'Types of passenger ...                   ');
insert into label values (181, 35, 1, 0, 25, 'Type of passenger label                  ');
insert into label values (181, 35, 2, 0, 25, 'Description                              ');
insert into label values (181, 35, 3, 0, 25, 'Code                                     ');
insert into label values (181, 35, 4, 0, 25, 'Lower age limit                          ');
insert into label values (181, 35, 5, 0, 25, 'Upper age limit                          ');
insert into label values (181, 36, 0, 0, 25, 'Passenger...                             ');
insert into label values (181, 36, 1, 0, 25, 'Pax number                               ');
insert into label values (181, 36, 2, 0, 25, 'Lastname                                 ');
insert into label values (181, 36, 3, 0, 25, 'Firstname                                ');
insert into label values (181, 36, 4, 0, 25, 'Residence                                ');
insert into label values (181, 36, 5, 0, 25, 'Type                                     ');
insert into label values (181, 36, 6, 0, 25, 'Sex/Salutation                           ');
insert into label values (181, 36, 7, 0, 25, 'Language                                 ');
insert into label values (181, 36, 8, 0, 25, 'Country                                  ');
insert into label values (181, 36, 9, 0, 25, 'Age                                      ');
insert into label values (181, 36, 10, 0, 25, 'Passport number                          ');
insert into label values (181, 36, 11, 0, 25, 'Nationality                              ');
insert into label values (181, 36, 12, 0, 25, 'Place of birth                           ');
insert into label values (181, 36, 13, 0, 25, 'Pax Info                                 ');
insert into label values (181, 36, 14, 0, 25, 'Ticket text                              ');
insert into label values (181, 37, 0, 0, 25, 'Adresses...                              ');
insert into label values (181, 37, 1, 0, 25, 'Client                                   ');
insert into label values (181, 37, 2, 0, 25, 'Passenger                                ');
insert into label values (181, 37, 3, 0, 25, 'Salutation                               ');
insert into label values (181, 37, 4, 0, 25, 'Adress                                   ');
insert into label values (181, 37, 5, 0, 25, 'Adress                                   ');
insert into label values (181, 37, 6, 0, 25, 'Adress                                   ');
insert into label values (181, 37, 7, 0, 25, 'Village                                  ');
insert into label values (181, 37, 8, 0, 25, 'Postal code                              ');
insert into label values (181, 37, 9, 0, 25, 'Delivery state                           ');
insert into label values (181, 38, 0, 0, 25, 'Hostcontingents...                       ');
insert into label values (181, 38, 1, 0, 25, 'Hostcontingent                           ');
insert into label values (181, 38, 2, 0, 25, 'From distributor                         ');
insert into label values (181, 38, 3, 0, 25, 'GSA Booking office                       ');
insert into label values (181, 38, 4, 0, 25, 'Offer (and parts of)                     ');
insert into label values (181, 38, 5, 0, 25, 'Service                                  ');
insert into label values (181, 38, 6, 0, 25, 'Start date                               ');
insert into label values (181, 38, 7, 0, 25, 'End date                                 ');
insert into label values (181, 38, 8, 0, 25, 'Option to  [dd.mm.yy]                    ');
insert into label values (181, 38, 9, 0, 25, 'Reference                                ');
insert into label values (181, 38, 10, 0, 25, 'Label                                    ');
insert into label values (181, 38, 11, 0, 25, 'Code                                     ');
insert into label values (181, 39, 0, 0, 25, 'Contingents...                           ');
insert into label values (181, 39, 1, 0, 25, 'Contingent                               ');
insert into label values (181, 39, 2, 0, 25, 'Master contingent                        ');
insert into label values (181, 39, 3, 0, 25, 'To client                                ');
insert into label values (181, 39, 4, 0, 25, 'Option to  [dd.mm.yy]                    ');
insert into label values (181, 39, 5, 0, 25, 'Reference                                ');
insert into label values (181, 39, 6, 0, 25, 'Label                                    ');
insert into label values (181, 40, 0, 0, 25, 'Contingentdetails...                     ');
insert into label values (181, 40, 1, 0, 25, 'Hostcontingent                           ');
insert into label values (181, 40, 2, 0, 25, 'Contingent                               ');
insert into label values (181, 40, 3, 0, 25, 'Category                                 ');
insert into label values (181, 40, 4, 0, 25, 'Quantity                                 ');
insert into label values (181, 40, 5, 0, 25, 'Minimum quantity                         ');
insert into label values (181, 40, 6, 0, 25, 'Location                                 ');
insert into label values (181, 40, 7, 0, 25, 'Overbooking factor                       ');
insert into label values (181, 41, 0, 0, 25, 'Dossier/Booking window...                ');
insert into label values (181, 41, 1, 0, 25, 'Bookingreference                         ');
insert into label values (181, 41, 2, 0, 25, 'Bookingnumber                            ');
insert into label values (181, 41, 3, 0, 25, 'Dossier/Booking state                    ');
insert into label values (181, 41, 4, 0, 25, 'Object: Date                             ');
insert into label values (181, 41, 5, 0, 25, 'Object: * arrangement                    ');
insert into label values (181, 41, 6, 0, 25, 'Object: * service                        ');
insert into label values (181, 41, 7, 0, 25, 'GSA:  Booking office                     ');
insert into label values (181, 41, 8, 0, 25, 'Client: accounting office                ');
insert into label values (181, 41, 9, 0, 25, 'Object: location                         ');
insert into label values (181, 41, 10, 0, 25, 'Object: offers ( and parts of)           ');
insert into label values (181, 41, 11, 0, 25, 'Client: group/team                       ');
insert into label values (181, 41, 12, 0, 25, 'Maindossier for this booking             ');
insert into label values (181, 41, 13, 0, 25, 'User name booking office                 ');
insert into label values (181, 41, 14, 0, 25, 'Requestoption is [dd.mm.yy]              ');
insert into label values (181, 41, 15, 0, 25, 'Client option is [dd.mm.yy]              ');
insert into label values (181, 41, 16, 0, 25, 'Bookinghistory                           ');
insert into label values (181, 41, 17, 0, 25, 'Booking: Passenger                       ');
insert into label values (181, 41, 18, 0, 25, 'Booking text                             ');
insert into label values (181, 43, 0, 0, 25, 'Type of cost ...                         ');
insert into label values (181, 43, 1, 0, 25, 'Type of cost label                       ');
insert into label values (181, 43, 2, 0, 25, 'Label                                    ');
insert into label values (181, 44, 0, 0, 25, 'Commission/Reduction...                  ');
insert into label values (181, 44, 1, 0, 25, 'Commission label                         ');
insert into label values (181, 44, 2, 0, 25, 'Type of commission                       ');
insert into label values (181, 44, 3, 0, 25, 'Type of unit                             ');
insert into label values (181, 44, 4, 0, 25, 'Unit/value                               ');
insert into label values (181, 44, 5, 0, 25, 'GSA Booking office/Travel agency         ');
insert into label values (181, 44, 6, 0, 25, 'Type of cost                             ');
insert into label values (181, 44, 7, 0, 25, 'Category                                 ');
insert into label values (181, 44, 8, 0, 25, 'Type of passenger                        ');
insert into label values (181, 44, 9, 0, 25, 'Offer (or part of)                       ');
insert into label values (181, 44, 10, 0, 25, 'Service                                  ');
insert into label values (181, 44, 11, 0, 25, 'Start date                               ');
insert into label values (181, 44, 12, 0, 25, 'End date                                 ');
insert into label values (181, 44, 13, 0, 25, 'Contingent                               ');
insert into label values (181, 44, 14, 0, 25, 'Booking                                  ');
insert into label values (181, 44, 15, 0, 25, 'Text                                     ');
insert into label values (181, 44, 16, 0, 25, 'Type of location                         ');
insert into label values (181, 45, 0, 0, 25, 'Link to commission ...                   ');
insert into label values (181, 45, 1, 0, 25, 'Commission label                         ');
insert into label values (181, 45, 2, 0, 25, 'Booking reference                        ');
insert into label values (181, 45, 3, 0, 25, 'Link to: Passenger                       ');
insert into label values (181, 45, 4, 0, 25, 'Link to: Client                          ');
insert into label values (181, 45, 5, 0, 25, 'Link to: PAX Group                       ');
insert into label values (181, 45, 6, 0, 25, 'Order                                    ');
insert into label values (181, 46, 0, 0, 25, 'Booking details ...                      ');
insert into label values (181, 46, 1, 0, 25, 'Service                                  ');
insert into label values (181, 46, 2, 0, 25, 'Part of service                          ');
insert into label values (181, 46, 3, 0, 25, 'Passenger                                ');
insert into label values (181, 46, 4, 0, 25, 'Location                                 ');
insert into label values (181, 46, 5, 0, 25, 'Type of location                         ');
insert into label values (181, 46, 6, 0, 25, 'Category                                 ');
insert into label values (181, 46, 7, 0, 25, 'Contingent                               ');
insert into label values (181, 46, 8, 0, 25, 'Reservation state                        ');
insert into label values (181, 46, 9, 0, 25, 'Start of service                         ');
insert into label values (181, 46, 10, 0, 25, 'End of service                           ');
insert into label values (181, 47, 0, 0, 25, 'Prices...                                ');
insert into label values (181, 47, 1, 0, 25, 'Price number                             ');
insert into label values (181, 47, 2, 0, 25, 'Currency                                 ');
insert into label values (181, 47, 3, 0, 25, 'Buying price                             ');
insert into label values (181, 47, 4, 0, 25, 'Cost price                               ');
insert into label values (181, 47, 5, 0, 25, 'Selling price                            ');
insert into label values (181, 47, 6, 0, 25, 'Valid from [dd.mm.yy]                    ');
insert into label values (181, 47, 7, 0, 25, 'GSA Booking office/Travel agency         ');
insert into label values (181, 47, 8, 0, 25, 'Type of cost                             ');
insert into label values (181, 47, 9, 0, 25, 'Type of location                         ');
insert into label values (181, 47, 10, 0, 25, 'Category                                 ');
insert into label values (181, 47, 11, 0, 25, 'Type of passenger                        ');
insert into label values (181, 47, 12, 0, 25, 'Offer (and parts)                        ');
insert into label values (181, 47, 13, 0, 25, 'Service                                  ');
insert into label values (181, 47, 14, 0, 25, 'Start date                               ');
insert into label values (181, 47, 15, 0, 25, 'End date                                 ');
insert into label values (181, 47, 16, 0, 25, 'Contingent                               ');
insert into label values (181, 47, 17, 0, 25, 'State                                    ');
insert into label values (181, 47, 18, 0, 25, 'Description                              ');
insert into label values (181, 47, 19, 0, 25, 'Arrangement                              ');
insert into label values (181, 47, 20, 0, 25, 'Type of unit                             ');
insert into label values (181, 47, 21, 0, 25, 'Unit from                                ');
insert into label values (181, 47, 22, 0, 25, 'Unit till                                ');
insert into label values (181, 48, 0, 0, 25, 'Graphic layout ...                       ');
insert into label values (181, 48, 1, 0, 25, 'Graphic label                            ');
insert into label values (181, 48, 2, 0, 25, 'Location                                 ');
insert into label values (181, 48, 3, 0, 25, 'Description                              ');
insert into label values (181, 49, 0, 0, 25, 'Pixelimages...                           ');
insert into label values (181, 49, 1, 0, 25, 'Pixelimage label                         ');
insert into label values (181, 49, 2, 0, 25, 'Pixelimage filename                      ');
insert into label values (181, 49, 3, 0, 25, 'Object type                              ');
insert into label values (181, 49, 4, 0, 25, 'Object                                   ');
insert into label values (181, 49, 5, 0, 25, 'Order                                    ');
insert into label values (181, 49, 6, 0, 25, 'relative X-value                         ');
insert into label values (181, 49, 7, 0, 25, 'relative Y-value                         ');
insert into label values (181, 150, 0, 0, 25, ' Info                                    ');
insert into label values (181, 150, 1, 0, 25, '*Help*                                   ');
insert into label values (181, 150, 2, 0, 25, ' next                                    ');
insert into label values (181, 150, 3, 0, 25, 'Field                                    ');
insert into label values (181, 150, 4, 0, 25, 'Previous                                 ');
insert into label values (181, 150, 5, 0, 25, ' Field                                   ');
insert into label values (181, 150, 6, 0, 25, 'Delete                                   ');
insert into label values (181, 150, 7, 0, 25, 'entry                                    ');
insert into label values (181, 150, 8, 0, 25, ' Stop                                    ');
insert into label values (181, 150, 9, 0, 25, 'input                                    ');
insert into label values (181, 150, 10, 0, 25, '  go                                     ');
insert into label values (181, 150, 11, 0, 25, ' ahead                                   ');
insert into label values (181, 150, 12, 0, 25, 'Delete                                   ');
insert into label values (181, 150, 13, 0, 25, ' Mask                                    ');
insert into label values (181, 150, 14, 0, 25, 'Window                                   ');
insert into label values (181, 150, 15, 0, 25, ' Exit                                    ');
insert into label values (181, 151, 0, 0, 25, 'File                                     ');
insert into label values (181, 151, 1, 0, 25, 'Booking                                  ');
insert into label values (181, 151, 2, 0, 25, 'Offers                                   ');
insert into label values (181, 151, 3, 0, 25, 'Core data                                ');
insert into label values (181, 151, 4, 0, 25, 'Geo                                      ');
insert into label values (181, 151, 5, 0, 25, 'Text                                     ');
insert into label values (181, 151, 6, 0, 25, 'Help                                     ');
insert into label values (181, 151, 7, 0, 25, '*                                        ');
insert into label values (181, 152, 0, 0, 25, 'Yes                                      ');
insert into label values (181, 152, 1, 0, 25, 'No                                       ');
insert into label values (181, 152, 2, 0, 25, 'Exit window ?                            ');
insert into label values (181, 152, 3, 0, 25, 'Delete entry ?                           ');
insert into label values (181, 152, 4, 0, 25, 'Modify entry ?                           ');
insert into label values (181, 152, 5, 0, 25, 'Continue                                 ');
insert into label values (181, 152, 6, 0, 25, 'Cancel                                   ');
insert into label values (181, 152, 7, 0, 25, 'Print                                    ');
insert into label values (181, 152, 8, 0, 25, 'next                                     ');
insert into label values (181, 152, 9, 0, 25, 'previous                                 ');
insert into label values (181, 152, 10, 0, 25, 'Exit travelDB ?                        ');
insert into label values (181, 152, 11, 0, 25, 'Save global values ?                     ');
insert into label values (181, 153, 0, 0, 25, 'Optional fields                          ');
insert into label values (181, 153, 1, 0, 25, 'New                                      ');
insert into label values (181, 153, 2, 0, 25, 'Modify                                   ');
insert into label values (181, 153, 3, 0, 25, 'Delete                                   ');
insert into label values (181, 154, 0, 0, 25, 'Mandatory fields                         ');
insert into label values (181, 154, 1, 0, 25, 'Optional fieldsr                         ');
insert into label values (181, 154, 2, 0, 25, 'Commands                                 ');
insert into label values (181, 154, 3, 0, 25, 'Setup                                    ');
insert into label values (181, 157, 0, 0, 25, '                                         ');
insert into label values (181, 157, 1, 0, 25, 'travelDB                               ');
insert into label values (181, 157, 2, 0, 25, 'Globale Values                           ');
insert into label values (181, 157, 3, 0, 25, 'GLOBAL                                   ');
insert into label values (181, 157, 4, 0, 25, 'Information                              ');
insert into label values (181, 157, 5, 0, 25, 'Manual                                   ');
insert into label values (181, 157, 6, 0, 25, 'Errormessage                             ');
insert into label values (181, 157, 7, 0, 25, 'Selection menu                           ');
insert into label values (181, 157, 8, 0, 25, 'Search mask                              ');
insert into label values (181, 157, 9, 0, 25, 'A T T E N T I O N                        ');
insert into label values (181, 157, 10, 0, 25, 'Selection                                ');
insert into label values (181, 157, 11, 0, 25, 'Priority                                 ');
insert into label values (181, 157, 12, 0, 25, 'Banner                                   ');
insert into label values (181, 157, 13, 0, 25, 'Warning                                  ');
insert into label values (181, 200, 0, 0, 25, 'Global values                            ');
insert into label values (181, 200, 1, 0, 25, 'Database (-)                             ');
insert into label values (181, 200, 2, 0, 25, 'User (-)                                 ');
insert into label values (181, 200, 3, 0, 25, 'GSA bookingoffice/travel agency          ');
insert into label values (181, 200, 4, 0, 25, 'Dialoglanguage                           ');
insert into label values (181, 200, 5, 0, 25, 'Country/Country setup                    ');
insert into label values (181, 200, 6, 0, 25, 'Type of location                         ');
insert into label values (181, 200, 7, 0, 25, 'Categorie                                ');
insert into label values (181, 200, 8, 0, 25, 'Location                                 ');
insert into label values (181, 200, 9, 0, 25, 'Type of offers                           ');
insert into label values (181, 200, 10, 0, 25, 'Type of passenger                        ');
insert into label values (181, 200, 11, 0, 25, 'Season                                   ');
insert into label values (181, 200, 12, 0, 25, 'Catalog / Destination                    ');
insert into label values (181, 200, 13, 0, 25, 'Initial - Datum                          ');
insert into label values (181, 200, 14, 0, 25, 'End - date                               ');
insert into label values (181, 200, 15, 0, 25, 'Period                                   ');
insert into label values (181, 201, 0, 0, 25, 'Start output/action ...                  ');
insert into label values (181, 201, 1, 0, 25, 'Outputprogram                            ');
insert into label values (181, 201, 2, 0, 25, 'Output device                            ');
insert into label values (181, 201, 3, 0, 25, 'Initial reservation state                ');
insert into label values (181, 201, 4, 0, 25, 'Target reservation state                 ');
insert into label values (181, 202, 0, 0, 25, 'Backup...                                ');
insert into label values (181, 202, 1, 0, 25, 'Backup                                   ');
insert into label values (181, 203, 0, 0, 25, 'Restore...                               ');
insert into label values (181, 203, 1, 0, 25, 'Restore                                  ');
insert into label values (181, 209, 0, 0, 25, 'Setup/Administration ...                 ');
insert into label values (181, 209, 1, 0, 25, 'Edition/transfers                        ');
insert into label values (181, 209, 2, 0, 25, '--unused frame 2 --                      ');
insert into label values (181, 209, 3, 0, 25, 'Preferences                              ');
insert into label values (181, 209, 4, 0, 25, ' ! Software tests                        ');
insert into label values (181, 209, 5, 0, 25, 'Global Values                            ');
insert into label values (181, 209, 6, 0, 25, 'Commands                                 ');
insert into label values (181, 209, 7, 0, 25, 'Reinit program                           ');
insert into label values (181, 209, 8, 0, 25, 'Generate labelfile                       ');
insert into label values (181, 210, 0, 0, 25, 'Database log                             ');
insert into label values (181, 210, 1, 0, 25, 'User log                                 ');
insert into label values (181, 210, 2, 0, 25, 'Automatic Info                           ');
insert into label values (181, 210, 3, 0, 25, 'Graphic                                  ');
insert into label values (181, 210, 4, 0, 25, 'Entry pax one after another              ');
insert into label values (181, 210, 5, 0, 25, 'Show global values                       ');
insert into label values (181, 210, 6, 0, 25, 'Sort order: ON=date OFF=description      ');
insert into label values (181, 210, 7, 0, 25, 'Audio on/off                             ');
insert into label values (181, 210, 8, 0, 25, 'Debug information                        ');
insert into label values (181, 210, 9, 0, 25, 'Fast rread                               ');
insert into label values (181, 211, 0, 0, 25, 'Setup Globalvalues file ...              ');
insert into label values (181, 212, 0, 0, 25, 'travelDB exit ...                      ');
insert into label values (181, 213, 0, 0, 25, 'Application                              ');
insert into label values (181, 214, 0, 0, 25, 'About...                                 ');
insert into label values (182, 2, 0, 0, 25, 'Passenger short entry                    ');
insert into label values (182, 2, 1, 0, 25, 'Salutation                               ');
insert into label values (182, 2, 2, 0, 25, 'Identity                                 ');
insert into label values (182, 2, 3, 0, 25, 'Reduction                                ');
insert into label values (182, 2, 4, 0, 25, 'Passenger type                           ');
insert into label values (182, 2, 5, 0, 25, 'Actions                                  ');
insert into label values (182, 2, 6, 0, 25, 'Settings                                 ');
insert into label values (182, 2, 7, 0, 25, '-- unused frame --                       ');
insert into label values (182, 2, 8, 0, 25, '-- unused frame --                       ');
insert into label values (182, 3, 0, 0, 25, 'Lastname                                 ');
insert into label values (182, 3, 1, 0, 25, 'Firstname                                ');
insert into label values (182, 3, 2, 0, 25, 'Birthdate                                ');
insert into label values (182, 3, 3, 0, 25, 'Internal text                            ');
insert into label values (182, 3, 4, 0, 25, 'External text                            ');
insert into label values (182, 3, 5, 0, 25, 'Language                                 ');
insert into label values (182, 3, 6, 0, 25, '--Unused--                               ');
insert into label values (182, 4, 0, 0, 25, 'Reservations ...                         ');
insert into label values (182, 4, 1, 0, 25, 'Booking                                  ');
insert into label values (182, 4, 2, 0, 25, 'Reservationobjects                       ');
insert into label values (182, 4, 3, 0, 25, 'Addition/State                           ');
insert into label values (182, 4, 4, 0, 25, 'Actions                                  ');
insert into label values (182, 5, 0, 0, 25, 'Serv.                                    ');
insert into label values (182, 5, 1, 0, 25, '.........                                ');
insert into label values (182, 5, 2, 0, 25, '.   B-No:                                ');
insert into label values (182, 5, 3, 0, 25, '.........                                ');
insert into label values (182, 5, 4, 0, 25, '.  B-Ref:                                ');
insert into label values (182, 5, 5, 0, 25, '.........                                ');
insert into label values (182, 5, 6, 0, 25, 'Passenger:                               ');
insert into label values (182, 5, 7, 0, 25, '.........                                ');
insert into label values (182, 6, 0, 0, 25, 'Description of category                  ');
insert into label values (182, 6, 1, 0, 25, 'Normal price                             ');
insert into label values (182, 6, 2, 0, 25, 'Pers. per location                       ');
insert into label values (182, 6, 3, 0, 25, 'Places in contingent                     ');
insert into label values (182, 6, 4, 0, 25, 'Places out of contingent                 ');
insert into label values (182, 6, 5, 0, 25, 'Additional place                         ');
insert into label values (182, 7, 0, 0, 25, 'Passenger   (empty = all)                ');
insert into label values (182, 7, 1, 0, 25, 'State of reservation                     ');
insert into label values (182, 7, 2, 0, 25, 'Location                                 ');
insert into label values (182, 7, 3, 0, 25, 'Location typ                             ');
insert into label values (182, 7, 4, 0, 25, 'Service Part                             ');
insert into label values (182, 7, 5, 0, 25, 'Service: start time                      ');
insert into label values (182, 7, 6, 0, 25, 'Service: end time                        ');
insert into label values (182, 7, 7, 0, 25, 'Contigent                                ');
insert into label values (182, 7, 8, 0, 25, 'Request text                             ');
insert into label values (182, 8, 0, 0, 25, 'Location selection                       ');
insert into label values (182, 8, 1, 0, 25, 'Location                                 ');
insert into label values (182, 8, 2, 0, 25, 'Other location                           ');
insert into label values (182, 8, 3, 0, 25, 'Actions                                  ');
insert into label values (182, 8, 4, 0, 25, '*                                        ');
insert into label values (182, 9, 0, 0, 25, 'Location No.                             ');
insert into label values (182, 10, 0, 0, 25, 'Planningboard                            ');
insert into label values (182, 10, 1, 0, 25, 'Exit                                     ');
insert into label values (182, 10, 2, 0, 25, 'Help                                     ');
commit work;
