/*
* labels used in travelDB TO 2000 only !
* 
* Copyright : yafra.org
* Author : 
* Creation Date : 01/12/1998
*
* execution steps :
* 1) copy-paste this green column in a file "file_name.sql"
* 2) in SQLPlus, execute this file with the command "@file_name.sql"
*/
/* delete old to2000 labels */
delete from mp_label where S_ID =25 ;

/* labels definition */
insert into mp_label values (0, 0,1,25, 'Traveller' );
insert into mp_label values (1, 0,1,25, 'Gender' );
insert into mp_label values (2, 0,1,25, 'female' );
insert into mp_label values (3, 0,1,25, 'male' );
insert into mp_label values (4, 0,1,25, 'First Name' );
insert into mp_label values (5, 0,1,25, 'Last Name' );
insert into mp_label values (6, 0,1,25, 'Date of birth' );
insert into mp_label values (7, 0,1,25, 'Language' );
insert into mp_label values (8, 0,1,25, 'Confidential Text' );
insert into mp_label values (9, 0,1,25, 'Remaks' );
insert into mp_label values (10, 0,1,25, 'Reduction' );
insert into mp_label values (11, 0,1,25, 'Priority' );
insert into mp_label values (12, 0,1,25, 'Type of Traveller' );
insert into mp_label values (13, 0,1,25, 'Salutation' );
insert into mp_label values (14, 0,1,25, 'Address' );
insert into mp_label values (15, 0,1,25, '  ' );
insert into mp_label values (16, 0,1,25, '  ' );
insert into mp_label values (17, 0,1,25, 'ZIP' );
insert into mp_label values (18, 0,1,25, 'City / Place' );
insert into mp_label values (19, 0,1,25, 'Country' );
insert into mp_label values (20, 0,1,25, 'Shipping mode' );
insert into mp_label values (21, 0,1,25, 'Passport nr.' );
insert into mp_label values (22, 0,1,25, 'Nationality' );
insert into mp_label values (0, 0,2,25, 'File' );
insert into mp_label values (2, 0,2,25, 'Booking nr.' );
insert into mp_label values (3, 0,2,25, 'Status' );
insert into mp_label values (4, 0,2,25, 'Package' );
insert into mp_label values (5, 0,2,25, 'Services' );
insert into mp_label values (6, 0,2,25, 'Group' );
insert into mp_label values (7, 0,2,25, 'Notes' );
insert into mp_label values (8, 0,2,25, 'Client' );
insert into mp_label values (9, 0,2,25, 'Supplier option' );
insert into mp_label values (10, 0,2,25, 'Available services to add to folder' );
insert into mp_label values (11, 0,2,25, 'Available services to remove from folder' );
insert into mp_label values (12, 0,2,25, 'Client option date' );
insert into mp_label values (13, 0,2,25, 'Group rebate' );
insert into mp_label values (14, 0,2,25, 'Client rebate' );
insert into mp_label values (15, 0,2,25, 'Rebate rate' );
insert into mp_label values (16, 0,2,25, 'Rebate amount' );
insert into mp_label values (0, 0,3,25, 'Travel' );
insert into mp_label values (2, 0,3,25, 'Status' );
insert into mp_label values (3, 0,3,25, 'Allotement' );
insert into mp_label values (4, 0,3,25, 'Category' );
insert into mp_label values (5, 0,3,25, 'Upgrade category' );
insert into mp_label values (6, 0,3,25, 'Date Choice' );
insert into mp_label values (7, 0,3,25, 'Begin date' );
insert into mp_label values (8, 0,3,25, 'End date' );
insert into mp_label values (9, 0,3,25, 'Step Selection' );
insert into mp_label values (10, 0,3,25, 'Service carrier' );
insert into mp_label values (11, 0,3,25, 'Service code' );
insert into mp_label values (12, 0,3,25, 'Supplier' );
insert into mp_label values (13, 0,3,25, 'Notice' );
insert into mp_label values (14, 0,3,25, 'Service rebate' );
insert into mp_label values (15, 0,3,25, 'Offer rebate' );
insert into mp_label values (0, 0,4,25, 'Search service' );
insert into mp_label values (1, 0,4,25, 'Description' );
insert into mp_label values (2, 0,4,25, 'Departure' );
insert into mp_label values (3, 0,4,25, 'Arrival' );
insert into mp_label values (4, 0,4,25, 'Begin date' );
insert into mp_label values (5, 0,4,25, 'End date' );
insert into mp_label values (6, 0,4,25, 'Season' );
insert into mp_label values (7, 0,4,25, 'Offer type' );
insert into mp_label values (8, 0,4,25, 'service(s) found' );
insert into mp_label values (9, 0,4,25, 'Add selected service(s) to traveller' );
insert into mp_label values (10, 0,4,25, 'New service search' );
insert into mp_label values (11, 0,4,25, 'Cancel' );
insert into mp_label values (12, 0,4,25, 'Date type' );
insert into mp_label values (13, 0,4,25, 'Search' );
insert into mp_label values (14, 0,4,25, 'Search again' );
insert into mp_label values (15, 0,4,25, 'SRV' );
insert into mp_label values (16, 0,4,25, 'Code' );
insert into mp_label values (0, 0,5,25, 'Package search' );
insert into mp_label values (1, 0,5,25, 'Description' );
insert into mp_label values (2, 0,5,25, 'Departure' );
insert into mp_label values (3, 0,5,25, 'Arrival' );
insert into mp_label values (4, 0,5,25, 'Departure date' );
insert into mp_label values (5, 0,5,25, 'Arrival date' );
insert into mp_label values (6, 0,5,25, 'Season' );
insert into mp_label values (7, 0,5,25, 'Catalog' );
insert into mp_label values (8, 0,5,25, 'Package(s) found' );
insert into mp_label values (9, 0,5,25, 'Add package to ...' );
insert into mp_label values (10, 0,5,25, 'New package search' );
insert into mp_label values (11, 0,5,25, 'Cancel' );
insert into mp_label values (12, 0,5,25, 'Date type' );
insert into mp_label values (13, 0,5,25, 'ARR' );
insert into mp_label values (14, 0,5,25, 'Code' );
insert into mp_label values (0, 0,6,25, 'Traveller search' );
insert into mp_label values (1, 0,6,25, 'First name' );
insert into mp_label values (2, 0,6,25, 'Last name' );
insert into mp_label values (3, 0,6,25, 'Type' );
insert into mp_label values (4, 0,6,25, 'Traveller(s) found' );
insert into mp_label values (5, 0,6,25, 'Add traveller(s) to file' );
insert into mp_label values (6, 0,6,25, 'New traveller' );
insert into mp_label values (7, 0,6,25, 'Cancel' );
insert into mp_label values (8, 0,6,25, 'Date of birth' );
insert into mp_label values (9, 0,6,25, 'Search' );
insert into mp_label values (10, 0,6,25, 'Search again' );
insert into mp_label values (11, 0,6,25, 'Gender' );
insert into mp_label values (12, 0,6,25, 'Language' );
insert into mp_label values (0, 0,7,25, 'System preferences' );
insert into mp_label values (1, 0,7,25, 'Change password' );
insert into mp_label values (2, 0,7,25, 'Name' );
insert into mp_label values (3, 0,7,25, 'Old password' );
insert into mp_label values (4, 0,7,25, 'New password' );
insert into mp_label values (5, 0,7,25, 'Password Confirmation' );
insert into mp_label values (6, 0,7,25, 'GUI language' );
insert into mp_label values (0, 0,8,25, 'Booking settings' );
insert into mp_label values (1, 0,8,25, 'Role' );
insert into mp_label values (2, 0,8,25, 'Booking place' );
insert into mp_label values (3, 0,8,25, 'Season' );
insert into mp_label values (4, 0,8,25, 'Date from' );
insert into mp_label values (5, 0,8,25, 'to' );
insert into mp_label values (0, 0,9,25, 'Search file' );
insert into mp_label values (1, 0,9,25, 'Booking number' );
insert into mp_label values (2, 0,9,25, 'State' );
insert into mp_label values (3, 0,9,25, 'Group' );
insert into mp_label values (4, 0,9,25, 'Client' );
insert into mp_label values (5, 0,9,25, 'File(s) found' );
insert into mp_label values (6, 0,9,25, 'Get File' );
insert into mp_label values (7, 0,9,25, 'Open new booking' );
insert into mp_label values (8, 0,9,25, 'Cancel' );
insert into mp_label values (9, 0,9,25, 'Search' );
insert into mp_label values (10, 0,9,25, 'Search again' );
insert into mp_label values (11, 0,9,25, 'Supplier option from' );
insert into mp_label values (12, 0,9,25, 'to' );
insert into mp_label values (13, 0,9,25, 'Supplier option' );
insert into mp_label values (14, 0,9,25, 'Client option from' );
insert into mp_label values (15, 0,9,25, 'to' );
insert into mp_label values (16, 0,9,25, 'Client option ' );
insert into mp_label values (17, 0,9,25, 'Owner' );
insert into mp_label values (18, 0,9,25, 'Traveler' );
insert into mp_label values (19, 0,9,25, 'Service Code' );
insert into mp_label values (20, 0,9,25, 'Notes' );
insert into mp_label values (0, 0,10,25, 'login' );
insert into mp_label values (3, 0,10,25, 'OK' );
insert into mp_label values (4, 0,10,25, 'Cancel' );
insert into mp_label values (0, 0,11,25, 'global popup-menu' );
insert into mp_label values (1, 0,11,25, 'Save all' );
insert into mp_label values (2, 0,11,25, 'Help' );
insert into mp_label values (3, 0,11,25, 'Exit' );
insert into mp_label values (4, 0,11,25, 'Cut' );
insert into mp_label values (5, 0,11,25, 'Copy' );
insert into mp_label values (6, 0,11,25, 'Paste' );
insert into mp_label values (7, 0,11,25, 'About MARCO POLO' );
insert into mp_label values (8, 0,11,25, 'File' );
insert into mp_label values (9, 0,11,25, 'Edit' );
insert into mp_label values (10, 0,11,25, 'Session' );
insert into mp_label values (11, 0,11,25, 'File' );
insert into mp_label values (12, 0,11,25, 'Traveller' );
insert into mp_label values (13, 0,11,25, 'Service' );
insert into mp_label values (14, 0,11,25, 'Help' );
insert into mp_label values (0, 0,12,25, 'folder popup-menu' );
insert into mp_label values (1, 0,12,25, 'New Traveller' );
insert into mp_label values (2, 0,12,25, 'Save whole folder' );
insert into mp_label values (3, 0,12,25, 'Close' );
insert into mp_label values (4, 0,12,25, 'Do you really want to close this file ?' );
insert into mp_label values (5, 0,12,25, 'Properties' );
insert into mp_label values (6, 0,12,25, 'Add to arrangement' );
insert into mp_label values (7, 0,12,25, 'Delete from package' );
insert into mp_label values (8, 0,12,25, 'Cancel' );
insert into mp_label values (9, 0,12,25, 'OK to delete service from package?' );
insert into mp_label values (10, 0,12,25, 'Delete' );
insert into mp_label values (11, 0,12,25, 'Do you want to delete this Folder ?' );
insert into mp_label values (12, 0,12,25, 'Progress' );
insert into mp_label values (13, 0,12,25, 'Set To Status Request' );
insert into mp_label values (14, 0,12,25, 'Set To Status Option' );
insert into mp_label values (15, 0,12,25, 'All Booking informations sent' );
insert into mp_label values (16, 0,12,25, 'Hotel Confirmation sent to client' );
insert into mp_label values (17, 0,12,25, 'Modify/Annulate' );
insert into mp_label values (18, 0,12,25, 'Save folder details only' );
insert into mp_label values (0, 0,13,25, 'Traveler popup-menu' );
insert into mp_label values (1, 0,13,25, 'New Service' );
insert into mp_label values (2, 0,13,25, 'Save' );
insert into mp_label values (3, 0,13,25, 'Delete' );
insert into mp_label values (4, 0,13,25, 'Do you want to delete this Traveller ?' );
insert into mp_label values (5, 0,13,25, 'Save' );
insert into mp_label values (6, 0,13,25, 'Delete' );
insert into mp_label values (7, 0,13,25, 'Do you want to delete this Service ?' );
insert into mp_label values (8, 0,13,25, 'Progress toward... ' );
insert into mp_label values (9, 0,13,25, 'Modify/Annulate ...' );
insert into mp_label values (0, 0,14,25, 'Client / Booking place' );
insert into mp_label values (1, 0,14,25, 'Name' );
insert into mp_label values (2, 0,14,25, 'Type' );
insert into mp_label values (3, 0,14,25, 'Currency' );
insert into mp_label values (4, 0,14,25, 'Language' );
insert into mp_label values (5, 0,14,25, 'Account Number' );
insert into mp_label values (6, 0,14,25, 'Description' );
insert into mp_label values (7, 0,14,25, 'Address' );
insert into mp_label values (8, 0,14,25, ' ' );
insert into mp_label values (9, 0,14,25, ' ' );
insert into mp_label values (10, 0,14,25, 'ZIP' );
insert into mp_label values (11, 0,14,25, 'City' );
insert into mp_label values (12, 0,14,25, 'Country' );
insert into mp_label values (13, 0,14,25, 'Shipping mode' );
insert into mp_label values (14, 0,14,25, 'Telephone' );
insert into mp_label values (15, 0,14,25, 'Fax' );
insert into mp_label values (16, 0,14,25, 'E-Mail' );
insert into mp_label values (17, 0,14,25, 'Internet' );
insert into mp_label values (18, 0,14,25, 'Code' );
insert into mp_label values (0, 0,15,25, 'Group' );
insert into mp_label values (1, 0,15,25, 'Reference' );
insert into mp_label values (2, 0,15,25, 'Description' );
insert into mp_label values (3, 0,15,25, 'Type of Group' );
insert into mp_label values (4, 0,15,25, 'Client' );
insert into mp_label values (5, 0,15,25, 'Booking Place' );
insert into mp_label values (6, 0,15,25, 'Group Leader' );
insert into mp_label values (7, 0,15,25, 'Description' );
insert into mp_label values (0, 0,16,25, 'session popup-menu' );
insert into mp_label values (1, 0,16,25, 'New Ad-Hoc File' );
insert into mp_label values (2, 0,16,25, 'New Package File' );
insert into mp_label values (3, 0,16,25, 'Save' );
insert into mp_label values (4, 0,16,25, 'Search file' );
insert into mp_label values (5, 0,16,25, 'Close All Files' );
insert into mp_label values (0, 0,17,25, 'session' );
insert into mp_label values (1, 0,17,25, 'Booking' );
insert into mp_label values (2, 0,17,25, 'Preferences' );
insert into mp_label values (3, 0,17,25, 'Clients' );
insert into mp_label values (4, 0,17,25, 'Preferences for' );
insert into mp_label values (5, 0,17,25, 'Tools for' );
insert into mp_label values (6, 0,17,25, 'Save all before closing all opened files?' );
insert into mp_label values (0, 0,18,25, 'calendar' );
insert into mp_label values (1, 0,18,25, 'January' );
insert into mp_label values (2, 0,18,25, 'February' );
insert into mp_label values (3, 0,18,25, 'March' );
insert into mp_label values (4, 0,18,25, 'April' );
insert into mp_label values (5, 0,18,25, 'May' );
insert into mp_label values (6, 0,18,25, 'June' );
insert into mp_label values (7, 0,18,25, 'July' );
insert into mp_label values (8, 0,18,25, 'August' );
insert into mp_label values (9, 0,18,25, 'September' );
insert into mp_label values (10, 0,18,25, 'October' );
insert into mp_label values (11, 0,18,25, 'November' );
insert into mp_label values (12, 0,18,25, 'December' );
insert into mp_label values (20, 0,18,25, 'mo' );
insert into mp_label values (21, 0,18,25, 'tu' );
insert into mp_label values (22, 0,18,25, 'we' );
insert into mp_label values (23, 0,18,25, 'th' );
insert into mp_label values (24, 0,18,25, 'fr' );
insert into mp_label values (25, 0,18,25, 'sa' );
insert into mp_label values (26, 0,18,25, 'su' );
insert into mp_label values (0, 0,19,25, 'group popup-menu' );
insert into mp_label values (1, 0,19,25, 'Save' );
insert into mp_label values (2, 0,19,25, 'New Group' );
insert into mp_label values (3, 0,19,25, 'Delete' );
insert into mp_label values (4, 0,19,25, 'Do you want to delete this Group ?' );
insert into mp_label values (0, 0,20,25, 'client popup-menu' );
insert into mp_label values (1, 0,20,25, 'Save' );
insert into mp_label values (2, 0,20,25, 'New client / booking place' );
insert into mp_label values (3, 0,20,25, 'Delete' );
insert into mp_label values (4, 0,20,25, 'Do you want to delete this Client ?' );
insert into mp_label values (0, 0,21,25, 'Properties' );
insert into mp_label values (1, 0,21,25, 'Properties' );
insert into mp_label values (2, 0,21,25, 'OK' );
insert into mp_label values (3, 0,21,25, 'Properties of folder' );
insert into mp_label values (0, 0,22,25, 'action popup-menu' );
insert into mp_label values (1, 1,22,25, 'Global passenger list' );
insert into mp_label values (1, 2,22,25, 'Reservation status control' );
insert into mp_label values (1, 3,22,25, 'Supplier option list' );
insert into mp_label values (1, 4,22,25, 'Client option list ' );
insert into mp_label values (1, 5,22,25, 'Global amount' );
insert into mp_label values (1, 6,22,25, 'Allotement Control' );
insert into mp_label values (1, 7,22,25, 'Allotement Overflows' );
insert into mp_label values (1, 8,22,25, 'Hotel Status Control' );
insert into mp_label values (1, 9,22,25, 'Rooming List' );
insert into mp_label values (1, 10,22,25, 'Planing Board' );
insert into mp_label values (2, 1,22,25, 'Properties' );
insert into mp_label values (2, 2,22,25, 'Voucher' );
insert into mp_label values (2, 3,22,25, 'Booking amount' );
insert into mp_label values (2, 4,22,25, 'Hotel Confirmation to Client' );
insert into mp_label values (2, 5,22,25, 'Allotement Info' );
insert into mp_label values (2, 6,22,25, 'Invoice' );
insert into mp_label values (3, 1,22,25, 'Cancellation Request' );
insert into mp_label values (4, 1,22,25, 'Passenger list' );
insert into mp_label values (4, 2,22,25, 'Request to supplier' );
insert into mp_label values (4, 3,22,25, 'Voucher' );
insert into mp_label values (4, 4,22,25, 'Booking Information' );
insert into mp_label values (4, 5,22,25, 'Additional Request' );
insert into mp_label values (5, 1,22,25, 'Voucher' );
insert into mp_label values (0, 0,23,25, 'Reports' );
insert into mp_label values (1, 0,23,25, 'Status Control Report' );
insert into mp_label values (2, 0,23,25, 'Supplier option list' );
insert into mp_label values (3, 0,23,25, 'Client option list ' );
insert into mp_label values (4, 0,23,25, 'Allotement Control' );
insert into mp_label values (5, 0,23,25, 'Hotel Status Control' );
insert into mp_label values (6, 0,23,25, 'Rooming List' );
insert into mp_label values (7, 0,23,25, 'Planing Board' );
insert into mp_label values (10, 0,23,25, 'Status from' );
insert into mp_label values (11, 0,23,25, 'Status to' );
insert into mp_label values (12, 0,23,25, 'Supplier date from' );
insert into mp_label values (13, 0,23,25, 'Supplier date to' );
insert into mp_label values (14, 0,23,25, 'Client date from' );
insert into mp_label values (15, 0,23,25, 'Client date to' );
insert into mp_label values (16, 0,23,25, 'Code' );
insert into mp_label values (17, 0,23,25, 'Start week' );
insert into mp_label values (18, 0,23,25, 'End week' );
insert into mp_label values (20, 0,23,25, 'Show report' );
insert into mp_label values (21, 0,23,25, 'Cancel' );
insert into mp_label values (41, 0,23,25, 'Host Allotement' );
insert into mp_label values (51, 0,23,25, 'Hotel Code' );
insert into mp_label values (0, 0,24,25, 'Popup-menu Preferences' );
insert into mp_label values (1, 0,24,25, 'Save Preferences' );
insert into mp_label values (0, 0,25,25, 'Wizard' );
insert into mp_label values (1, 0,25,25, '< Back' );
insert into mp_label values (2, 0,25,25, 'Next >' );
insert into mp_label values (3, 0,25,25, 'Cancel' );
insert into mp_label values (4, 0,25,25, 'Finish' );
insert into mp_label values (0, 0,26,25, 'Wizard Mapo' );
insert into mp_label values (1, 0,26,25, 'Create Folder from Agent Wizard' );
insert into mp_label values (2, 0,26,25, 'Create Folder from FIT Wizard' );
insert into mp_label values (10, 0,26,25, 'Select One Agent' );
insert into mp_label values (11, 0,26,25, 'Select Search Parameters' );
insert into mp_label values (12, 0,26,25, 'Select One Arrangement' );
insert into mp_label values (13, 0,26,25, 'Selected Arrangement' );
insert into mp_label values (14, 0,26,25, 'Summary of selected services' );
insert into mp_label values (15, 0,26,25, 'One more ARR/SRV' );
insert into mp_label values (16, 0,26,25, 'No more ARR/SRV' );
insert into mp_label values (17, 0,26,25, 'Enter Travellers' );
insert into mp_label values (18, 0,26,25, 'Add Traveller' );
insert into mp_label values (19, 0,26,25, 'Remove Traveller' );
insert into mp_label values (20, 0,26,25, 'PAX Number' );
insert into mp_label values (21, 0,26,25, 'Code' );
insert into mp_label values (22, 0,26,25, 'Select One Service' );
insert into mp_label values (23, 0,26,25, 'Additionnal Information' );
insert into mp_label values (0, 0,27,25, 'MARCO POLO' );
insert into mp_label values (1, 0,27,25, 'OK' );
insert into mp_label values (2, 0,27,25, 'Yes' );
insert into mp_label values (3, 0,27,25, 'No' );
insert into mp_label values (4, 0,27,25, 'Cancel' );
insert into mp_label values (0, 0,30,25, 'Amexco Import Wizard' );
insert into mp_label values (1, 0,30,25, 'Amexco Import Wizard' );

















insert into mp_label values (0, 0,31,25, 'Amexco Synchronisation Wizard' );
insert into mp_label values (1, 0,31,25, 'Amexco Synchronisation Wizard' );
insert into mp_label values (2, 0,42,25, 'Please select a client. If your client is not in the list, create it in the Client panel' );
insert into mp_label values (7, 0,42,25, 'Can''t create a new traveler.' );
insert into mp_label values (1, 0,505,25, 'Exception' );
insert into mp_label values (2, 0,505,25, 'Look And Feel change failed.' );
insert into mp_label values (3, 0,505,25, 'Cannot go to folder state.' );
insert into mp_label values (4, 0,505,25, 'Cannot go to service state.' );
insert into mp_label values (1, 0,506,25, 'Error' );
insert into mp_label values (2, 0,506,25, 'Error while checking present plugins.' );
insert into mp_label values (3, 0,506,25, 'Can''t delete file ' );
insert into mp_label values (4, 0,506,25, '.' );
insert into mp_label values (5, 0,506,25, 'Can''t delete file. ' );
insert into mp_label values (6, 0,506,25, 'Can''t create new booking.' );
insert into mp_label values (7, 0,506,25, 'Can''t create new arrangement booking.' );
insert into mp_label values (8, 0,506,25, 'Can''t validate.' );
insert into mp_label values (9, 0,506,25, 'Can''t create new group.' );
insert into mp_label values (10, 0,506,25, 'Can''t create new client.' );
insert into mp_label values (11, 0,506,25, 'Error getting input dialog.' );
insert into mp_label values (12, 0,506,25, 'Can''t create new arrangement.' );
insert into mp_label values (13, 0,506,25, 'Can''t remove client.' );
insert into mp_label values (14, 0,506,25, 'Can''t remove group.' );
insert into mp_label values (15, 0,506,25, 'Can''t remove folder.' );
insert into mp_label values (16, 0,506,25, 'Can''t remove traveler.' );
insert into mp_label values (17, 0,506,25, 'Can''t remove service.' );
insert into mp_label values (18, 0,506,25, 'Failed to get state.' );
insert into mp_label values (19, 0,506,25, 'Failed to set state.' );
insert into mp_label values (20, 0,506,25, 'Unexpected CORBA exception.' );
insert into mp_label values (21, 0,506,25, 'Can''t create report.' );
insert into mp_label values (22, 0,506,25, 'Error opening help file.' );
insert into mp_label values (23, 0,506,25, 'Can''t launch Acrobat Reader.' );
insert into mp_label values (24, 0,506,25, 'Can''t retrieve group ' );
insert into mp_label values (25, 0,506,25, '.' );
insert into mp_label values (26, 0,506,25, 'Unable to get client from code ' );

insert into mp_label values (28, 0,506,25, 'Can''t retrieve client ' );
insert into mp_label values (29, 0,506,25, '.' );
insert into mp_label values (0, 0,1001,25, 'Session warning message' );
insert into mp_label values (1, 0,1001,25, 'This folder is already opened by another user.' );
insert into mp_label values (0, 0,1002,25, 'Folder Warning Message' );
insert into mp_label values (1, 0,1002,25, 'Folder' );
insert into mp_label values (2, 0,1002,25, 'Please select a client. If your client is not in the list, create it in the Client panel' );
insert into mp_label values (3, 0,1002,25, 'Please enter the given amount :' );
insert into mp_label values (4, 0,1002,25, 'Confirmation was not send because of recipient missing. You should enter an address or send the confirmation manually.' );
insert into mp_label values (5, 0,1002,25, 'Confirmation was not send because of a mailer error. If this problem persists, contact yoru system administrator.' );
insert into mp_label values (6, 0,1002,25, 'Confirmation was not send for a undefined reason. Please check your data/your configuration  or send the confirmation manually.' );
insert into mp_label values (7, 0,1002,25, 'Can''t create a new traveler.' );
insert into mp_label values (0, 0,1003,25, 'Traveler Warning Message' );
insert into mp_label values (0, 0,1004,25, 'Travel Warning Message' );
insert into mp_label values (1, 0,1004,25, 'Folder' );
insert into mp_label values (2, 0,1004,25, ', traveler' );
insert into mp_label values (3, 0,1004,25, ', travel number' );
insert into mp_label values (4, 0,1004,25, 'You can''t remove all stages, old stages are kept.' );
insert into mp_label values (5, 0,1004,25, 'Allotement cannot be changed, excepted in ""Input"" state.  You should use the right button ""Modify/Annulate"" function at first.' );
insert into mp_label values (6, 0,1004,25, 'Category cannot be changed, excepted in ""Input"" state.  You should use the right button ""Modify/Annulate"" function at first.' );
insert into mp_label values (7, 0,1004,25, 'Carrier cannot be changed, excepted in ""Input"" state.  You should use the right button ""Modify/Annulate"" function at first.' );
insert into mp_label values (8, 0,1004,25, 'Start date cannot be changed, excepted in ""Input"" state.  You should use the right button ""Modify/Annulate"" function at first.' );
insert into mp_label values (9, 0,1004,25, 'End date cannot be changed, excepted in ""Input"" state.  You should use the right button ""Modify/Annulate"" function at first.' );
insert into mp_label values (10, 0,1004,25, 'No date change allowed for static services.' );
insert into mp_label values (11, 0,1004,25, 'Please choose a category.' );
insert into mp_label values (12, 0,1004,25, 'The details of the allotement you used are not defined.' );
insert into mp_label values (13, 0,1004,25, 'Your old values were kept.' );
insert into mp_label values (14, 0,1004,25, 'Only the category was validated, allotement was unselected.' );
insert into mp_label values (15, 0,1004,25, 'Your allotement will soon be totally busy, you may ask your supplier for additional places.' );
insert into mp_label values (16, 0,1004,25, 'There is' );
insert into mp_label values (17, 0,1004,25, 'place(s) left for this category after this service is booked.' );
insert into mp_label values (18, 0,1004,25, 'There is' );
insert into mp_label values (19, 0,1004,25, 'place(s) left in whole allotement after this service is booked.' );
insert into mp_label values (20, 0,1004,25, 'This allotement is totally busy, it is impossible to book into anymore.' );
insert into mp_label values (21, 0,1004,25, 'This allotement is busy for the category you choose, but there is place left in other categories.' );
insert into mp_label values (22, 0,1004,25, 'The contingent was saved and the category unselected.' );
insert into mp_label values (23, 0,1004,25, 'Warning : found no carrier for this category.  Please check that your data are well defined.' );
insert into mp_label values (24, 0,1004,25, 'There is no client specified on this folder.  Please select one and validate your folder.' );
insert into mp_label values (25, 0,1004,25, 'No allotement is selected.  If you want to use just a supplier information instead of a request, you have to select one allotement.' );
insert into mp_label values (26, 0,1004,25, 'There is no places left for this carrier.  Please Consult planing board to choose another one.' );

/*
* labels used in Marco Polo TO 2000 only !
* 
* Copyright : yafra.org
* Author : Genevieve Rolli
* Creation Date : 01/12/1998
*
* execution steps :
* 1) copy-paste this column "R" in a file "file_name.sql"
* 2) in SQLPlus, execute this file with the command "@file_name.sql"
*/

/* delete old to2000 labels */
delete from mp_label where S_ID =1 ;


insert into mp_label values (0, 0,1,1, 'Reisender' );
insert into mp_label values (1, 0,1,1, 'Geschlecht' );
insert into mp_label values (2, 0,1,1, 'weiblich' );
insert into mp_label values (3, 0,1,1, 'mï¿½nnlich' );
insert into mp_label values (4, 0,1,1, 'Vorname' );
insert into mp_label values (5, 0,1,1, 'Name' );
insert into mp_label values (6, 0,1,1, 'Geburtsdatum' );
insert into mp_label values (7, 0,1,1, 'Sprache' );
insert into mp_label values (8, 0,1,1, 'Interne Bemerkung' );
insert into mp_label values (9, 0,1,1, 'Bemerkung' );
insert into mp_label values (10, 0,1,1, 'Reduktion' );
insert into mp_label values (11, 0,1,1, 'Prioritï¿½t' );
insert into mp_label values (12, 0,1,1, 'Reisendertyp' );
insert into mp_label values (13, 0,1,1, 'Anrede' );
insert into mp_label values (14, 0,1,1, 'Adresse' );
insert into mp_label values (15, 0,1,1, '    ' );
insert into mp_label values (16, 0,1,1, '  ' );
insert into mp_label values (17, 0,1,1, 'PLZ' );
insert into mp_label values (18, 0,1,1, 'Ort' );
insert into mp_label values (19, 0,1,1, 'Land' );
insert into mp_label values (20, 0,1,1, 'Versandart' );
insert into mp_label values (21, 0,1,1, 'Passnummer' );
insert into mp_label values (22, 0,1,1, 'Nationalitï¿½t' );
insert into mp_label values (0, 0,2,1, 'Dossier' );
insert into mp_label values (2, 0,2,1, 'Buchungsnummer' );
insert into mp_label values (3, 0,2,1, 'Buchungsstatus' );
insert into mp_label values (4, 0,2,1, 'Arrangement' );
insert into mp_label values (5, 0,2,1, 'Dienstleistungen' );
insert into mp_label values (6, 0,2,1, 'Gruppe' );
insert into mp_label values (7, 0,2,1, 'Bemerkung' );
insert into mp_label values (8, 0,2,1, 'Rechnungsstelle' );
insert into mp_label values (9, 0,2,1, 'Liefereantenoption' );
insert into mp_label values (10, 0,2,1, 'verfï¿½gare Dienstleistungen um in Buchung hinzuzufï¿½gen' );
insert into mp_label values (11, 0,2,1, 'verfï¿½gare dienstleistungen um aus Buchung zu lï¿½schen' );
insert into mp_label values (12, 0,2,1, 'Kundenoption' );
insert into mp_label values (13, 0,2,1, 'Gruppenrabatt' );
insert into mp_label values (14, 0,2,1, 'Kundenrabatt' );
insert into mp_label values (15, 0,2,1, 'Rabattprozent' );
insert into mp_label values (16, 0,2,1, 'Fixer Rabatt' );
insert into mp_label values (0, 0,3,1, 'Reise' );
insert into mp_label values (2, 0,3,1, 'Reservationsstatus' );
insert into mp_label values (3, 0,3,1, 'Kontingent' );
insert into mp_label values (4, 0,3,1, 'Kategorie' );
insert into mp_label values (5, 0,3,1, 'Upgrade Kategorie' );
insert into mp_label values (6, 0,3,1, 'Datumswahl' );
insert into mp_label values (7, 0,3,1, 'Startdatum' );
insert into mp_label values (8, 0,3,1, 'Enddatum' );
insert into mp_label values (9, 0,3,1, 'Teildienstleistungen' );
insert into mp_label values (10, 0,3,1, 'Dienstleistungstrï¿½ger' );
insert into mp_label values (11, 0,3,1, 'Dienstleistungscode' );
insert into mp_label values (12, 0,3,1, 'Lieferant' );
insert into mp_label values (13, 0,3,1, 'Bemerkung' );
insert into mp_label values (14, 0,3,1, 'Dienstleistungsrabatt' );
insert into mp_label values (15, 0,3,1, 'Angebotsrabatt' );
insert into mp_label values (0, 0,4,1, 'Dienstleistung(en) suchen' );
insert into mp_label values (1, 0,4,1, 'Bezeichnung' );
insert into mp_label values (2, 0,4,1, 'Abreise' );
insert into mp_label values (3, 0,4,1, 'Rï¿½ckkehr' );
insert into mp_label values (4, 0,4,1, 'Startdatum' );
insert into mp_label values (5, 0,4,1, 'Enddatum' );
insert into mp_label values (6, 0,4,1, 'Saison' );
insert into mp_label values (7, 0,4,1, 'Angebotstyp' );
insert into mp_label values (8, 0,4,1, 'Dienstleistung(en) gefunden' );
insert into mp_label values (9, 0,4,1, 'Zu Reisendem hinzufï¿½gen ' );
insert into mp_label values (10, 0,4,1, 'Neue Dienstleistung(en) suchen' );
insert into mp_label values (11, 0,4,1, 'Abbrechen' );
insert into mp_label values (12, 0,4,1, 'Datumstyp' );
insert into mp_label values (13, 0,4,1, 'Suchen' );
insert into mp_label values (14, 0,4,1, 'Erneute Suche' );
insert into mp_label values (15, 0,4,1, 'DL' );
insert into mp_label values (16, 0,4,1, 'Code' );
insert into mp_label values (0, 0,5,1, 'Arrangement suchen' );
insert into mp_label values (1, 0,5,1, 'Bezeichnung' );
insert into mp_label values (2, 0,5,1, 'Abreise' );
insert into mp_label values (3, 0,5,1, 'Rï¿½ckkehr' );
insert into mp_label values (4, 0,5,1, 'Abreisedatum' );
insert into mp_label values (5, 0,5,1, 'Rï¿½ckkehrdatum' );
insert into mp_label values (6, 0,5,1, 'Saison' );
insert into mp_label values (7, 0,5,1, 'Katalog' );
insert into mp_label values (8, 0,5,1, 'Arrangement(s) gefunden' );
insert into mp_label values (9, 0,5,1, 'Arrangement(s) hinzufï¿½gen ...' );
insert into mp_label values (10, 0,5,1, 'Neues Arrangement suchen' );
insert into mp_label values (11, 0,5,1, 'Abbrechen' );
insert into mp_label values (12, 0,5,1, 'Datumstyp' );
insert into mp_label values (13, 0,5,1, 'ARR' );
insert into mp_label values (14, 0,5,1, 'Code' );
insert into mp_label values (0, 0,6,1, 'Reisende(n) suchen' );
insert into mp_label values (1, 0,6,1, 'Vorname' );
insert into mp_label values (2, 0,6,1, 'Name' );
insert into mp_label values (3, 0,6,1, 'Reisendertyp' );
insert into mp_label values (4, 0,6,1, 'Reisende(n) gefunden' );
insert into mp_label values (5, 0,6,1, 'Reisende(n) zum Dossier hinzufï¿½gen' );
insert into mp_label values (6, 0,6,1, 'Neuer Reisender ' );
insert into mp_label values (7, 0,6,1, 'Abbrechen' );
insert into mp_label values (8, 0,6,1, 'Geburtsdatum' );
insert into mp_label values (9, 0,6,1, 'Suchen' );
insert into mp_label values (10, 0,6,1, 'Erneute Suche' );
insert into mp_label values (11, 0,6,1, 'Geschlecht' );
insert into mp_label values (12, 0,6,1, 'Sprache' );
insert into mp_label values (0, 0,7,1, 'Systemeinstellungen' );
insert into mp_label values (1, 0,7,1, 'Passwort ï¿½ndern' );
insert into mp_label values (2, 0,7,1, 'Name' );
insert into mp_label values (3, 0,7,1, 'Altes Passwort' );
insert into mp_label values (4, 0,7,1, 'Neues Passwort' );
insert into mp_label values (5, 0,7,1, 'Bestï¿½tigung' );
insert into mp_label values (6, 0,7,1, 'GUI sprache' );
insert into mp_label values (0, 0,8,1, 'Buchungsfilter' );
insert into mp_label values (1, 0,8,1, 'System Role' );
insert into mp_label values (2, 0,8,1, 'Buchungstelle' );
insert into mp_label values (3, 0,8,1, 'Saison' );
insert into mp_label values (4, 0,8,1, 'Datum von' );
insert into mp_label values (5, 0,8,1, 'bis' );
insert into mp_label values (0, 0,9,1, 'Dossier suchen' );
insert into mp_label values (1, 0,9,1, 'Buchungsnummer' );
insert into mp_label values (2, 0,9,1, 'Buchungsstatus' );
insert into mp_label values (3, 0,9,1, 'Gruppe' );
insert into mp_label values (4, 0,9,1, 'Rechnungsstelle' );
insert into mp_label values (5, 0,9,1, 'Dossier(s) gefunden' );
insert into mp_label values (6, 0,9,1, 'Dossier holen' );
insert into mp_label values (7, 0,9,1, 'Neue Buchung ï¿½ffnen' );
insert into mp_label values (8, 0,9,1, 'Abbrechen' );
insert into mp_label values (9, 0,9,1, 'Suchen' );
insert into mp_label values (10, 0,9,1, 'Neue Suche' );
insert into mp_label values (11, 0,9,1, 'Lieferantoption von' );
insert into mp_label values (12, 0,9,1, 'bis' );
insert into mp_label values (13, 0,9,1, 'Lieferantoption' );
insert into mp_label values (14, 0,9,1, 'Kundenoption von' );
insert into mp_label values (15, 0,9,1, 'bis' );
insert into mp_label values (16, 0,9,1, 'Kundenoption' );
insert into mp_label values (17, 0,9,1, 'Verantwortlicher' );
insert into mp_label values (18, 0,9,1, 'Reisender' );
insert into mp_label values (19, 0,9,1, 'Dienstleistungscode' );
insert into mp_label values (20, 0,9,1, 'Bemerkung' );
insert into mp_label values (0, 0,10,1, 'login' );
insert into mp_label values (3, 0,10,1, 'OK' );
insert into mp_label values (4, 0,10,1, 'Abbrechen' );
insert into mp_label values (0, 0,11,1, 'generelles popup-menu' );
insert into mp_label values (1, 0,11,1, 'Alles speichern' );
insert into mp_label values (2, 0,11,1, 'Hilfe' );
insert into mp_label values (3, 0,11,1, 'Beenden' );
insert into mp_label values (4, 0,11,1, 'Ausschneiden' );
insert into mp_label values (5, 0,11,1, 'Kopieren' );
insert into mp_label values (6, 0,11,1, 'Einfï¿½gen' );
insert into mp_label values (7, 0,11,1, 'ï¿½ber MARCO POLO' );
insert into mp_label values (8, 0,11,1, 'Datei' );
insert into mp_label values (9, 0,11,1, 'Bearbeiten' );
insert into mp_label values (10, 0,11,1, 'Aktionen' );
insert into mp_label values (11, 0,11,1, 'Dossier' );
insert into mp_label values (12, 0,11,1, 'Reisender' );
insert into mp_label values (13, 0,11,1, 'Dienstleistung' );
insert into mp_label values (14, 0,11,1, 'Hilfe' );
insert into mp_label values (0, 0,12,1, 'dossier popup-menu' );
insert into mp_label values (1, 0,12,1, 'Neuer Reisender' );
insert into mp_label values (2, 0,12,1, 'Ganzes Dossier speichern' );
insert into mp_label values (3, 0,12,1, 'Schliessen' );
insert into mp_label values (4, 0,12,1, 'Soll dieses Dossier geschlossen werden?' );
insert into mp_label values (5, 0,12,1, 'Eigenschaften' );
insert into mp_label values (6, 0,12,1, 'Zu Arrangement hinzufï¿½gen' );
insert into mp_label values (7, 0,12,1, 'Aus Arrangement lï¿½schen' );
insert into mp_label values (8, 0,12,1, 'Abbrechen' );
insert into mp_label values (9, 0,12,1, 'Diensleistung aus Arrangement lï¿½schen?' );
insert into mp_label values (10, 0,12,1, 'Lï¿½schen' );
insert into mp_label values (11, 0,12,1, 'Soll dieses Dossier gelï¿½scht werden ?' );
insert into mp_label values (12, 0,12,1, 'Fortschritt' );
insert into mp_label values (13, 0,12,1, 'Fortschritt in Richtung Anfrage' );
insert into mp_label values (14, 0,12,1, 'Fortschritt in Richtung Option' );
insert into mp_label values (15, 0,12,1, 'Alle Buchungsinformationen gesendet' );
insert into mp_label values (16, 0,12,1, 'Hotelbestï¿½tigung an den Kunden gesendet' );
insert into mp_label values (17, 0,12,1, 'ï¿½ndern/Annulieren' );
insert into mp_label values (18, 0,12,1, 'Nur Dossier Details speichern' );
insert into mp_label values (0, 0,13,1, 'Reisender popup-menu' );
insert into mp_label values (1, 0,13,1, 'Neue Dienstleistung' );
insert into mp_label values (2, 0,13,1, 'Speichern' );
insert into mp_label values (3, 0,13,1, 'Lï¿½schen' );
insert into mp_label values (4, 0,13,1, 'Soll dieses Reisender gelï¿½scht werden ?' );
insert into mp_label values (5, 0,13,1, 'Speichern' );
insert into mp_label values (6, 0,13,1, 'Lï¿½schen' );
insert into mp_label values (7, 0,13,1, 'Soll diese Diensleistung gelï¿½scht werden?' );
insert into mp_label values (8, 0,13,1, 'Fortschritt in Richtung ...' );
insert into mp_label values (9, 0,13,1, 'ï¿½ndern/Annulieren ...' );
insert into mp_label values (0, 0,14,1, 'Kunde / Buchungstelle' );
insert into mp_label values (1, 0,14,1, 'Name' );
insert into mp_label values (2, 0,14,1, 'Kundentyp' );
insert into mp_label values (3, 0,14,1, 'Wï¿½hrung' );
insert into mp_label values (4, 0,14,1, 'Sprache' );
insert into mp_label values (5, 0,14,1, 'Konto-Nummer' );
insert into mp_label values (6, 0,14,1, 'Beschreibung' );
insert into mp_label values (7, 0,14,1, 'Adresse' );
insert into mp_label values (8, 0,14,1, ' ' );
insert into mp_label values (9, 0,14,1, ' ' );
insert into mp_label values (10, 0,14,1, 'PLZ' );
insert into mp_label values (11, 0,14,1, 'Ort' );
insert into mp_label values (12, 0,14,1, 'Land' );
insert into mp_label values (13, 0,14,1, 'Versandart' );
insert into mp_label values (14, 0,14,1, 'Telefon' );
insert into mp_label values (15, 0,14,1, 'Fax' );
insert into mp_label values (16, 0,14,1, 'E-Mail' );
insert into mp_label values (17, 0,14,1, 'Internet' );
insert into mp_label values (18, 0,14,1, 'Kunden Code' );
insert into mp_label values (0, 0,15,1, 'Gruppe' );
insert into mp_label values (1, 0,15,1, 'Gruppennummer' );
insert into mp_label values (2, 0,15,1, 'Beschreibung' );
insert into mp_label values (3, 0,15,1, 'Kollektivtyp' );
insert into mp_label values (4, 0,15,1, 'Kunde' );
insert into mp_label values (5, 0,15,1, 'Buchungstelle' );
insert into mp_label values (6, 0,15,1, 'Gruppenleiter' );
insert into mp_label values (7, 0,15,1, 'Beschreibung' );
insert into mp_label values (0, 0,16,1, 'session popup-menu' );
insert into mp_label values (1, 0,16,1, 'Neues Ad-Hoc Dossier' );
insert into mp_label values (2, 0,16,1, 'Neues Arrangement Dossier' );
insert into mp_label values (3, 0,16,1, 'Speichern' );
insert into mp_label values (4, 0,16,1, 'Dossier suchen' );
insert into mp_label values (5, 0,16,1, 'Alle Dossiers schliessen' );
insert into mp_label values (0, 0,17,1, 'session' );
insert into mp_label values (1, 0,17,1, 'Dossier' );
insert into mp_label values (2, 0,17,1, 'Voreinstellungen' );
insert into mp_label values (3, 0,17,1, 'Kunden' );
insert into mp_label values (4, 0,17,1, 'Voreinstellungen fï¿½r' );
insert into mp_label values (5, 0,17,1, 'Werkzeuge fï¿½r' );
insert into mp_label values (6, 0,17,1, 'ï¿½nderungen speichern vor dem Schliessen?' );
insert into mp_label values (0, 0,18,1, 'Kalender' );
insert into mp_label values (1, 0,18,1, 'Januar' );
insert into mp_label values (2, 0,18,1, 'Februar' );
insert into mp_label values (3, 0,18,1, 'Mï¿½rz' );
insert into mp_label values (4, 0,18,1, 'April' );
insert into mp_label values (5, 0,18,1, 'Mai' );
insert into mp_label values (6, 0,18,1, 'Juni' );
insert into mp_label values (7, 0,18,1, 'Juli' );
insert into mp_label values (8, 0,18,1, 'August' );
insert into mp_label values (9, 0,18,1, 'September' );
insert into mp_label values (10, 0,18,1, 'Oktober' );
insert into mp_label values (11, 0,18,1, 'November' );
insert into mp_label values (12, 0,18,1, 'Dezember' );
insert into mp_label values (20, 0,18,1, 'mo' );
insert into mp_label values (21, 0,18,1, 'di' );
insert into mp_label values (22, 0,18,1, 'mi' );
insert into mp_label values (23, 0,18,1, 'do' );
insert into mp_label values (24, 0,18,1, 'fr' );
insert into mp_label values (25, 0,18,1, 'sa' );
insert into mp_label values (26, 0,18,1, 'so' );
insert into mp_label values (0, 0,19,1, 'gruppe popup-menu' );
insert into mp_label values (1, 0,19,1, 'Speichern' );
insert into mp_label values (2, 0,19,1, 'Neue Gruppe' );
insert into mp_label values (3, 0,19,1, 'Lï¿½schen' );
insert into mp_label values (4, 0,19,1, 'Soll diese Gruppe gelï¿½scht werden ?' );
insert into mp_label values (0, 0,20,1, 'kunde popup-menu' );
insert into mp_label values (1, 0,20,1, 'Speichern' );
insert into mp_label values (2, 0,20,1, 'Neue(r) Kunde / Buchungstelle' );
insert into mp_label values (3, 0,20,1, 'Lï¿½schen' );
insert into mp_label values (4, 0,20,1, 'Soll dieser Kunde gelï¿½scht werden ?' );
insert into mp_label values (0, 0,21,1, 'Eigenschaften' );
insert into mp_label values (1, 0,21,1, 'Eigenschaften' );
insert into mp_label values (2, 0,21,1, 'OK' );
insert into mp_label values (3, 0,21,1, 'Eigenschaften vom Dossier' );
insert into mp_label values (0, 0,22,1, 'Aktion popup-menu' );
insert into mp_label values (1, 1,22,1, 'Gesamte Passagierliste' );
insert into mp_label values (1, 2,22,1, 'Reservation Status Kontrolle' );
insert into mp_label values (1, 3,22,1, 'Option Verfall Liste / Lieferant' );
insert into mp_label values (1, 4,22,1, 'Option Verfall Liste / Kunde' );
insert into mp_label values (1, 5,22,1, 'Globaler Umsatz' );
insert into mp_label values (1, 6,22,1, 'Kontingent Kontrolle' );
insert into mp_label values (1, 7,22,1, 'ï¿½berschrittene Kontingente' );
insert into mp_label values (1, 8,22,1, 'Hotel Status Kontrolle' );
insert into mp_label values (1, 9,22,1, 'Rooming Liste' );
insert into mp_label values (1, 10,22,1, 'Planungsboard' );
insert into mp_label values (2, 1,22,1, 'Eigenschaften' );
insert into mp_label values (2, 2,22,1, 'Voucher' );
insert into mp_label values (2, 3,22,1, 'Dossier Umsatz' );
insert into mp_label values (2, 4,22,1, 'Hotel Bestï¿½tigung an Kunde' );
insert into mp_label values (2, 5,22,1, 'Kontingent Info' );
insert into mp_label values (2, 6,22,1, 'Rechnung' );
insert into mp_label values (3, 1,22,1, 'Annulation Anfrage' );
insert into mp_label values (4, 1,22,1, 'Passagierliste' );
insert into mp_label values (4, 2,22,1, 'Request/Anfrage an Supplier' );
insert into mp_label values (4, 3,22,1, 'Voucher' );
insert into mp_label values (4, 4,22,1, 'Booking Information' );
insert into mp_label values (4, 5,22,1, 'Anfrage' );
insert into mp_label values (5, 1,22,1, 'Voucher' );
insert into mp_label values (0, 0,23,1, 'Reports' );
insert into mp_label values (1, 0,23,1, 'Status Kontrolle Report' );
insert into mp_label values (2, 0,23,1, 'Option Verfall Liste / Lieferant' );
insert into mp_label values (3, 0,23,1, 'Option Verfall Liste / Kunde' );
insert into mp_label values (4, 0,23,1, 'Kontingent Kontrolle' );
insert into mp_label values (5, 0,23,1, 'Hotel Status Kontrolle' );
insert into mp_label values (6, 0,23,1, 'Roomingliste' );
insert into mp_label values (7, 0,23,1, 'Planungsboard' );
insert into mp_label values (10, 0,23,1, 'Status von' );
insert into mp_label values (11, 0,23,1, 'Status bis ' );
insert into mp_label values (12, 0,23,1, 'Datum Lieferant  von' );
insert into mp_label values (13, 0,23,1, 'Datum Lieferant bis ' );
insert into mp_label values (14, 0,23,1, 'Datum Kunde von' );
insert into mp_label values (15, 0,23,1, 'Datum Kunde bis ' );
insert into mp_label values (16, 0,23,1, 'Code' );
insert into mp_label values (17, 0,23,1, 'Anfangswoche' );
insert into mp_label values (18, 0,23,1, 'Endwoche' );
insert into mp_label values (20, 0,23,1, 'Report ansehen' );
insert into mp_label values (21, 0,23,1, 'Abbrechen' );
insert into mp_label values (41, 0,23,1, 'Hauptkontingent' );
insert into mp_label values (51, 0,23,1, 'Hotel Code' );
insert into mp_label values (0, 0,24,1, 'Popup-menu Voreinstellungen' );
insert into mp_label values (1, 0,24,1, 'Voreinstellungen speichern' );
insert into mp_label values (0, 0,25,1, 'Assistent' );
insert into mp_label values (1, 0,25,1, '< Zurï¿½ck' );
insert into mp_label values (2, 0,25,1, 'Weiter >' );
insert into mp_label values (3, 0,25,1, 'Abbrechen' );
insert into mp_label values (4, 0,25,1, 'Fertigstellen' );
insert into mp_label values (0, 0,26,1, 'Mapo Assistent' );
insert into mp_label values (1, 0,26,1, 'Buchungassitent pro Agent' );
insert into mp_label values (2, 0,26,1, 'Buchungassitent pro FIT' );
insert into mp_label values (10, 0,26,1, 'Wï¿½hlen Sie einen Agent' );
insert into mp_label values (11, 0,26,1, 'Bitte wï¿½hlen Sie die Suchkriterien' );
insert into mp_label values (12, 0,26,1, 'Wï¿½hlen Sie ein Arrangement' );
insert into mp_label values (13, 0,26,1, 'Gewï¿½hltes Arrangement' );
insert into mp_label values (14, 0,26,1, 'Ihre gewï¿½hlten Dienstleistungen' );
insert into mp_label values (15, 0,26,1, 'Weiteres ARR/DL hinzufï¿½gen' );
insert into mp_label values (16, 0,26,1, 'Keine weiteren ARR/DL' );
insert into mp_label values (17, 0,26,1, 'Reisende eingeben' );
insert into mp_label values (18, 0,26,1, 'Reisenden hinzufï¿½gen' );
insert into mp_label values (19, 0,26,1, 'Reisenden lï¿½schen' );
insert into mp_label values (20, 0,26,1, 'Anzahl PAX' );
insert into mp_label values (21, 0,26,1, 'Code' );
insert into mp_label values (22, 0,26,1, 'Wï¿½hlen Sie eine Dienstleistung' );
insert into mp_label values (23, 0,26,1, 'Zusatzinformation' );
insert into mp_label values (0, 0,27,1, 'MARCO POLO' );
insert into mp_label values (1, 0,27,1, 'OK' );
insert into mp_label values (2, 0,27,1, 'Ja' );
insert into mp_label values (3, 0,27,1, 'Nein' );
insert into mp_label values (4, 0,27,1, 'Abbrechen' );
insert into mp_label values (0, 0,30,1, 'Amexco Import Wizard' );
insert into mp_label values (1, 0,30,1, 'Amexco Import Wizard' );

















insert into mp_label values (0, 0,31,1, 'Amexco Synchronisation Wizard' );
insert into mp_label values (1, 0,31,1, 'Amexco Synchronisation Wizard' );
insert into mp_label values (2, 0,42,1, 'Bitte Kunden auswï¿½hlen. Falls Ihr Kunde nicht in der Liste steht, bitte im Feld Kunde neu erfassen.' );
insert into mp_label values (7, 0,42,1, 'Kann keinen neuen Reisenden erzeugen.' );
insert into mp_label values (1, 0,505,1, 'Fehler' );
insert into mp_label values (2, 0,505,1, 'Das Look and Feel konnte nicht geï¿½ndert werden.' );
insert into mp_label values (3, 0,505,1, 'Der Ordnerstatus kann nicht ermittelt werden.' );
insert into mp_label values (4, 0,505,1, 'Der Servicestatus kann nicht ermittelt werden.' );
insert into mp_label values (1, 0,506,1, 'Fehler' );
insert into mp_label values (2, 0,506,1, 'Es ist ein Fehler beim Laden der Konfigurationsdateien aufgetreten. ' );
insert into mp_label values (3, 0,506,1, 'Die Datei ' );
insert into mp_label values (4, 0,506,1, ' kann nicht gelï¿½scht werden.' );
insert into mp_label values (5, 0,506,1, 'Die Datei kann nicht gelï¿½scht werden.' );
insert into mp_label values (6, 0,506,1, 'Es kann keine neue Buchung erstellt werden.' );
insert into mp_label values (7, 0,506,1, 'Es kann keine neue Arrangementbuchung erstellt werden.' );
insert into mp_label values (8, 0,506,1, 'Validierung nicht mï¿½glich.' );
insert into mp_label values (9, 0,506,1, 'Es kann keine neue Gruppe erstellt werden.' );
insert into mp_label values (10, 0,506,1, 'Es kann kein neuer Client erstellt werden.' );
insert into mp_label values (11, 0,506,1, 'Der Eingabedialog kann nicht geï¿½ffnet werden.' );
insert into mp_label values (12, 0,506,1, 'Es kann kein neues Arrangement erstellt werden.' );
insert into mp_label values (13, 0,506,1, 'Der Client kann nicht entfernt werden.' );
insert into mp_label values (14, 0,506,1, 'Die Gruppe kann nicht entfernt werden.' );
insert into mp_label values (15, 0,506,1, 'Der Ordner kann nicht entfernt werden.' );
insert into mp_label values (16, 0,506,1, 'Der Reisende kann nicht enfernt werden.' );
insert into mp_label values (17, 0,506,1, 'Der Service kann nicht entfernt werden.' );
insert into mp_label values (18, 0,506,1, 'Der Status konnte nicht gelesen werden.' );
insert into mp_label values (19, 0,506,1, 'Ser Status konnte nicht gesetzt werden.' );
insert into mp_label values (20, 0,506,1, 'Unerwarteter CORBA Fehler.' );
insert into mp_label values (21, 0,506,1, 'Der Report kann nicht erstellt werden.' );
insert into mp_label values (22, 0,506,1, 'Fehler beim ï¿½ffnen der Hilfedatei. ' );
insert into mp_label values (23, 0,506,1, 'Acrobat Reader kann nicht gestartet werden.' );
insert into mp_label values (24, 0,506,1, ' Gruppe ' );
insert into mp_label values (25, 0,506,1, '  kann nicht gefunden werden.' );
insert into mp_label values (26, 0,506,1, 'Client  ' );
insert into mp_label values (27, 0,506,1, ' kann nicht gefunden werden.' );
insert into mp_label values (28, 0,506,1, 'Client  ' );
insert into mp_label values (29, 0,506,1, ' kann nichtgefunden werden.' );
insert into mp_label values (0, 0,1001,1, 'Session Warnmeldung ' );
insert into mp_label values (1, 0,1001,1, 'Dieses Dossier wird gerade von einem anderen Benutzer bearbeitet.' );
insert into mp_label values (0, 0,1002,1, 'Dossier Warnmeldung ' );
insert into mp_label values (1, 0,1002,1, 'Dossier' );
insert into mp_label values (2, 0,1002,1, 'Bitte Kunden auswï¿½hlen.  Falls Ihr Kunde nicht in der Liste steht, bitte im Feld ""Kunde"" neu erfassen.' );
insert into mp_label values (3, 0,1002,1, 'Bitte Menge eingeben :' );
insert into mp_label values (4, 0,1002,1, 'Bestï¿½tigung wurde nicht geschickt, weil kein Mailempfï¿½nger gefunden wurde.  Geben Sie eine Adresse ein oder schicken Sie die Bestï¿½tigung manuell.' );
insert into mp_label values (5, 0,1002,1, 'Bestï¿½tigung wurde nicht geschickt - Mail-Problem.  Falls dieser Fehler fortbesteht, bitte beim Systemadministrator melden.' );
insert into mp_label values (6, 0,1002,1, 'Bestï¿½tigung wurde wegen eines unbekannten Problems nicht geschickt.  Bitte prï¿½fen Sie Ihre Daten/Systemeinstellungen oder schicken Sie die Bestï¿½tigung manuell.' );
insert into mp_label values (7, 0,1002,1, 'Kann keinen neuen Reisenden erzeugen.' );
insert into mp_label values (0, 0,1003,1, 'Reisender Warnmeldung ' );
insert into mp_label values (0, 0,1004,1, 'Reservierung Warnmeldung ' );
insert into mp_label values (1, 0,1004,1, 'Dossier' );
insert into mp_label values (2, 0,1004,1, ', Reisender ' );
insert into mp_label values (3, 0,1004,1, ', Reise Nummer' );
insert into mp_label values (4, 0,1004,1, 'Es ist nicht mï¿½glich alle Teildienstleistungen zu lï¿½schen. Die vorherigen Teildienstleistungen wurden beibehalten.' );
insert into mp_label values (5, 0,1004,1, 'Kontingent kann nur im Anfragestatus geï¿½ndert werden. Rechte-Maustaste drï¿½cken und Aendern/Annulieren Funktion auswï¿½hlen.' );
insert into mp_label values (6, 0,1004,1, 'Kategorie kann nur im ""Anfrage""-status geï¿½ndert werden. Mit der rechten Maustaste Aendern/Annulieren Funktion auswï¿½hlen.' );
insert into mp_label values (7, 0,1004,1, 'Diensttrï¿½ger kann nur im ""Anfrage""-status geï¿½ndert werden. Mit der rechten Maustaste Aendern/Annulieren Funktion auswï¿½hlen.' );
insert into mp_label values (8, 0,1004,1, 'Startdatum kann nur im ""Anfrage""-status geï¿½ndert werden. Mit der rechten Maustaste Aendern/Annulieren Funktion auswï¿½hlen.' );
insert into mp_label values (9, 0,1004,1, 'Enddatum kann nur im ""Anfrage""-status geï¿½ndert werden. Mit der rechten Maustaste Aendern/Annulieren Funktion auswï¿½hlen.' );
insert into mp_label values (10, 0,1004,1, 'Keine Datumsï¿½nderung in statistischer Dienstleistung mï¿½glich.' );
insert into mp_label values (11, 0,1004,1, 'Bitte wï¿½hlen Sie eine Kategorie aus.' );
insert into mp_label values (12, 0,1004,1, 'Keine Details im ausgewï¿½hlten Kontingent definiert.' );
insert into mp_label values (13, 0,1004,1, 'Die vorherigen Daten wurden beibehalten.' );
insert into mp_label values (14, 0,1004,1, 'Nur Kategorie wurde gespeichert, Kontingent wurde nicht ausgewï¿½hlt.' );
insert into mp_label values (15, 0,1004,1, 'Dieses Kontingent ist bald ausgeschï¿½pft. Bitte Lieferant um Kontingenterweiterung bitten.' );
insert into mp_label values (16, 0,1004,1, 'Es verbleibt' );
insert into mp_label values (17, 0,1004,1, 'Nach dieser Buchung noch verfï¿½gbar:' );
insert into mp_label values (18, 0,1004,1, 'Nach Buchung dieser Dienstleistung verbleiben noch:' );
insert into mp_label values (19, 0,1004,1, 'Platz("e) im gesammten Kontingent ' );
insert into mp_label values (20, 0,1004,1, 'Kontingent ist ausgeschï¿½pft -
es ist keine Buchung mehr mï¿½glich.' );
insert into mp_label values (21, 0,1004,1, 'Das Kontingent fï¿½r diese Kategorie ist ausgeschï¿½pft. 
Es gibt jedoch noch freie Plï¿½tze in einer anderen Kategorie.' );
insert into mp_label values (22, 0,1004,1, 'Das Kontingent wurde gespeichert. 
Die Kategorie wurde nicht ausgewï¿½hlt.' );
insert into mp_label values (23, 0,1004,1, 'Warnmeldung : Es wurde kein Trï¿½ger fï¿½r diese Kategorie gefunden.
Bitte prï¿½fen Sie, ob Ihre Daten korrekt definiert sind. ' );
insert into mp_label values (24, 0,1004,1, 'Es gibt keine Rechnungstelle fï¿½r dieses Dossier, 
bitte wï¿½hlen Sie eine aus und speichern Sie das Dossier.' );
insert into mp_label values (25, 0,1004,1, 'Es wurde kein Kontingent ausgewï¿½hlt.
Wenn Sie eine Lieferanteninformation benï¿½tigen, 
wï¿½hlen Sie bitte ein Kontingent aus.' );
insert into mp_label values (26, 0,1004,1, 'Es gibt kein Platz mehr fï¿½r diesen Dienstleistungstrï¿½ger. 
Bitte wï¿½hlen Sie einen anderen Diensleistungstrï¿½ger mit 
dem Planungsboard.' );


