/* created by excel sheet with copy paste ! */
/* update before you run it !! */
/* first copy paste row "J", "K" and "L" to this file */


delete from sprachen;
commit work;



insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (1, 1, 1, 'ge', 1, 1 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (2, 2, 0, 'aa', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (3, 3, 0, 'ab', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (4, 4, 0, 'af', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (5, 5, 0, 'am', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (6, 6, 0, 'ar', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (7, 7, 0, 'as', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (8, 8, 0, 'ay', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (9, 9, 0, 'az', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (10, 10, 0, 'ba', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (11, 11, 0, 'be', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (12, 12, 0, 'bg', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (13, 13, 0, 'bh', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (14, 14, 0, 'bi', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (15, 15, 0, 'bn', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (16, 16, 0, 'bo', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (17, 17, 0, 'br', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (18, 18, 0, 'ca', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (19, 19, 0, 'co', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (20, 20, 0, 'cs', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (21, 21, 0, 'cy', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (22, 22, 0, 'da', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (23, 23, 0, 'dz', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (24, 24, 0, 'el', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (25, 25, 0, 'en', 0, 1 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (26, 26, 0, 'eo', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (27, 27, 0, 'es', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (28, 28, 0, 'et', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (29, 29, 0, 'eu', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (30, 30, 0, 'fa', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (31, 31, 0, 'fi', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (32, 32, 0, 'fj', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (33, 33, 0, 'fo', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (34, 34, 0, 'fr', 0, 1 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (35, 35, 0, 'fy', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (36, 36, 0, 'ga', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (37, 37, 0, 'gd', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (38, 38, 0, 'gl', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (39, 39, 0, 'gn', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (40, 40, 0, 'gu', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (41, 41, 0, 'ha', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (42, 42, 0, 'iw', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (43, 43, 0, 'he', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (44, 44, 0, 'hi', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (45, 45, 0, 'hr', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (46, 46, 0, 'hu', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (47, 47, 0, 'hy', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (48, 48, 0, 'ia', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (49, 49, 0, 'in', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (50, 50, 0, 'id', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (51, 51, 0, 'ie', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (52, 52, 0, 'ik', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (53, 53, 0, 'is', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (54, 54, 0, 'it', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (55, 55, 0, 'ja', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (56, 56, 0, 'jw', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (57, 57, 0, 'ka', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (58, 58, 0, 'kk', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (59, 59, 0, 'kl', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (60, 60, 0, 'km', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (61, 61, 0, 'kn', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (62, 62, 0, 'ko', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (63, 63, 0, 'ks', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (64, 64, 0, 'ku', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (65, 65, 0, 'ky', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (66, 66, 0, 'la', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (67, 67, 0, 'ln', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (68, 68, 0, 'lo', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (69, 69, 0, 'lt', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (70, 70, 0, 'lv', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (71, 71, 0, 'mg', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (72, 72, 0, 'mi', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (73, 73, 0, 'mk', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (74, 74, 0, 'ml', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (75, 75, 0, 'mn', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (76, 76, 0, 'mo', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (77, 77, 0, 'mr', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (78, 78, 0, 'ms', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (79, 79, 0, 'mt', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (80, 80, 0, 'my', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (81, 81, 0, 'na', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (82, 82, 0, 'ne', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (83, 83, 0, 'nl', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (84, 84, 0, 'no', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (85, 85, 0, 'oc', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (86, 86, 0, 'om', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (87, 87, 0, 'or', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (88, 88, 0, 'pa', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (89, 89, 0, 'pl', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (90, 90, 0, 'ps', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (91, 91, 0, 'pt', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (92, 92, 0, 'qu', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (93, 93, 0, 'rm', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (94, 94, 0, 'rn', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (95, 95, 0, 'ro', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (96, 96, 0, 'ru', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (97, 97, 0, 'rw', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (98, 98, 0, 'sa', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (99, 99, 0, 'sd', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (100, 100, 0, 'sg', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (101, 101, 0, 'sh', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (102, 102, 0, 'si', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (103, 103, 0, 'sk', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (104, 104, 0, 'sl', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (105, 105, 0, 'sm', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (106, 106, 0, 'sn', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (107, 107, 0, 'so', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (108, 108, 0, 'sq', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (109, 109, 0, 'sr', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (110, 110, 0, 'ss', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (111, 111, 0, 'st', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (112, 112, 0, 'su', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (113, 113, 0, 'sv', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (114, 114, 0, 'sw', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (115, 115, 0, 'ta', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (116, 116, 0, 'te', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (117, 117, 0, 'tg', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (118, 118, 0, 'th', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (119, 119, 0, 'ti', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (120, 120, 0, 'tk', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (121, 121, 0, 'tl', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (122, 122, 0, 'tn', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (123, 123, 0, 'to', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (124, 124, 0, 'tr', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (125, 125, 0, 'ts', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (126, 126, 0, 'tt', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (127, 127, 0, 'tw', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (128, 128, 0, 'uk', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (129, 129, 0, 'ur', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (130, 130, 0, 'uz', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (131, 131, 0, 'vi', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (132, 132, 0, 'vo', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (133, 133, 0, 'wo', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (134, 134, 0, 'xh', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (135, 135, 0, 'yi', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (136, 136, 0, 'ji', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (137, 137, 0, 'yo', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (138, 138, 0, 'zh', 0, 0 );
insert into sprachen (S_ID, BEZ_ID, DIALOG, SYSBEZ, OUTPUT, GUI) values (139, 139, 0, 'zu', 0, 0 );



delete from bezeichnung where TYP = 1;

insert into bezeichnung values (-1, 25, 'n/a', 1);
insert into bezeichnung values (0, 25, 'Languages', 1);
insert into bezeichnung values (1, 25, 'German', 1);
insert into bezeichnung values (2, 25, 'Afar', 1);
insert into bezeichnung values (3, 25, 'Abkhazian', 1);
insert into bezeichnung values (4, 25, 'Afrikaans', 1);
insert into bezeichnung values (5, 25, 'Amharic', 1);
insert into bezeichnung values (6, 25, 'Arabic', 1);
insert into bezeichnung values (7, 25, 'Assamese', 1);
insert into bezeichnung values (8, 25, 'Aymara', 1);
insert into bezeichnung values (9, 25, 'Azerbaijani', 1);
insert into bezeichnung values (10, 25, 'Bashkir', 1);
insert into bezeichnung values (11, 25, 'Byelorussian', 1);
insert into bezeichnung values (12, 25, 'Bulgarian', 1);
insert into bezeichnung values (13, 25, 'Bihari', 1);
insert into bezeichnung values (14, 25, 'Bislama', 1);
insert into bezeichnung values (15, 25, 'Bengali', 1);
insert into bezeichnung values (16, 25, 'Tibetan', 1);
insert into bezeichnung values (17, 25, 'Breton', 1);
insert into bezeichnung values (18, 25, 'Catalan', 1);
insert into bezeichnung values (19, 25, 'Corsican', 1);
insert into bezeichnung values (20, 25, 'Czech', 1);
insert into bezeichnung values (21, 25, 'Welsh', 1);
insert into bezeichnung values (22, 25, 'Danish', 1);
insert into bezeichnung values (23, 25, 'Bhutani', 1);
insert into bezeichnung values (24, 25, 'Greek', 1);
insert into bezeichnung values (25, 25, 'English', 1);
insert into bezeichnung values (26, 25, 'Esperanto', 1);
insert into bezeichnung values (27, 25, 'Spanish', 1);
insert into bezeichnung values (28, 25, 'Estonian', 1);
insert into bezeichnung values (29, 25, 'Basque', 1);
insert into bezeichnung values (30, 25, 'Persian', 1);
insert into bezeichnung values (31, 25, 'Finnish', 1);
insert into bezeichnung values (32, 25, 'Fiji', 1);
insert into bezeichnung values (33, 25, 'Faeroese', 1);
insert into bezeichnung values (34, 25, 'French', 1);
insert into bezeichnung values (35, 25, 'Frisian', 1);
insert into bezeichnung values (36, 25, 'Irish', 1);
insert into bezeichnung values (37, 25, 'Scots Gaelic', 1);
insert into bezeichnung values (38, 25, 'Galician', 1);
insert into bezeichnung values (39, 25, 'Guarani', 1);
insert into bezeichnung values (40, 25, 'Gujarati', 1);
insert into bezeichnung values (41, 25, 'Hausa', 1);
insert into bezeichnung values (42, 25, 'Hebrew', 1);
insert into bezeichnung values (43, 25, 'Hebrew', 1);
insert into bezeichnung values (44, 25, 'Hindi', 1);
insert into bezeichnung values (45, 25, 'Croatian', 1);
insert into bezeichnung values (46, 25, 'Hungarian', 1);
insert into bezeichnung values (47, 25, 'Armenian', 1);
insert into bezeichnung values (48, 25, 'Interlingua', 1);
insert into bezeichnung values (49, 25, 'Indonesian', 1);
insert into bezeichnung values (50, 25, 'Indonesian', 1);
insert into bezeichnung values (51, 25, 'Interlingue', 1);
insert into bezeichnung values (52, 25, 'Inupiak', 1);
insert into bezeichnung values (53, 25, 'Icelandic', 1);
insert into bezeichnung values (54, 25, 'Italian', 1);
insert into bezeichnung values (55, 25, 'Japanese', 1);
insert into bezeichnung values (56, 25, 'Javanese', 1);
insert into bezeichnung values (57, 25, 'Georgian', 1);
insert into bezeichnung values (58, 25, 'Kazakh', 1);
insert into bezeichnung values (59, 25, 'Greenlandic', 1);
insert into bezeichnung values (60, 25, 'Cambodian', 1);
insert into bezeichnung values (61, 25, 'Kannada', 1);
insert into bezeichnung values (62, 25, 'Korean', 1);
insert into bezeichnung values (63, 25, 'Kashmiri', 1);
insert into bezeichnung values (64, 25, 'Kurdish', 1);
insert into bezeichnung values (65, 25, 'Kirghiz', 1);
insert into bezeichnung values (66, 25, 'Latin', 1);
insert into bezeichnung values (67, 25, 'Lingala', 1);
insert into bezeichnung values (68, 25, 'Laothian', 1);
insert into bezeichnung values (69, 25, 'Lithuanian', 1);
insert into bezeichnung values (70, 25, 'Latvian', 1);
insert into bezeichnung values (71, 25, 'Malagasy', 1);
insert into bezeichnung values (72, 25, 'Maori', 1);
insert into bezeichnung values (73, 25, 'Macedonian', 1);
insert into bezeichnung values (74, 25, 'Malayalam', 1);
insert into bezeichnung values (75, 25, 'Mongolian', 1);
insert into bezeichnung values (76, 25, 'Moldavian', 1);
insert into bezeichnung values (77, 25, 'Marathi', 1);
insert into bezeichnung values (78, 25, 'Malay', 1);
insert into bezeichnung values (79, 25, 'Maltese', 1);
insert into bezeichnung values (80, 25, 'Burmese', 1);
insert into bezeichnung values (81, 25, 'Nauru', 1);
insert into bezeichnung values (82, 25, 'Nepali', 1);
insert into bezeichnung values (83, 25, 'Dutch', 1);
insert into bezeichnung values (84, 25, 'Norwegian', 1);
insert into bezeichnung values (85, 25, 'Occitan', 1);
insert into bezeichnung values (86, 25, 'Oromo', 1);
insert into bezeichnung values (87, 25, 'Oriya', 1);
insert into bezeichnung values (88, 25, 'Punjabi', 1);
insert into bezeichnung values (89, 25, 'Polish', 1);
insert into bezeichnung values (90, 25, 'Pashto', 1);
insert into bezeichnung values (91, 25, 'Portuguese', 1);
insert into bezeichnung values (92, 25, 'Quechua', 1);
insert into bezeichnung values (93, 25, 'Rhaeto-Romance', 1);
insert into bezeichnung values (94, 25, 'Kirundi', 1);
insert into bezeichnung values (95, 25, 'Romanian', 1);
insert into bezeichnung values (96, 25, 'Russian', 1);
insert into bezeichnung values (97, 25, 'Kinyarwanda', 1);
insert into bezeichnung values (98, 25, 'Sanskrit', 1);
insert into bezeichnung values (99, 25, 'Sindhi', 1);
insert into bezeichnung values (100, 25, 'Sangro', 1);
insert into bezeichnung values (101, 25, 'Serbo-Croatian', 1);
insert into bezeichnung values (102, 25, 'Singhalese', 1);
insert into bezeichnung values (103, 25, 'Slovak', 1);
insert into bezeichnung values (104, 25, 'Slovenian', 1);
insert into bezeichnung values (105, 25, 'Samoan', 1);
insert into bezeichnung values (106, 25, 'Shona', 1);
insert into bezeichnung values (107, 25, 'Somali', 1);
insert into bezeichnung values (108, 25, 'Albanian', 1);
insert into bezeichnung values (109, 25, 'Serbian', 1);
insert into bezeichnung values (110, 25, 'Siswati', 1);
insert into bezeichnung values (111, 25, 'Sesotho', 1);
insert into bezeichnung values (112, 25, 'Sundanese', 1);
insert into bezeichnung values (113, 25, 'Swedish', 1);
insert into bezeichnung values (114, 25, 'Swahili', 1);
insert into bezeichnung values (115, 25, 'Tamil', 1);
insert into bezeichnung values (116, 25, 'Tegulu', 1);
insert into bezeichnung values (117, 25, 'Tajik', 1);
insert into bezeichnung values (118, 25, 'Thai', 1);
insert into bezeichnung values (119, 25, 'Tigrinya', 1);
insert into bezeichnung values (120, 25, 'Turkmen', 1);
insert into bezeichnung values (121, 25, 'Tagalog', 1);
insert into bezeichnung values (122, 25, 'Setswana', 1);
insert into bezeichnung values (123, 25, 'Tonga', 1);
insert into bezeichnung values (124, 25, 'Turkish', 1);
insert into bezeichnung values (125, 25, 'Tsonga', 1);
insert into bezeichnung values (126, 25, 'Tatar', 1);
insert into bezeichnung values (127, 25, 'Twi', 1);
insert into bezeichnung values (128, 25, 'Ukrainian', 1);
insert into bezeichnung values (129, 25, 'Urdu', 1);
insert into bezeichnung values (130, 25, 'Uzbek', 1);
insert into bezeichnung values (131, 25, 'Vietnamese', 1);
insert into bezeichnung values (132, 25, 'Volapuk', 1);
insert into bezeichnung values (133, 25, 'Wolof', 1);
insert into bezeichnung values (134, 25, 'Xhosa', 1);
insert into bezeichnung values (135, 25, 'Yiddish', 1);
insert into bezeichnung values (136, 25, 'Yiddish', 1);
insert into bezeichnung values (137, 25, 'Yoruba', 1);
insert into bezeichnung values (138, 25, 'Chinese', 1);
insert into bezeichnung values (139, 25, 'Zulu', 1);


insert into bezeichnung values (-1, 1, 'n/a', 1);
insert into bezeichnung values (0, 1, 'Sprachen', 1);
insert into bezeichnung values (1, 1, 'Deutsch', 1);
insert into bezeichnung values (2, 1, 'Afar', 1);
insert into bezeichnung values (3, 1, 'Abchasisch', 1);
insert into bezeichnung values (4, 1, 'Afrikaans', 1);
insert into bezeichnung values (5, 1, 'Amharisch', 1);
insert into bezeichnung values (6, 1, 'Arabisch', 1);
insert into bezeichnung values (7, 1, 'Assamesisch', 1);
insert into bezeichnung values (8, 1, 'Aymara', 1);
insert into bezeichnung values (9, 1, 'Aserbaidschanisch', 1);
insert into bezeichnung values (10, 1, 'Baschkirisch', 1);
insert into bezeichnung values (11, 1, 'Belorussisch', 1);
insert into bezeichnung values (12, 1, 'Bulgarisch', 1);
insert into bezeichnung values (13, 1, 'Biharisch', 1);
insert into bezeichnung values (14, 1, 'Bislamisch', 1);
insert into bezeichnung values (15, 1, 'Bengalisch', 1);
insert into bezeichnung values (16, 1, 'Tibetanisch', 1);
insert into bezeichnung values (17, 1, 'Bretonisch', 1);
insert into bezeichnung values (18, 1, 'Katalanisch', 1);
insert into bezeichnung values (19, 1, 'Korsisch', 1);
insert into bezeichnung values (20, 1, 'Tschechisch', 1);
insert into bezeichnung values (21, 1, 'Walisisch', 1);
insert into bezeichnung values (22, 1, 'Dänisch', 1);
insert into bezeichnung values (23, 1, 'Bhutani', 1);
insert into bezeichnung values (24, 1, 'Griechisch', 1);
insert into bezeichnung values (25, 1, 'Englisch', 1);
insert into bezeichnung values (26, 1, 'Esperanto', 1);
insert into bezeichnung values (27, 1, 'Spanisch', 1);
insert into bezeichnung values (28, 1, 'Estnisch', 1);
insert into bezeichnung values (29, 1, 'Baskisch', 1);
insert into bezeichnung values (30, 1, 'Persisch', 1);
insert into bezeichnung values (31, 1, 'Finnisch', 1);
insert into bezeichnung values (32, 1, 'Fiji', 1);
insert into bezeichnung values (33, 1, 'Faröisch', 1);
insert into bezeichnung values (34, 1, 'Französisch', 1);
insert into bezeichnung values (35, 1, 'Friesisch', 1);
insert into bezeichnung values (36, 1, 'Irisch', 1);
insert into bezeichnung values (37, 1, 'Schottisches Gälisch', 1);
insert into bezeichnung values (38, 1, 'Galizisch', 1);
insert into bezeichnung values (39, 1, 'Guarani', 1);
insert into bezeichnung values (40, 1, 'Gujaratisch', 1);
insert into bezeichnung values (41, 1, 'Haussa', 1);
insert into bezeichnung values (42, 1, 'Hebräisch', 1);
insert into bezeichnung values (43, 1, 'Hebräisch', 1);
insert into bezeichnung values (44, 1, 'Hindi', 1);
insert into bezeichnung values (45, 1, 'Kroatisch', 1);
insert into bezeichnung values (46, 1, 'Ungarisch', 1);
insert into bezeichnung values (47, 1, 'Armenisch', 1);
insert into bezeichnung values (48, 1, 'Interlingua', 1);
insert into bezeichnung values (49, 1, 'Indonesisch', 1);
insert into bezeichnung values (50, 1, 'Indonesisch', 1);
insert into bezeichnung values (51, 1, 'Interlingue', 1);
insert into bezeichnung values (52, 1, 'Inupiak', 1);
insert into bezeichnung values (53, 1, 'Isländisch', 1);
insert into bezeichnung values (54, 1, 'Italienisch', 1);
insert into bezeichnung values (55, 1, 'Japanisch', 1);
insert into bezeichnung values (56, 1, 'Javanisch', 1);
insert into bezeichnung values (57, 1, 'Georgisch', 1);
insert into bezeichnung values (58, 1, 'Kasachisch', 1);
insert into bezeichnung values (59, 1, 'Grönländisch', 1);
insert into bezeichnung values (60, 1, 'Kambodschanisch', 1);
insert into bezeichnung values (61, 1, 'Kannada', 1);
insert into bezeichnung values (62, 1, 'Koreanisch', 1);
insert into bezeichnung values (63, 1, 'Kaschmirisch', 1);
insert into bezeichnung values (64, 1, 'Kurdisch', 1);
insert into bezeichnung values (65, 1, 'Kirgisisch', 1);
insert into bezeichnung values (66, 1, 'Lateinisch', 1);
insert into bezeichnung values (67, 1, 'Lingalisch', 1);
insert into bezeichnung values (68, 1, 'Laotisch', 1);
insert into bezeichnung values (69, 1, 'Litauisch', 1);
insert into bezeichnung values (70, 1, 'Lettisch', 1);
insert into bezeichnung values (71, 1, 'Malagasisch', 1);
insert into bezeichnung values (72, 1, 'Maorisch', 1);
insert into bezeichnung values (73, 1, 'Mazedonisch', 1);
insert into bezeichnung values (74, 1, 'Malajalam', 1);
insert into bezeichnung values (75, 1, 'Mongolisch', 1);
insert into bezeichnung values (76, 1, 'Moldavisch', 1);
insert into bezeichnung values (77, 1, 'Marathi', 1);
insert into bezeichnung values (78, 1, 'Malaysisch', 1);
insert into bezeichnung values (79, 1, 'Maltesisch', 1);
insert into bezeichnung values (80, 1, 'Burmesisch', 1);
insert into bezeichnung values (81, 1, 'Nauruisch', 1);
insert into bezeichnung values (82, 1, 'Nepalisch', 1);
insert into bezeichnung values (83, 1, 'Holländisch', 1);
insert into bezeichnung values (84, 1, 'Norwegisch', 1);
insert into bezeichnung values (85, 1, 'Okzitanisch', 1);
insert into bezeichnung values (86, 1, 'Oromo', 1);
insert into bezeichnung values (87, 1, 'Orija', 1);
insert into bezeichnung values (88, 1, 'Pundjabisch', 1);
insert into bezeichnung values (89, 1, 'Polnisch', 1);
insert into bezeichnung values (90, 1, 'Paschtu', 1);
insert into bezeichnung values (91, 1, 'Portugiesisch', 1);
insert into bezeichnung values (92, 1, 'Quechua', 1);
insert into bezeichnung values (93, 1, 'Rätoromanisch', 1);
insert into bezeichnung values (94, 1, 'Kirundisch', 1);
insert into bezeichnung values (95, 1, 'Rumänisch', 1);
insert into bezeichnung values (96, 1, 'Russisch', 1);
insert into bezeichnung values (97, 1, 'Kijarwanda', 1);
insert into bezeichnung values (98, 1, 'Sanskrit', 1);
insert into bezeichnung values (99, 1, 'Zinti', 1);
insert into bezeichnung values (100, 1, 'Sango', 1);
insert into bezeichnung values (101, 1, 'Serbokroatisch', 1);
insert into bezeichnung values (102, 1, 'Singhalesisch', 1);
insert into bezeichnung values (103, 1, 'Slowakisch', 1);
insert into bezeichnung values (104, 1, 'Slowenisch', 1);
insert into bezeichnung values (105, 1, 'Samoanisch', 1);
insert into bezeichnung values (106, 1, 'Schonisch', 1);
insert into bezeichnung values (107, 1, 'Somalisch', 1);
insert into bezeichnung values (108, 1, 'Albanisch', 1);
insert into bezeichnung values (109, 1, 'Serbisch', 1);
insert into bezeichnung values (110, 1, 'Swasiländisch', 1);
insert into bezeichnung values (111, 1, 'Sesothisch', 1);
insert into bezeichnung values (112, 1, 'Sudanesisch', 1);
insert into bezeichnung values (113, 1, 'Schwedisch', 1);
insert into bezeichnung values (114, 1, 'Suaheli', 1);
insert into bezeichnung values (115, 1, 'Tamilisch', 1);
insert into bezeichnung values (116, 1, 'Telugu', 1);
insert into bezeichnung values (117, 1, 'Tadschikisch', 1);
insert into bezeichnung values (118, 1, 'Thai', 1);
insert into bezeichnung values (119, 1, 'Tigrinja', 1);
insert into bezeichnung values (120, 1, 'Turkmenisch', 1);
insert into bezeichnung values (121, 1, 'Tagalog', 1);
insert into bezeichnung values (122, 1, 'Sezuan', 1);
insert into bezeichnung values (123, 1, 'Tongaisch', 1);
insert into bezeichnung values (124, 1, 'Türkisch', 1);
insert into bezeichnung values (125, 1, 'Tsongaisch', 1);
insert into bezeichnung values (126, 1, 'Tatarisch', 1);
insert into bezeichnung values (127, 1, 'Twi', 1);
insert into bezeichnung values (128, 1, 'Ukrainisch', 1);
insert into bezeichnung values (129, 1, 'Urdu', 1);
insert into bezeichnung values (130, 1, 'Usbekisch', 1);
insert into bezeichnung values (131, 1, 'Vietnamesisch', 1);
insert into bezeichnung values (132, 1, 'Volapük', 1);
insert into bezeichnung values (133, 1, 'Wolof', 1);
insert into bezeichnung values (134, 1, 'Xhosa', 1);
insert into bezeichnung values (135, 1, 'Jiddish', 1);
insert into bezeichnung values (136, 1, 'Jiddish', 1);
insert into bezeichnung values (137, 1, 'Joruba', 1);
insert into bezeichnung values (138, 1, 'Chinesisch', 1);
insert into bezeichnung values (139, 1, 'Zulu', 1);

