insert into label values (180, 0, 0, 0, 1, 'travelDB - Graphik                     ');
insert into label values (180, 0, 1, 0, 1, 'Graphik                                  ');
insert into label values (180, 0, 2, 0, 1, 'Datei:                                   ');
insert into label values (180, 0, 3, 0, 1, 'Dialogfenster                            ');
insert into label values (180, 0, 4, 0, 1, 'Ende                                     ');
insert into label values (180, 0, 5, 0, 1, 'Buchungsfenster                          ');
insert into label values (180, 0, 6, 0, 1, 'Dienstleistungstraeger                   ');
insert into label values (180, 0, 7, 0, 1, 'Dateiauswahl                             ');
insert into label values (180, 0, 8, 0, 1, 'Palette                                  ');
insert into label values (180, 0, 9, 0, 1, ' Region:                                 ');
insert into label values (180, 0, 10, 0, 1, 'Graphik Buchung                          ');
insert into label values (180, 1, 0, 0, 1, 'Font                                     ');
insert into label values (180, 1, 1, 0, 1, 'Farbe                                    ');
insert into label values (180, 1, 2, 0, 1, 'Breite                                   ');
insert into label values (180, 1, 3, 0, 1, 'Muster                                   ');
insert into label values (180, 1, 4, 0, 1, 'Stil                                     ');
insert into label values (180, 1, 5, 0, 1, 'Snap                                     ');
insert into label values (180, 2, 0, 0, 1, 'Datei                                    ');
insert into label values (180, 2, 1, 0, 1, 'Import ...                               ');
insert into label values (180, 2, 2, 0, 1, 'Export                                   ');
insert into label values (180, 2, 3, 0, 1, 'Export als ...                           ');
insert into label values (180, 2, 4, 0, 1, 'Graphik loeschen                         ');
insert into label values (180, 2, 5, 0, 1, 'Abbrechen                                ');
insert into label values (180, 2, 6, 0, 1, 'Ende                                     ');
insert into label values (180, 3, 0, 0, 1, 'Erzeugen                                 ');
insert into label values (180, 3, 1, 0, 1, 'Text                                     ');
insert into label values (180, 3, 2, 0, 1, 'Punkt                                    ');
insert into label values (180, 3, 3, 0, 1, 'Vektor                                   ');
insert into label values (180, 3, 4, 0, 1, 'Rechteck                                 ');
insert into label values (180, 3, 5, 0, 1, 'Kreis                                    ');
insert into label values (180, 3, 6, 0, 1, 'Kreisbogen                               ');
insert into label values (180, 3, 7, 0, 1, 'Ellipse                                  ');
insert into label values (180, 3, 8, 0, 1, 'schraffiertes Rechteck                   ');
insert into label values (180, 3, 9, 0, 1, 'schraffierter Kreis                      ');
insert into label values (180, 3, 10, 0, 1, 'schraffierter Kreisbogen                 ');
insert into label values (180, 3, 11, 0, 1, 'schraffierte Ellipse                     ');
insert into label values (180, 4, 0, 0, 1, 'Modifizieren                             ');
insert into label values (180, 4, 1, 0, 1, 'Element verschieben                      ');
insert into label values (180, 4, 2, 0, 1, 'Element kopieren                         ');
insert into label values (180, 4, 3, 0, 1, 'Element loeschen                         ');
insert into label values (180, 5, 0, 0, 1, 'Settings                                 ');
insert into label values (180, 5, 1, 0, 1, 'Gitter                                   ');
insert into label values (180, 5, 2, 0, 1, 'Pickbox                                  ');
insert into label values (180, 5, 3, 0, 1, 'Punktradius                              ');
insert into label values (180, 5, 4, 0, 1, 'Zeichenflaeche                           ');
insert into label values (180, 6, 0, 0, 1, 'Zoom                                     ');
insert into label values (180, 6, 1, 0, 1, 'Start                                    ');
insert into label values (180, 6, 2, 0, 1, 'neu                                      ');
insert into label values (180, 6, 3, 0, 1, 'letzter Zoom                             ');
insert into label values (180, 6, 4, 0, 1, 'naechster Zoom                           ');
insert into label values (180, 6, 5, 0, 1, 'resize                                   ');
insert into label values (180, 6, 6, 0, 1, '..... dbg print                          ');
insert into label values (180, 7, 0, 0, 1, 'Hilfe                                    ');
insert into label values (180, 7, 1, 0, 1, 'Hilfe ueber Graphik                      ');
insert into label values (180, 7, 2, 0, 1, 'Hilfe ueber Hauptmenu                    ');
insert into label values (180, 7, 3, 0, 1, 'Hilfe ueber Menu ...                     ');
insert into label values (180, 7, 4, 0, 1, 'Hilfe allg                               ');
insert into label values (180, 8, 0, 0, 1, 'ok                                       ');
insert into label values (180, 8, 1, 0, 1, 'no                                       ');
insert into label values (180, 8, 2, 0, 1, 'ganze Graphik loeschen ?                 ');
insert into label values (180, 8, 3, 0, 1, 'Graphik verlassen ohne Sicherung ?       ');
insert into label values (180, 8, 4, 0, 1, 'Buchung senden                           ');
insert into label values (180, 9, 0, 0, 1, ' 1. Punkt des Vektors                    ');
insert into label values (180, 9, 1, 0, 1, ' 2. Punkt des Vektors                    ');
insert into label values (180, 9, 2, 0, 1, 'Punkt eingeben                           ');
insert into label values (180, 9, 3, 0, 1, 'Linke obere Ecke (Rechteck)              ');
insert into label values (180, 9, 4, 0, 1, 'Rechte untere Ecke (Rechteck)            ');
insert into label values (180, 9, 5, 0, 1, ' 1. Peripheriepunkt (Kreissegt)          ');
insert into label values (180, 9, 6, 0, 1, ' 2. Peripheriepunkt (Kreissegt)          ');
insert into label values (180, 9, 7, 0, 1, ' 3. Peripheriepunkt (Kreissegt)          ');
insert into label values (180, 9, 8, 0, 1, 'Kreismittelpunkt eingeben                ');
insert into label values (180, 9, 9, 0, 1, 'Peripheriepunkt eingeben                 ');
insert into label values (180, 9, 10, 0, 1, 'linke obere Ecke (Pickbox)               ');
insert into label values (180, 9, 11, 0, 1, 'rechte untere Ecke (Pickbox)             ');
insert into label values (180, 9, 12, 0, 1, 'Text eingeben                            ');
insert into label values (180, 9, 13, 0, 1, 'linke untere Ecke (Textanfang)           ');
insert into label values (180, 9, 14, 0, 1, 'Gitterabstand im mm eingeben             ');
insert into label values (180, 9, 15, 0, 1, 'Pickboxgroesse in mm eingeben            ');
insert into label values (180, 9, 16, 0, 1, 'Zeichenblattgroesse (A0-A4)              ');
insert into label values (180, 9, 17, 0, 1, 'Punktradius in mm eingeben               ');
insert into label values (180, 9, 18, 0, 1, 'Element in Pickbox auswaehlen            ');
insert into label values (180, 9, 19, 0, 1, 'Bestimmungsort eingeben                  ');
insert into label values (180, 9, 20, 0, 1, 'Element in Pickbox auswaehlen            ');
insert into label values (180, 9, 21, 0, 1, 'Bestimmungsort der Kopie                 ');
insert into label values (180, 9, 22, 0, 1, 'Element in Pickbox auswaehlen            ');
insert into label values (180, 9, 23, 0, 1, 'linke obere Ecke (Ausschnitt)            ');
insert into label values (180, 9, 24, 0, 1, 'rechte untere Ecke (Ausschnitt)          ');
insert into label values (180, 9, 25, 0, 1, 'Punkt eingeben fuer Textelement          ');
insert into label values (180, 9, 26, 0, 1, 'Punkt eines Elementes auswaehlen         ');
insert into label values (180, 10, 0, 0, 1, 'Ende                                     ');
insert into label values (180, 10, 1, 0, 1, 'Zoom original                            ');
insert into label values (180, 10, 2, 0, 1, 'Zoom neu                                 ');
insert into label values (180, 10, 3, 0, 1, 'Zoom-                                    ');
insert into label values (180, 10, 4, 0, 1, 'Zoom+                                    ');
insert into label values (180, 10, 5, 0, 1, 'Hilfe                                    ');
insert into label values (181, 1, 0, 0, 1, 'Sprachen...                              ');
insert into label values (181, 1, 1, 0, 1, 'Sprachen Bezeichnung                     ');
insert into label values (181, 1, 2, 0, 1, 'Dialogsprache ?                          ');
insert into label values (181, 1, 3, 0, 1, 'Systembezeichnung (NLS)                  ');
insert into label values (181, 1, 4, 0, 1, 'Output Sprache ?                         ');
insert into label values (181, 1, 5, 0, 1, 'GUI Sprache ?                            ');
insert into label values (181, 2, 0, 0, 1, 'Statuswerte...                           ');
insert into label values (181, 2, 1, 0, 1, 'Status Bezeichnung                       ');
insert into label values (181, 2, 2, 0, 1, 'Abkuerzung                               ');
insert into label values (181, 2, 3, 0, 1, 'Status Wert                              ');
insert into label values (181, 2, 4, 0, 1, 'Konditionen                              ');
insert into label values (181, 2, 5, 0, 1, 'Status Typ                               ');
insert into label values (181, 3, 0, 0, 1, 'Bezeichnungen...                         ');
insert into label values (181, 3, 1, 0, 1, 'Sprache                                  ');
insert into label values (181, 3, 2, 0, 1, 'Bezeichnungstyp                          ');
insert into label values (181, 3, 3, 0, 1, 'Bezeichnung                              ');
insert into label values (181, 3, 4, 0, 1, 'neue Bezeichnung                         ');
insert into label values (181, 4, 0, 0, 1, 'Texte...                                 ');
insert into label values (181, 4, 1, 0, 1, 'Sprache                                  ');
insert into label values (181, 4, 2, 0, 1, 'Text                                     ');
insert into label values (181, 4, 3, 0, 1, 'zu Sprache                               ');
insert into label values (181, 4, 4, 0, 1, 'zu Text                                  ');
insert into label values (181, 6, 0, 0, 1, 'Hilfe...                                 ');
insert into label values (181, 6, 1, 0, 1, 'Hilfe Typ                                ');
insert into label values (181, 6, 2, 0, 1, 'Hilfe Nummer                             ');
insert into label values (181, 6, 3, 0, 1, 'Sprache                                  ');
insert into label values (181, 6, 4, 0, 1, 'Hilfe Text                               ');
insert into label values (181, 7, 0, 0, 1, 'Messages...                              ');
insert into label values (181, 7, 1, 0, 1, 'Meldungstyp                              ');
insert into label values (181, 7, 2, 0, 1, 'Meldungsnummer                           ');
insert into label values (181, 7, 3, 0, 1, 'Sprache                                  ');
insert into label values (181, 7, 4, 0, 1, 'Text                                     ');
insert into label values (181, 8, 0, 0, 1, 'Labels...                                ');
insert into label values (181, 8, 1, 0, 1, 'Label Bezeichnung                        ');
insert into label values (181, 8, 2, 0, 1, 'Label Sprache                            ');
insert into label values (181, 8, 3, 0, 1, 'Label Programmnummer                     ');
insert into label values (181, 8, 4, 0, 1, 'Label Typ                                ');
insert into label values (181, 8, 5, 0, 1, 'Label Stufe 1                            ');
insert into label values (181, 8, 6, 0, 1, 'Label Stufe 2                            ');
insert into label values (181, 9, 0, 0, 1, 'Saisons...                               ');
insert into label values (181, 9, 1, 0, 1, 'Saison Bezeichnung                       ');
insert into label values (181, 9, 2, 0, 1, 'Code                                     ');
insert into label values (181, 9, 3, 0, 1, 'Von - Datum [tt.mm.jj]                   ');
insert into label values (181, 9, 4, 0, 1, 'Bis - Datum [tt.mm.jj]                   ');
insert into label values (181, 9, 5, 0, 1, 'Beschreibung                             ');
insert into label values (181, 10, 0, 0, 1, 'Laender...                               ');
insert into label values (181, 10, 1, 0, 1, 'Land                                     ');
insert into label values (181, 10, 2, 0, 1, 'Hauptstadt                               ');
insert into label values (181, 10, 3, 0, 1, 'Landeswaehrung                           ');
insert into label values (181, 10, 4, 0, 1, 'Nationalsprache                          ');
insert into label values (181, 10, 5, 0, 1, 'Kuerzel                                  ');
insert into label values (181, 10, 6, 0, 1, 'Mehrwertssteuer (in %)                   ');
insert into label values (181, 10, 7, 0, 1, 'Beschreibung                             ');
insert into label values (181, 10, 8, 0, 1, 'Datumsformat                             ');
insert into label values (181, 11, 0, 0, 1, 'Orte...                                  ');
insert into label values (181, 11, 1, 0, 1, 'Ort                                      ');
insert into label values (181, 11, 2, 0, 1, 'Land                                     ');
insert into label values (181, 11, 3, 0, 1, 'Typ                                      ');
insert into label values (181, 11, 4, 0, 1, 'Kuerzel                                  ');
insert into label values (181, 11, 5, 0, 1, 'Zeitverschiebung                         ');
insert into label values (181, 11, 6, 0, 1, 'X Koordinate                             ');
insert into label values (181, 11, 7, 0, 1, 'Y Koordinate                             ');
insert into label values (181, 11, 8, 0, 1, 'Beschreibung                             ');
insert into label values (181, 12, 0, 0, 1, 'Waehrungen...                            ');
insert into label values (181, 12, 1, 0, 1, 'Waehrung                                 ');
insert into label values (181, 12, 2, 0, 1, 'Waehrungsstatus                          ');
insert into label values (181, 12, 3, 0, 1, 'Kuerzel                                  ');
insert into label values (181, 12, 4, 0, 1, 'Beschreibung                             ');
insert into label values (181, 13, 0, 0, 1, 'Kurse...                                 ');
insert into label values (181, 13, 1, 0, 1, 'Land                                     ');
insert into label values (181, 13, 2, 0, 1, 'Waehrung                                 ');
insert into label values (181, 13, 3, 0, 1, 'Kurstyp                                  ');
insert into label values (181, 13, 4, 0, 1, 'Ankaufskurs                              ');
insert into label values (181, 13, 5, 0, 1, 'Verkaufskurs                             ');
insert into label values (181, 13, 6, 0, 1, 'Kurs Datum                               ');
insert into label values (181, 15, 0, 0, 1, 'Traegertypen...                          ');
insert into label values (181, 15, 1, 0, 1, 'Traegertyp Bezeichnung                   ');
insert into label values (181, 15, 2, 0, 1, 'Uebergeordneter Traegertyp               ');
insert into label values (181, 15, 3, 0, 1, 'Beschreibung                             ');
insert into label values (181, 16, 0, 0, 1, 'Kategorien...                            ');
insert into label values (181, 16, 1, 0, 1, 'Kategorie Bezeichnung                    ');
insert into label values (181, 16, 2, 0, 1, 'Traegertyp                               ');
insert into label values (181, 16, 3, 0, 1, 'upgrade Kategorie                        ');
insert into label values (181, 16, 4, 0, 1, 'graph. Attribut                          ');
insert into label values (181, 16, 5, 0, 1, 'Beschreibung                             ');
insert into label values (181, 17, 0, 0, 1, 'Dienstleistungstraeger...                ');
insert into label values (181, 17, 1, 0, 1, 'Dienstleistungstraeger Bezeichnung       ');
insert into label values (181, 17, 2, 0, 1, 'Kategorie                                ');
insert into label values (181, 17, 3, 0, 1, 'Uebergeordneter Traeger                  ');
insert into label values (181, 17, 4, 0, 1, 'Traegertyp                               ');
insert into label values (181, 17, 5, 0, 1, 'Beschreibung                             ');
insert into label values (181, 17, 6, 0, 1, 'Haupt Dienstleistungstraeger             ');
insert into label values (181, 17, 7, 0, 1, 'Bestplatzattribut                        ');
insert into label values (181, 17, 8, 0, 1, 'Code                                     ');
insert into label values (181, 17, 9, 0, 1, 'Anzahl                                   ');
insert into label values (181, 18, 0, 0, 1, 'Angebotstypen...                         ');
insert into label values (181, 18, 1, 0, 1, 'Angebotstyp Bezeichnung                  ');
insert into label values (181, 18, 2, 0, 1, 'Beschreibung                             ');
insert into label values (181, 19, 0, 0, 1, 'Aktionstypen...                          ');
insert into label values (181, 19, 1, 0, 1, 'Aktionstyp Bezeichnung                   ');
insert into label values (181, 19, 2, 0, 1, 'Prozess                                  ');
insert into label values (181, 19, 3, 0, 1, 'Beschreibung                             ');
insert into label values (181, 19, 4, 0, 1, 'Parameternummer                          ');
insert into label values (181, 19, 5, 0, 1, 'Parametertyp                             ');
insert into label values (181, 19, 6, 0, 1, 'Parameter                                ');
insert into label values (181, 19, 7, 0, 1, 'MUSS-Parameter ?                         ');
insert into label values (181, 19, 8, 0, 1, 'FLAG-Parameter ?                         ');
insert into label values (181, 19, 9, 0, 1, 'Parameterbeschreibung                    ');
insert into label values (181, 21, 0, 0, 1, 'Aktionen...                              ');
insert into label values (181, 21, 1, 0, 1, 'Aktionsbezeichnung                       ');
insert into label values (181, 21, 2, 0, 1, 'Ausgabegeraet                            ');
insert into label values (181, 21, 3, 0, 1, 'Beschreibung                             ');
insert into label values (181, 21, 4, 0, 1, 'Ausfuehrungsstatus                       ');
insert into label values (181, 21, 5, 0, 1, 'Reservationsstatus als Ausloeser         ');
insert into label values (181, 21, 6, 0, 1, 'Aktionstyp                               ');
insert into label values (181, 21, 7, 0, 1, 'Reservationsstatus bei Erfolg            ');
insert into label values (181, 22, 0, 0, 1, 'Aktionsgruppen...                        ');
insert into label values (181, 22, 1, 0, 1, 'Uebergeordnete Aktion                    ');
insert into label values (181, 22, 2, 0, 1, 'Aktion                                   ');
insert into label values (181, 22, 3, 0, 1, 'Reihenfolge                              ');
insert into label values (181, 23, 0, 0, 1, 'Angebote/(Teil)Strecken...               ');
insert into label values (181, 23, 1, 0, 1, 'Angebotsbezeichnung                      ');
insert into label values (181, 23, 2, 0, 1, 'Uebergeordnetes Angebot                  ');
insert into label values (181, 23, 3, 0, 1, 'Reihenfolge des Angebotes                ');
insert into label values (181, 23, 4, 0, 1, 'Dienstleistungstraeger                   ');
insert into label values (181, 23, 5, 0, 1, 'Aktionen                                 ');
insert into label values (181, 23, 6, 0, 1, 'Einfindungsort                           ');
insert into label values (181, 23, 7, 0, 1, 'Angebotstyp                              ');
insert into label values (181, 23, 8, 0, 1, 'Dauer [tt.ss.mm]                         ');
insert into label values (181, 23, 9, 0, 1, 'Beschreibung                             ');
insert into label values (181, 23, 10, 0, 1, 'Von-Destination                          ');
insert into label values (181, 23, 11, 0, 1, 'Nach-Destination                         ');
insert into label values (181, 23, 12, 0, 1, 'Code                                     ');
insert into label values (181, 24, 0, 0, 1, 'Kundentypen...                           ');
insert into label values (181, 24, 1, 0, 1, 'Kundentyp Bezeichnung                    ');
insert into label values (181, 24, 2, 0, 1, 'Beschreibung                             ');
insert into label values (181, 24, 3, 0, 1, 'Code                                     ');
insert into label values (181, 25, 0, 0, 1, 'Kunden...                                ');
insert into label values (181, 25, 1, 0, 1, 'Kunden-Nummer                            ');
insert into label values (181, 25, 2, 0, 1, 'Kundenname                               ');
insert into label values (181, 25, 3, 0, 1, 'Ortschaft                                ');
insert into label values (181, 25, 4, 0, 1, 'Kundentyp                                ');
insert into label values (181, 25, 5, 0, 1, 'Land                                     ');
insert into label values (181, 25, 6, 0, 1, 'Rechnungswaehrung                        ');
insert into label values (181, 25, 7, 0, 1, 'Sprache                                  ');
insert into label values (181, 25, 8, 0, 1, 'Telephon-Nummer                          ');
insert into label values (181, 25, 9, 0, 1, 'Fax-Nummer                               ');
insert into label values (181, 25, 10, 0, 1, 'Telex-Nummer                             ');
insert into label values (181, 25, 11, 0, 1, 'Konto-Nummer                             ');
insert into label values (181, 25, 12, 0, 1, 'Name Geschaeftsleiter                    ');
insert into label values (181, 25, 13, 0, 1, 'Kanton/Kreis Bezeichnung                 ');
insert into label values (181, 25, 14, 0, 1, 'e-mail                                   ');
insert into label values (181, 25, 15, 0, 1, 'Internet URL                             ');
insert into label values (181, 25, 16, 0, 1, 'Beschreibung                             ');
insert into label values (181, 26, 0, 0, 1, 'Teildienstleistungen...                  ');
insert into label values (181, 26, 1, 0, 1, 'Teildienstleistungs Bezeichnung          ');
insert into label values (181, 26, 2, 0, 1, 'Uebergeordnete Teildienstleistung        ');
insert into label values (181, 26, 3, 0, 1, 'Angebot/(Teil)Strecken                   ');
insert into label values (181, 26, 4, 0, 1, 'Anfangszeit [tt.mm.jj [ss.mm]]           ');
insert into label values (181, 26, 5, 0, 1, 'Endzeit     [tt.mm.jj [ss.mm]]           ');
insert into label values (181, 26, 6, 0, 1, 'Reservationsart                          ');
insert into label values (181, 26, 7, 0, 1, 'Anbieter/Verwalter                       ');
insert into label values (181, 26, 8, 0, 1, 'Ertragskonto-Nummer                      ');
insert into label values (181, 26, 9, 0, 1, 'Beschreibung                             ');
insert into label values (181, 26, 10, 0, 1, 'Saison                                   ');
insert into label values (181, 26, 11, 0, 1, 'Abrechnungsstelle                        ');
insert into label values (181, 26, 12, 0, 1, 'Code                                     ');
insert into label values (181, 27, 0, 0, 1, 'Dienstleistungen...                      ');
insert into label values (181, 27, 1, 0, 1, 'Dienstleistungs Bezeichnung              ');
insert into label values (181, 27, 2, 0, 1, 'Teildienstleistung                       ');
insert into label values (181, 27, 3, 0, 1, 'Beschreibung                             ');
insert into label values (181, 27, 4, 0, 1, 'Anfangszeit [tt.mm.jj [ss.mm]]           ');
insert into label values (181, 27, 5, 0, 1, 'Aktionen                                 ');
insert into label values (181, 27, 6, 0, 1, 'Reihenfolge                              ');
insert into label values (181, 27, 7, 0, 1, 'Code                                     ');
insert into label values (181, 29, 0, 0, 1, 'Ferienkatalog/Destination...             ');
insert into label values (181, 29, 1, 0, 1, 'Katalog/Dest. Bezeichnung                ');
insert into label values (181, 29, 2, 0, 1, 'Code                                     ');
insert into label values (181, 29, 3, 0, 1, 'Beschreibung                             ');
insert into label values (181, 29, 4, 0, 1, 'Saison                                   ');
insert into label values (181, 30, 0, 0, 1, 'Arrangements...                          ');
insert into label values (181, 30, 1, 0, 1, 'Arrangement Bezeichnung                  ');
insert into label values (181, 30, 2, 0, 1, 'Start Datum [tt.mm.jj]                   ');
insert into label values (181, 30, 3, 0, 1, 'Ferienkatalog/Destination                ');
insert into label values (181, 30, 4, 0, 1, 'Prioritaet                               ');
insert into label values (181, 30, 5, 0, 1, 'Beschreibung                             ');
insert into label values (181, 30, 6, 0, 1, 'Dienstleistung                           ');
insert into label values (181, 30, 7, 0, 1, 'Teilstueck Nummer                        ');
insert into label values (181, 30, 8, 0, 1, 'Code                                     ');
insert into label values (181, 32, 0, 0, 1, 'Kollektivtypen...                        ');
insert into label values (181, 32, 1, 0, 1, 'Kollektivtyp Bezeichnung                 ');
insert into label values (181, 32, 2, 0, 1, 'Beschreibung                             ');
insert into label values (181, 32, 3, 0, 1, 'Code                                     ');
insert into label values (181, 33, 0, 0, 1, 'Gruppe/Kollektiv...                      ');
insert into label values (181, 33, 1, 0, 1, 'Gruppen Bezeichnung                      ');
insert into label values (181, 33, 2, 0, 1, 'Gruppen-Verantwortlicher                 ');
insert into label values (181, 33, 3, 0, 1, 'Kollektivtyp                             ');
insert into label values (181, 33, 4, 0, 1, 'Beschreibung                             ');
insert into label values (181, 33, 5, 0, 1, 'Kunde / Rechnungsempfaenger              ');
insert into label values (181, 33, 6, 0, 1, 'GSA / Buchungsstelle                     ');
insert into label values (181, 33, 7, 0, 1, 'Gruppen/Kollektiv-Referenz               ');
insert into label values (181, 35, 0, 0, 1, 'Reisendertypen...                        ');
insert into label values (181, 35, 1, 0, 1, 'Reisendertyp Bezeichnung                 ');
insert into label values (181, 35, 2, 0, 1, 'Beschreibung                             ');
insert into label values (181, 35, 3, 0, 1, 'Code                                     ');
insert into label values (181, 35, 4, 0, 1, 'von Altersgrenze                         ');
insert into label values (181, 35, 5, 0, 1, 'bis Altersgrenze                         ');
insert into label values (181, 36, 0, 0, 1, 'Reisende...                              ');
insert into label values (181, 36, 1, 0, 1, 'Reisendernummer                          ');
insert into label values (181, 36, 2, 0, 1, 'Name                                     ');
insert into label values (181, 36, 3, 0, 1, 'Vorname                                  ');
insert into label values (181, 36, 4, 0, 1, 'Wohnort                                  ');
insert into label values (181, 36, 5, 0, 1, 'Typ                                      ');
insert into label values (181, 36, 6, 0, 1, 'Geschlecht/Anrede                        ');
insert into label values (181, 36, 7, 0, 1, 'Sprache                                  ');
insert into label values (181, 36, 8, 0, 1, 'Land                                     ');
insert into label values (181, 36, 9, 0, 1, 'Alter                                    ');
insert into label values (181, 36, 10, 0, 1, 'Passnummer                               ');
insert into label values (181, 36, 11, 0, 1, 'Nationalitaet                            ');
insert into label values (181, 36, 12, 0, 1, 'Geburtsort                               ');
insert into label values (181, 36, 13, 0, 1, 'Pax Info                                 ');
insert into label values (181, 36, 14, 0, 1, 'Ticket Text                              ');
insert into label values (181, 37, 0, 0, 1, 'Adressen...                              ');
insert into label values (181, 37, 1, 0, 1, 'Kunde                                    ');
insert into label values (181, 37, 2, 0, 1, 'Reisender                                ');
insert into label values (181, 37, 3, 0, 1, 'Anrede/Titel                             ');
insert into label values (181, 37, 4, 0, 1, 'Adresse                                  ');
insert into label values (181, 37, 5, 0, 1, 'Adresse                                  ');
insert into label values (181, 37, 6, 0, 1, 'Adresse                                  ');
insert into label values (181, 37, 7, 0, 1, 'Ort                                      ');
insert into label values (181, 37, 8, 0, 1, 'Postleitzahl                             ');
insert into label values (181, 37, 9, 0, 1, 'Versandstatus                            ');
insert into label values (181, 38, 0, 0, 1, 'Hauptkontingente...                      ');
insert into label values (181, 38, 1, 0, 1, 'Hauptkontingent                          ');
insert into label values (181, 38, 2, 0, 1, 'von Liferant                             ');
insert into label values (181, 38, 3, 0, 1, 'GSA Buchungsstelle                       ');
insert into label values (181, 38, 4, 0, 1, 'Angebote/(Teil)Strecken                  ');
insert into label values (181, 38, 5, 0, 1, 'Dienstleistung                           ');
insert into label values (181, 38, 6, 0, 1, 'Dienstleistung von Datum                 ');
insert into label values (181, 38, 7, 0, 1, 'Dienstleistung bis Datum                 ');
insert into label values (181, 38, 8, 0, 1, 'Option bis [tt.mm.jj]                    ');
insert into label values (181, 38, 9, 0, 1, 'Referenz                                 ');
insert into label values (181, 38, 10, 0, 1, 'Beschreibung                             ');
insert into label values (181, 38, 11, 0, 1, 'Code                                     ');
insert into label values (181, 39, 0, 0, 1, 'Kontingente...                           ');
insert into label values (181, 39, 1, 0, 1, 'Kontingent                               ');
insert into label values (181, 39, 2, 0, 1, 'Top Kontingent                           ');
insert into label values (181, 39, 3, 0, 1, 'an Kunde                                 ');
insert into label values (181, 39, 4, 0, 1, 'Option bis [tt.mm.jj]                    ');
insert into label values (181, 39, 5, 0, 1, 'Referenz                                 ');
insert into label values (181, 39, 6, 0, 1, 'Beschreibung                             ');
insert into label values (181, 40, 0, 0, 1, 'Kontingentdetails...                     ');
insert into label values (181, 40, 1, 0, 1, 'Hauptkontingent                          ');
insert into label values (181, 40, 2, 0, 1, 'Kontingent                               ');
insert into label values (181, 40, 3, 0, 1, 'Kategorie                                ');
insert into label values (181, 40, 4, 0, 1, 'Menge                                    ');
insert into label values (181, 40, 5, 0, 1, 'Mindestanzahl                            ');
insert into label values (181, 40, 6, 0, 1, 'Dienstleistungstraeger                   ');
insert into label values (181, 40, 7, 0, 1, 'Ueberbuchungsfaktor                      ');
insert into label values (181, 41, 0, 0, 1, 'Dossier/Buchungsmaske...                 ');
insert into label values (181, 41, 1, 0, 1, 'Buchungsreferenz                         ');
insert into label values (181, 41, 2, 0, 1, 'Buchungsnummer                           ');
insert into label values (181, 41, 3, 0, 1, 'Dossier/Buchungsstatus                   ');
insert into label values (181, 41, 4, 0, 1, 'Objekt: Datum                            ');
insert into label values (181, 41, 5, 0, 1, 'Objekt: * Arrangement                    ');
insert into label values (181, 41, 6, 0, 1, 'Objekt: * Dienstleistung                 ');
insert into label values (181, 41, 7, 0, 1, 'GSA:  Buchungsstelle                     ');
insert into label values (181, 41, 8, 0, 1, 'Kunde:  Rechnungsstelle                  ');
insert into label values (181, 41, 9, 0, 1, 'Objekt: Dienstleistungstraeger           ');
insert into label values (181, 41, 10, 0, 1, 'Objekt: Angebote/(Teil)Strecken          ');
insert into label values (181, 41, 11, 0, 1, 'Kunde:  Gruppe/Kollektiv                 ');
insert into label values (181, 41, 12, 0, 1, 'Hauptbuchung bei Doppelbuchung           ');
insert into label values (181, 41, 13, 0, 1, 'Sachbearbeiter Rechnungsstelle           ');
insert into label values (181, 41, 14, 0, 1, 'Anfrageoption bis [dd.mm.yy]             ');
insert into label values (181, 41, 15, 0, 1, 'Kundenoption bis [dd.mm.yy]              ');
insert into label values (181, 41, 16, 0, 1, 'Buchungshistory                          ');
insert into label values (181, 41, 17, 0, 1, 'Buchung: Reisender                       ');
insert into label values (181, 41, 18, 0, 1, 'Sitzung Text                             ');
insert into label values (181, 43, 0, 0, 1, 'Kostenarten...                           ');
insert into label values (181, 43, 1, 0, 1, 'Kostenart Bezeichnung                    ');
insert into label values (181, 43, 2, 0, 1, 'Beschreibung                             ');
insert into label values (181, 44, 0, 0, 1, 'Kommissionen/Reduktionen...              ');
insert into label values (181, 44, 1, 0, 1, 'Kommissionsbezeichnung                   ');
insert into label values (181, 44, 2, 0, 1, 'Kommissionstyp                           ');
insert into label values (181, 44, 3, 0, 1, 'Satzart                                  ');
insert into label values (181, 44, 4, 0, 1, 'Satz/Wert                                ');
insert into label values (181, 44, 5, 0, 1, 'GSA Buchungsstelle/Aussteller            ');
insert into label values (181, 44, 6, 0, 1, 'Kostenart                                ');
insert into label values (181, 44, 7, 0, 1, 'Kategorie                                ');
insert into label values (181, 44, 8, 0, 1, 'Reisendertyp                             ');
insert into label values (181, 44, 9, 0, 1, 'Angebote/(Teil)Strecken                  ');
insert into label values (181, 44, 10, 0, 1, 'Dienstleistung                           ');
insert into label values (181, 44, 11, 0, 1, 'Dienstleistung von Datum                 ');
insert into label values (181, 44, 12, 0, 1, 'Dienstleistung bis Datum                 ');
insert into label values (181, 44, 13, 0, 1, 'Kontingent                               ');
insert into label values (181, 44, 14, 0, 1, 'Buchung                                  ');
insert into label values (181, 44, 15, 0, 1, 'Text                                     ');
insert into label values (181, 44, 16, 0, 1, 'Traegertyp                               ');
insert into label values (181, 45, 0, 0, 1, 'Kommissionsverknuepfungen...             ');
insert into label values (181, 45, 1, 0, 1, 'Kommissionsbezeichnung                   ');
insert into label values (181, 45, 2, 0, 1, 'betreffende Buchung                      ');
insert into label values (181, 45, 3, 0, 1, 'Verknuepfung: Reisender                  ');
insert into label values (181, 45, 4, 0, 1, 'Verknuepfung: Kunde                      ');
insert into label values (181, 45, 5, 0, 1, 'Verknuepfung: Kollektiv                  ');
insert into label values (181, 45, 6, 0, 1, 'Reihenfolge                              ');
insert into label values (181, 46, 0, 0, 1, 'Buchungs-Details...                      ');
insert into label values (181, 46, 1, 0, 1, 'Dienstleistung                           ');
insert into label values (181, 46, 2, 0, 1, 'Dienstleistungsteil                      ');
insert into label values (181, 46, 3, 0, 1, 'Reisender                                ');
insert into label values (181, 46, 4, 0, 1, 'Dienstleistungstraeger                   ');
insert into label values (181, 46, 5, 0, 1, 'Traegertyp                               ');
insert into label values (181, 46, 6, 0, 1, 'Kategorie                                ');
insert into label values (181, 46, 7, 0, 1, 'Kontingent                               ');
insert into label values (181, 46, 8, 0, 1, 'Reservationsstatus                       ');
insert into label values (181, 46, 9, 0, 1, 'Anfangszeit der Dienstleistung           ');
insert into label values (181, 46, 10, 0, 1, 'Endzeit der Dienstleistung               ');
insert into label values (181, 47, 0, 0, 1, 'Preise...                                ');
insert into label values (181, 47, 1, 0, 1, 'Preisnummer                              ');
insert into label values (181, 47, 2, 0, 1, 'Waehrung                                 ');
insert into label values (181, 47, 3, 0, 1, 'Ankaufspreis                             ');
insert into label values (181, 47, 4, 0, 1, 'Einstandspreis                           ');
insert into label values (181, 47, 5, 0, 1, 'Verkaufspreis                            ');
insert into label values (181, 47, 6, 0, 1, 'gueltig ab [tt.mm.jj]                    ');
insert into label values (181, 47, 7, 0, 1, 'GSA Buchungsstelle/Aussteller            ');
insert into label values (181, 47, 8, 0, 1, 'Kostenart                                ');
insert into label values (181, 47, 9, 0, 1, 'Traegertyp                               ');
insert into label values (181, 47, 10, 0, 1, 'Kategorie                                ');
insert into label values (181, 47, 11, 0, 1, 'Reisendertyp                             ');
insert into label values (181, 47, 12, 0, 1, 'Angebote/(Teil)Strecken                  ');
insert into label values (181, 47, 13, 0, 1, 'Dienstleistung                           ');
insert into label values (181, 47, 14, 0, 1, 'Dienstleistung von Datum                 ');
insert into label values (181, 47, 15, 0, 1, 'Dienstleistung bis Datum                 ');
insert into label values (181, 47, 16, 0, 1, 'Kontingent                               ');
insert into label values (181, 47, 17, 0, 1, 'Status                                   ');
insert into label values (181, 47, 18, 0, 1, 'Beschreibung                             ');
insert into label values (181, 47, 19, 0, 1, 'Arrangement                              ');
insert into label values (181, 47, 20, 0, 1, 'Art der Preiseinheit                     ');
insert into label values (181, 47, 21, 0, 1, 'Einheit von                              ');
insert into label values (181, 47, 22, 0, 1, 'Einheit bis                              ');
insert into label values (181, 48, 0, 0, 1, 'Grafiken/Plaene...                       ');
insert into label values (181, 48, 1, 0, 1, 'Grafik Bezeichnung                       ');
insert into label values (181, 48, 2, 0, 1, 'Dienstleistungstraeger                   ');
insert into label values (181, 48, 3, 0, 1, 'Beschreibung                             ');
insert into label values (181, 49, 0, 0, 1, 'Internet WWW URL...                      ');
insert into label values (181, 49, 1, 0, 1, 'URL internal descr.                      ');
insert into label values (181, 49, 2, 0, 1, 'URL                                      ');
insert into label values (181, 49, 3, 0, 1, 'Objekttyp                                ');
insert into label values (181, 49, 4, 0, 1, 'Objekt                                   ');
insert into label values (181, 49, 5, 0, 1, 'Folge                                    ');
insert into label values (181, 49, 6, 0, 1, 'relativer X-Wert                         ');
insert into label values (181, 49, 7, 0, 1, 'relativer Y-Wert                         ');
insert into label values (181, 150, 0, 0, 1, ' Infos                                   ');
insert into label values (181, 150, 1, 0, 1, '*Hilfe*                                  ');
insert into label values (181, 150, 2, 0, 1, 'unteres                                  ');
insert into label values (181, 150, 3, 0, 1, ' Feld                                    ');
insert into label values (181, 150, 4, 0, 1, 'voriges                                  ');
insert into label values (181, 150, 5, 0, 1, ' Feld                                    ');
insert into label values (181, 150, 6, 0, 1, 'Eintrag                                  ');
insert into label values (181, 150, 7, 0, 1, 'loeschen                                 ');
insert into label values (181, 150, 8, 0, 1, 'Eingabe                                  ');
insert into label values (181, 150, 9, 0, 1, 'beenden                                  ');
insert into label values (181, 150, 10, 0, 1, 'weiter                                   ');
insert into label values (181, 150, 11, 0, 1, 'fahren                                   ');
insert into label values (181, 150, 12, 0, 1, ' Maske                                   ');
insert into label values (181, 150, 13, 0, 1, 'loeschen                                 ');
insert into label values (181, 150, 14, 0, 1, ' Menue                                   ');
insert into label values (181, 150, 15, 0, 1, 'beenden                                  ');
insert into label values (181, 151, 0, 0, 1, 'Datei                                    ');
insert into label values (181, 151, 1, 0, 1, 'Buchung                                  ');
insert into label values (181, 151, 2, 0, 1, 'Angebot                                  ');
insert into label values (181, 151, 3, 0, 1, 'Stamm                                    ');
insert into label values (181, 151, 4, 0, 1, 'Geo                                      ');
insert into label values (181, 151, 5, 0, 1, 'Texte                                    ');
insert into label values (181, 151, 6, 0, 1, 'Hilfe                                    ');
insert into label values (181, 151, 7, 0, 1, '*                                        ');
insert into label values (181, 152, 0, 0, 1, 'Ja                                       ');
insert into label values (181, 152, 1, 0, 1, 'Nein                                     ');
insert into label values (181, 152, 2, 0, 1, 'Menu verlassen ?                         ');
insert into label values (181, 152, 3, 0, 1, 'Eintrag loeschen ?                       ');
insert into label values (181, 152, 4, 0, 1, 'Eintrag modifizieren ?                   ');
insert into label values (181, 152, 5, 0, 1, 'Weiter                                   ');
insert into label values (181, 152, 6, 0, 1, 'Abbrechen                                ');
insert into label values (181, 152, 7, 0, 1, 'Printen                                  ');
insert into label values (181, 152, 8, 0, 1, 'naechster                                ');
insert into label values (181, 152, 9, 0, 1, 'vorhergehender                           ');
insert into label values (181, 152, 10, 0, 1, 'travelDB Applikation verlassen ?        ');
insert into label values (181, 152, 11, 0, 1, 'Globale Werte speichern ?               ');
insert into label values (181, 153, 0, 0, 1, 'optionale Felder                         ');
insert into label values (181, 153, 1, 0, 1, 'Neueingeben                              ');
insert into label values (181, 153, 2, 0, 1, 'Aendern                                  ');
insert into label values (181, 153, 3, 0, 1, 'Loeschen                                 ');
insert into label values (181, 154, 0, 0, 1, 'obligatorische Felder                    ');
insert into label values (181, 154, 1, 0, 1, 'optionale Felder                         ');
insert into label values (181, 154, 2, 0, 1, 'Befehle                                  ');
insert into label values (181, 154, 3, 0, 1, 'Einstellungen                            ');
insert into label values (181, 157, 0, 0, 1, '                                         ');
insert into label values (181, 157, 1, 0, 1, 'travelDB                                 ');
insert into label values (181, 157, 2, 0, 1, 'Globale Werte                            ');
insert into label values (181, 157, 3, 0, 1, 'GLOBAL                                   ');
insert into label values (181, 157, 4, 0, 1, 'Information                              ');
insert into label values (181, 157, 5, 0, 1, 'Bedienungsanleitung                      ');
insert into label values (181, 157, 6, 0, 1, 'Fehlermeldung                            ');
insert into label values (181, 157, 7, 0, 1, 'Auswahlmenu                              ');
insert into label values (181, 157, 8, 0, 1, 'Suchmaske                                ');
insert into label values (181, 157, 9, 0, 1, 'A C H T U N G                            ');
insert into label values (181, 157, 10, 0, 1, 'Auswahl                                  ');
insert into label values (181, 157, 11, 0, 1, 'Prioritaet                               ');
insert into label values (181, 157, 12, 0, 1, 'Banner                                   ');
insert into label values (181, 157, 13, 0, 1, 'Warnung                                  ');
insert into label values (181, 200, 0, 0, 1, 'Globale Werte                            ');
insert into label values (181, 200, 1, 0, 1, 'Datenbank (-)                            ');
insert into label values (181, 200, 2, 0, 1, 'Benutzer  (-)                            ');
insert into label values (181, 200, 3, 0, 1, 'GSA Buchungsstelle/Aussteller            ');
insert into label values (181, 200, 4, 0, 1, 'Dialogsprache                            ');
insert into label values (181, 200, 5, 0, 1, 'Land / Laendereinstellung                ');
insert into label values (181, 200, 6, 0, 1, 'Traegertyp                               ');
insert into label values (181, 200, 7, 0, 1, 'Kategorie                                ');
insert into label values (181, 200, 8, 0, 1, 'Dienstleistungstraeger                   ');
insert into label values (181, 200, 9, 0, 1, 'Angebotstyp                              ');
insert into label values (181, 200, 10, 0, 1, 'Reisendertyp                             ');
insert into label values (181, 200, 11, 0, 1, 'Saison                                   ');
insert into label values (181, 200, 12, 0, 1, 'Ferienkatalog/Destination                ');
insert into label values (181, 200, 13, 0, 1, 'Anfangs - Datum                          ');
insert into label values (181, 200, 14, 0, 1, 'End - Datum                              ');
insert into label values (181, 200, 15, 0, 1, 'Zeitspanne                               ');
insert into label values (181, 201, 0, 0, 1, 'Output/Aktion starten...                 ');
insert into label values (181, 201, 1, 0, 1, 'Outputprogramm                           ');
insert into label values (181, 201, 2, 0, 1, 'Ausgabegeraet                            ');
insert into label values (181, 201, 3, 0, 1, 'Ausgangs Reservationsstatus              ');
insert into label values (181, 201, 4, 0, 1, 'Ziel Reservationsstatus                  ');
insert into label values (181, 202, 0, 0, 1, 'Backup...                                ');
insert into label values (181, 202, 1, 0, 1, 'Backup                                   ');
insert into label values (181, 203, 0, 0, 1, 'Restore...                               ');
insert into label values (181, 203, 1, 0, 1, 'Restore                                  ');
insert into label values (181, 209, 0, 0, 1, 'Einstellungen/Administration...          ');
insert into label values (181, 209, 1, 0, 1, 'Edition/Transfers                        ');
insert into label values (181, 209, 2, 0, 1, '--unused frame 2 --                      ');
insert into label values (181, 209, 3, 0, 1, 'Preferenzen                              ');
insert into label values (181, 209, 4, 0, 1, ' ! Software Tests                        ');
insert into label values (181, 209, 5, 0, 1, 'Globale Werte                            ');
insert into label values (181, 209, 6, 0, 1, 'Befehle                                  ');
insert into label values (181, 209, 7, 0, 1, 'Programm neu initialisieren              ');
insert into label values (181, 209, 8, 0, 1, 'Labeldatei generieren                    ');
insert into label values (181, 210, 0, 0, 1, 'Datenbanklog                             ');
insert into label values (181, 210, 1, 0, 1, 'Benutzerlog                              ');
insert into label values (181, 210, 2, 0, 1, 'Automatische Info                        ');
insert into label values (181, 210, 3, 0, 1, 'Graphik                                  ');
insert into label values (181, 210, 4, 0, 1, 'Reisendereingabe nacheinander            ');
insert into label values (181, 210, 5, 0, 1, 'Globale Werte zeigen                     ');
insert into label values (181, 210, 6, 0, 1, 'Sortieren nach: ON=Datum OFF=Alphabet.   ');
insert into label values (181, 210, 7, 0, 1, 'Audio einschalten                        ');
insert into label values (181, 210, 8, 0, 1, 'Debug Information                        ');
insert into label values (181, 210, 9, 0, 1, 'Schnelles Lesen                          ');
insert into label values (181, 211, 0, 0, 1, 'Setup Globalewerte Datei...              ');
insert into label values (181, 212, 0, 0, 1, 'travelDB beenden...                      ');
insert into label values (181, 213, 0, 0, 1, 'Applikation                              ');
insert into label values (181, 214, 0, 0, 1, 'About...                                 ');
insert into label values (182, 2, 0, 0, 1, 'Kurzeingabe Reisender                    ');
insert into label values (182, 2, 1, 0, 1, 'Anrede                                   ');
insert into label values (182, 2, 2, 0, 1, 'Identitaet                               ');
insert into label values (182, 2, 3, 0, 1, 'Reduktion                                ');
insert into label values (182, 2, 4, 0, 1, 'Reisender Typ                            ');
insert into label values (182, 2, 5, 0, 1, 'Aktionen                                 ');
insert into label values (182, 2, 6, 0, 1, 'Einstellungen                            ');
insert into label values (182, 2, 7, 0, 1, '-- unused frame --                       ');
insert into label values (182, 2, 8, 0, 1, '-- unused frame --                       ');
insert into label values (182, 3, 0, 0, 1, 'Name                                     ');
insert into label values (182, 3, 1, 0, 1, 'Vorname                                  ');
insert into label values (182, 3, 2, 0, 1, 'Geburtsdatum                             ');
insert into label values (182, 3, 3, 0, 1, 'Interner Text                            ');
insert into label values (182, 3, 4, 0, 1, 'Externer Text                            ');
insert into label values (182, 3, 5, 0, 1, 'Sprache                                  ');
insert into label values (182, 3, 6, 0, 1, '--Unused--                               ');
insert into label values (182, 4, 0, 0, 1, 'Reservationen...                         ');
insert into label values (182, 4, 1, 0, 1, 'Buchung                                  ');
insert into label values (182, 4, 2, 0, 1, 'Reservationsobjekte                      ');
insert into label values (182, 4, 3, 0, 1, 'Zusatz/Status                            ');
insert into label values (182, 4, 4, 0, 1, 'Aktionen                                 ');
insert into label values (182, 5, 0, 0, 1, 'DL:                                      ');
insert into label values (182, 5, 1, 0, 1, '.........                                ');
insert into label values (182, 5, 2, 0, 1, '.   B-Nr:                                ');
insert into label values (182, 5, 3, 0, 1, '.........                                ');
insert into label values (182, 5, 4, 0, 1, '.  B-Ref:                                ');
insert into label values (182, 5, 5, 0, 1, '.........                                ');
insert into label values (182, 5, 6, 0, 1, 'Reisender:                               ');
insert into label values (182, 5, 7, 0, 1, '.........                                ');
insert into label values (182, 6, 0, 0, 1, 'Kat Beschreibung                         ');
insert into label values (182, 6, 1, 0, 1, 'Norm. Preis                              ');
insert into label values (182, 6, 2, 0, 1, 'Pers. pro Kabine                         ');
insert into label values (182, 6, 3, 0, 1, 'Plaetze im Kontigent                     ');
insert into label values (182, 6, 4, 0, 1, 'Plaetze ausser Kontigent                 ');
insert into label values (182, 6, 5, 0, 1, 'Zusatz Platz                             ');
insert into label values (182, 7, 0, 0, 1, 'Reisender   (leer = alle)                ');
insert into label values (182, 7, 1, 0, 1, 'Reservationstatus                        ');
insert into label values (182, 7, 2, 0, 1, 'Dienstleistungstraeger                   ');
insert into label values (182, 7, 3, 0, 1, 'Dl. Traegertyp                           ');
insert into label values (182, 7, 4, 0, 1, 'Teildienstleistung                       ');
insert into label values (182, 7, 5, 0, 1, 'Dienstleistung: Anfangszeit              ');
insert into label values (182, 7, 6, 0, 1, 'Dienstleistung: Endzeit                  ');
insert into label values (182, 7, 7, 0, 1, 'Kontigent                                ');
insert into label values (182, 7, 8, 0, 1, 'Request Text                             ');
insert into label values (182, 8, 0, 0, 1, 'DLT Auswahl                              ');
insert into label values (182, 8, 1, 0, 1, 'Dienstleistungs Traeger                  ');
insert into label values (182, 8, 2, 0, 1, 'Andere DLT                               ');
insert into label values (182, 8, 3, 0, 1, 'Aktionen                                 ');
insert into label values (182, 8, 4, 0, 1, '*                                        ');
insert into label values (182, 9, 0, 0, 1, 'DLT Nr.                                  ');
insert into label values (182, 10, 0, 0, 1, 'Planungsbord                             ');
insert into label values (182, 10, 1, 0, 1, 'Ende                                     ');
insert into label values (182, 10, 2, 0, 1, 'Hilfe                                    ');
commit work;
