delete from status_werte where sta_id = -1;
delete from bezeichnung where typ >= 1000 and typ <= 1999 and bez_id = -1;
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1100);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1100);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1100);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1101);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1101);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1101);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1102);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1102);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1102);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1103);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1103);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1103);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1104);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1104);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1104);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1105);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1105);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1105);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1106);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1106);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1106);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1107);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1107);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1107);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1108);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1108);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1108);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1109);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1109);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1109);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1110);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1110);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1110);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1111);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1111);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1111);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1112);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1112);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1112);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1113);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1113);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1113);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1114);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1114);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1114);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1115);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1115);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1115);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1116);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1116);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1116);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1117);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1117);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1117);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1118);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1118);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1118);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1119);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1119);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1119);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1120);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1120);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1120);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1121);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1121);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1121);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1122);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1122);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1122);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1123);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1123);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1123);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1124);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1124);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1124);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1125);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1125);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1125);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1126);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1126);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1126);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1127);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1127);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1127);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1128);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1128);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1128);
insert into status_werte (sta_id, abk, sta, bez_id, kond, typ) values (-1, 'n/a', 'n/a', -1,-1, 1129);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 1, 'n/a', 1129);
insert into bezeichnung (bez_id, s_id, bez, typ) values (-1, 25, 'n/a', 1129);