#
#  Copyright 2002 yafra.org
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# MAKEFILE for travelDB init/unload/load
#
# copyright: yafra.org, Switzerland, 2004
#

#
# core name
#
CORENAME = db 

#--- Database target  
ifdef TDBMYSQL
	DBTARGET = mysql
endif	
ifdef TDBORACLE
	DBTARGET = oracle
endif	
ifdef TDBMSSQL
	DBTARGET = mssql
endif	
ifdef TDBODBC
	DBTARGET = odbc
endif	

ifdef TDBADABAS
	DBTARGET = adabas
endif	
ifdef TDBHPSQL
	DBTARGET = hpallbase
endif	
ifdef TDBINGRES
	DBTARGET = ingres
endif	
ifdef TDBDUMMY
	DBTARGET = dummy
endif	
