#
# MAKEFILE for travelDB common library
#
# copyright: yafra.org, Switzerland, 2004
#
# shell env: OSVERSION 7 or 8 for HP-UX Version
#            HARDWARE  HPUX400, HPUX700, PCUNIX, IBMAIX, IMBRT, DEC, SUNOS
#            SERVERNAME Name of the server (Mips, T400, Turbo, Tech)
#            BASENODE  /users/softech
#            RELEASE   vXrX
#            FOPTIONS  debug or optimize
#
#
# revision system: CVS
#
# P: PATH
# F: FLAG

CORENAME = tdbcommon
VER_NAME = "travelDB global library"
SONAMEVER = $(MAPOVER)

#
# path/flag declarations for release and develop
#
PBASE   = $(TDBS)
POBJ    = $(TDBO)
PSLIBINC = $(YAFRAINC)
PSLIB   = $(YAFRALIBPATH)
PLIB    = $(YAFRALIBPATH)
PINC = $(PBASE)/include
PSRC = $(PBASE)/lib
PMAN = $(PBASE)/man

# GNU make
# set the vpath and suffixes
#
include $(YAFRATOOLS)/include/searchpath.mak

#
# set input/output files
#
MAKEFILE   = makefile.lib
LINTOUT    = $(PSRC)/lint.out

#
# defines for the sourcecode
#
DEFINES   = -D$(PS_OS) -D$(PS_OSTYPE) -D$(PS_HW)

#
# search path for includes and librarys
#
include $(YAFRATOOLS)/include/libflags.mak

ifeq ($(PS_OS),ps_linux)
ADDON =
endif

ifeq ($(PS_OS),ps_osx)
ADDON =
endif

ifeq ($(PS_OS),ps_hpux)
ADDON = -Ae +w1
endif

ifeq ($(PS_OS),ps_cygwin)
ADDON =
endif

ifeq ($(PS_OS),ps_mingw)
ADDON =
endif

ifeq ($(PS_OS),ps_winnt)
ADDON = -W3 -Fp"C:/TEMP/vc.pch"
endif

ifeq ($(PS_COMPTYPE),ps_win)
FINCSEARCH  = -I"$(PS_LOCALDRV)$(PINC)" -I"$(PS_LOCALDRV)$(PSLIBINC)"
CFLAGS      = $(FCC) $(ADDON) $(DEFINES) \
 $(FINCSEARCH) -Fo"$(PS_LOCALDRV)$(POBJ)/"
else
FINCSEARCH  = -I$(PINC) -I$(PSLIBINC)
CFLAGS      = $(FCC) $(ADDON) $(DEFINES) $(FINCSEARCH)
endif


#
# dependencies
#
include $(YAFRATOOLS)/include/objects.mak

#
# to do list
#
include $(YAFRATOOLS)/include/librules.mak

# DO NOT DELETE THIS LINE -- make depend depends on it.
